### ISSUE TITLE
Issue writing to DuckDB data backend with type Decimal128(15, 2) for TPCH dataset

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1026]
**Describe the bug**
Working through the TPCH quickstart.  Edit spicepod.yaml with the tpch datasets:

```yaml
version: v1beta1
kind: Spicepod
name: my_test
datasets:
  - from: s3://spiceai-demo-datasets/tpch/customer/
    name: customer
    acceleration:
      enabled: true
      engine: sqlite
 
  - from: s3://spiceai-demo-datasets/tpch/lineitem/
    name: lineitem
    acceleration:
      enabled: true
      engine: duckdb
 
  - from: s3://spiceai-demo-datasets/tpch/nation/
    name: nation
    acceleration:
      enabled: true
 
  - from: s3://spiceai-demo-datasets/tpch/orders/
    name: orders
    acceleration:
      enabled: true
 
  - from: s3://spiceai-demo-datasets/tpch/part/
    name: part
    acceleration:
      enabled: true
 
  - from: s3://spiceai-demo-datasets/tpch/partsupp/
    name: partsupp
    acceleration:
      enabled: true
 
  - from: s3://spiceai-demo-datasets/tpch/region/
    name: region
    acceleration:
      enabled: true
  
  - from: s3://spiceai-demo-datasets/tpch/supplier/
    name: supplier
    acceleration:
      enabled: true
```

When starting spiced, the runtime will complain that it can't load the dataset and panic.  

**To Reproduce**
1. Edit spicepod.yaml with the dataset above.
2. Start the runtime wiht spice run
3. open the sql repl
4. run any query
5. Observe the output from the runtime:
```bash
thread 'tokio-runtime-worker' panicked at /Users/aurashb/.cargo/git/checkouts/duckdb-rs-e456b6af7d74a239/b82db39/src/vtab/arrow.rs:334:13:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
os: process already finished
aurashb@Aurashs-MacBook-Pro my_test % TRACE=1` environment variable to display a backtrace
fatal runtime error: Rust pan
```

**Expected behavior**
A correct response querying one of the datasets.

**Comment by Jeadie** [comment]
For `lineitem`, same issue as https://github.com/duckdb/duckdb-rs/issues/286 but with Arrow type `Date32`

**Comment by Jeadie** [comment]
`orders` same as above (`lineitem`)

**Comment by Jeadie** [comment]
Should be addressed in https://github.com/spiceai/spiceai/pull/1097. Retest to confirm.

**Comment by Jeadie** [comment]
New error, possibly related
```
Error receiving data: Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 48 bytes in buffers[0] in array of type Decimal128(15, 2), but got 24
```

**Comment by Jeadie** [comment]
Different issue, now related to `Decimal128(15, 2)`

**Comment by Jeadie** [comment]
Similar issue is with `eth.recent_transactions`. 

```
Error receiving data: Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 32768 bytes in buffers[0] in array of type Decimal128(38, 9), but got 16384
```

When getting one query
```
>>> select value from eth_recent_transactions limit 1
Error receiving data: Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 16 bytes in buffers[0] in array of type Decimal128(38, 9), but got 8
```
Seems we are under allocating for it.

**Comment by Jeadie** [comment]
Sqlite still doesn't support `Date32`.
```
Sqlite: ConnectionClosed
thread '<unnamed>' panicked at crates/arrow_sql_gen/src/statement.rs:357:14:
not implemented: Data type mapping not implemented for Date32
```

**Comment by Jeadie** [comment]
Also an issue with sqlite, e.q: 
```
datasets:
  - from: s3://spiceai-demo-datasets/tpch/lineitem/
    name: lineitem
    acceleration:
      enabled: true
      engine: sqlite
```

```
Status {
    code: Internal,
    message: "Arrow error: Invalid argument error: column types must match schema types, expected Decimal128(15, 2) but found Float64 at column index 0",
    source: None
}
```
