### ISSUE TITLE
Enhancement: Custom refresh SQL

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1056]
The ability to specify custom SQL query for accelerated dataset refresh using `refresh_sql`.

Example:

```yaml
datasets:
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
       enabled: true
       refresh_mode: full
       refresh_interval: 1m
       refresh_sql: |
          SELECT * FROM eth.recent_blocks WHERE number > 15000000
```

- [ ] Docs
