### ISSUE TITLE
Enhancement: Databricks Connect support

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1058]
By default, the [Databricks Data Connector](https://docs.spiceai.org/data-connectors/databricks) will use [Databricks Connect](https://docs.databricks.com/en/dev-tools/databricks-connect/index.html) based on [spark-connect-rs](https://crates.io/crates/spark-connect-rs) for query (not deltalake/delta-rs).

## Databricks Connect example

```yaml
datasets:
  - from: databricks:spiceai.datasets.my_awesome_table  // A reference to a table in the Databricks unity catalog
    name: my_delta_lake_table
    params:
      db_cluster_id: 12345
      endpoint: "https://dbc-a1b2345c-d6e7.cloud.databricks.com"
```

## DeltaLake example

The current implementation using delta-rs will continue to be supported, and can be invoked using

Example:

```yaml
datasets:
  - from: databricks:spiceai.datasets.my_awesome_table  // A reference to a table in the Databricks unity catalog
    name: my_delta_lake_table
    params:
      object_store_token: 123
      format: delta
      endpoint: "https://dbc-a1b2345c-d6e7.cloud.databricks.com"
```
