### ISSUE TITLE
Enhancement: Temporal acceleration retention

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1059]
## Goal-State/What/Result

A configurable retention mechanism on a single temporal column, to maintain the size of `append` acceleration. 

Milestones:

- M1 Function implemented and tested. Works for all 4 supported engines.
- M2 Doc, samples update.

## Why/Purpose

Storage/Memory concern on continuously growing temporal data

## By When

**Issue/Spec written and reviewed:** 4/12/2024 <AEDT>

**M1:** End of 4/17/2024 <AEDT>
**M2:** End of 4/18/2024 <AEDT>
**Done-Done:** End of 4/18/2024 <AEDT>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

- A config for temporal retention 
```yaml
from: spice.ai/eth.recent_blocks
name: eth_recent_blocks
acceleration:
  enabled: true
  refresh_mode: append
  time_column: timestamp
  time_format: unix_seconds // defaults to 'unix_milli'
  retention_period: 30m
  retention_check_interval: 30m (default)
```
- duration format follows existing convention in Spice
- time_format supports unix_milli, unix_seconds, and iso8601
- an additional capability on accelerated dataset to handle the retention/eviction
- every accelerated engine is able to perform the data eviction

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)
- #1086
- #1087 
- #1088 
- #1089 
- #1090 
- #1091 
- #1092
