### ISSUE TITLE
Enhancement: Temporal refresh data window

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1060]
## Goal-State/What/Result

A `refresh_data_window` configuration constrains the accelerated dataset refresh process to fetch data only between `now - refresh_data_window` and `now`, based on the specified `time_column` and `time_format`.

M1 - feature complete
M2 - doc/quickstart

## Why/Purpose

For recent time series data, optimizing data fetching speed, network bandwidth, memory usage, and storage capacity is crucial.

## By When

**Issue/Spec written and reviewed: Apr 23, 2024**

**M1: By the end of Apr 26, 2024**

**M2: Apr 29, 2024**

**Done-Done: Apr 29, 2024**

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

- Dataset configuration like following

    ```yaml
    datasets:
      - from: s3://spiceai-demo-datasets/taxi_trips/2024/
        name: taxi_trips
        time_column: tpep_pickup_datetime
        acceleration:
          refresh_data_window: 30m
          enabled: true
          refresh_interval: 10m
    ```

- Duration settings to be consistent with existing pattern.
- Temporal column could be `unix_seconds` , `unix_millis` , `ISO8691` , same as retention.
- The solution works as a shorthand of `refresh sql` with temporal column constraints
- It works along with `refresh sql` 
- Data connectors scope is same as the supported connectors by `refresh sql`

## How/MAP

- Using shared logic for retention and arrow schema to construct SQL
- Using shared logic from `refresh sql` and attach additional filters on top

### Implementation (issues)

- [x] #1174
- [x] #1175
- [x] #1176
- [x] #1177
- [x] #1178

##Delete any part if you can##
Not in this scope but worth a check.
- [x] #1179

**Comment by digadeesh** [comment]
Do we really want to have a flattened structure like this?  All of these properties is a property of the time_column.

What if we do something like (naming subject to change):


```yaml
acceleration:
  time_series:
    time_column: timestamp
    time_format: unix_nano
    refresh_period: 30m
  retention: 30m
```
