### ISSUE TITLE
Data Connector: Azure Data Lake Storage Gen2 (ADLSv2)

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1069]
With support for [Hierachical namespace](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace?source=recommendations)

Example:

```yaml
datasets:
  - from: adls2:/container/path
     name: datalake_storage_path
```

Supported formats:

- JSON
- CSV
- Parquet
