### ISSUE TITLE
`SELECT count(*) FROM {table_name}` doesn't work with the Sqlite Data Accelerator

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1082]
**Describe the bug**
When using `sqlite` as the Data Accelerator engine, a query with the form `SELECT count(*) FROM {accelerated_table}` returns the following error: `External error: Execution error: Unable to query arrow: ConnectionError Rusqlite("near "FROM": syntax error in SELECT  FROM taxi_trips   at offset 8")`

**To Reproduce**
Use the following spicepod:

```yaml
version: v1beta1
kind: Spicepod
name: quickstart
datasets:
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  description: taxi trips in s3
  acceleration:
    enabled: true
    refresh_interval: 30s
    refresh_mode: full
    engine: sqlite
    refresh_sql: |
      select * from taxi_trips limit 500
```

Start `spice sql` and run the query: `select count(*) from taxi_trips`

```
sql> select count(*) from taxi_trips
Error An internal error occurred while processing the query. Show technical details with '.error'
No data returned for query
sql> .error
Status { code: Internal, message: "External error: Execution error: Unable to query arrow: ConnectionError Rusqlite(\"near \"FROM\": syntax error in SELECT  FROM taxi_trips   at offset 8\")", source: None }
```

**Expected behavior**
The number of rows are returned.
