### ISSUE TITLE
Add eviction/retention handler on accelerated dataset

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1087]
```yaml
from: spice.ai/eth.recent_blocks
name: eth_recent_blocks
acceleration:
  enabled: true
  refresh_mode: append
  time_column: timestamp
  time_format: unix_seconds // defaults to 'unix_milli'
  retention_period: 30m
  retention_enabled: true
  retention_check_interval: 30m (default)
```
