### ISSUE TITLE
Enhancement: Advanced manual refresh API

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1102]
## Goal-State/What/Result

Enable two features to make acceleration refreshes, both manual and automatic, safer. 

## Why/Purpose

As more companies use dataset acceleration in production, we need to reduce the impact spice runtimes have on their data source whilst refreshing their accelerators.

## By When

**Issue/Spec written and reviewed:** 3rd September

**M1:** 5th September
**M2:** 6th September
...
**Done-Done:** 9th September

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [x] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

### Refresh Jitter
 - [x] #2491

```yaml
datasets:
 - from: databricks:my_dataset
   name: accelerated_dataset
   acceleration:
     refresh_mode: full
     refresh_check_interval: 10m
     refresh_jitter_enabled: true # Default: false
     refresh_max_jitter: 1m  # Default `refresh_check_interval`.
```

When `refresh_jitter_enabled: true` the dataset refreshes will occur with a jitter, between `[0, params.refresh_max_jitter]` (i.e. `rand(0, refresh_max_jitter)`).

For example, from above, refreshes will occur at `rand(0, 1m), 10 + rand(0, 1m), 20 + rand(0, 1m),...`

### Manual Refresh API
- [x] #2492

Add new fields to `/v1/datasets/:name/acceleration/refresh` to enable finer configuration for how to refresh the dataset. 
```shell
curl -i -XPOST 127.0.0.1:8090/v1/datasets/taxi_trips/acceleration/refresh --data '{
  "refresh_mode":  "(optional) <string>",  // `refresh_mode` options same as `acceleration.params.refresh_mode`, e.g. full, append. Default to the dataset's `refresh_mode`
  "refresh_sql": "<SQL>",
}'
```

#### Examples

Include a new parquet file from s3 (only add this new parquet, keep existing). 
```shell
curl -i -XPOST 127.0.0.1:8090/v1/datasets/taxi_trips/acceleration/refresh --data '{
  "refresh_mode":  "append",
  "refresh_sql": "select * from taxi_trips where start_time>=${parquet_start}",
}'
```

Override full table (e.g. only keep T30 in acceleration).
```shell
curl -i -XPOST 127.0.0.1:8090/v1/datasets/taxi_trips/acceleration/refresh --data '{
  "refresh_mode":  "full",
  "refresh_sql": "select * from taxi_trips where datediff(start_time, 30 days)",
}'
```

**Comment by Jeadie** [comment]
Refresh jitter UX
 ```
 datasets:
  - from: databricks:my_dataset
    name: accelerated_dataset
    acceleration:
      refresh_mode: full
      refresh_check_interval: 10m
      refresh_jitter_enable: true
      refresh_max_jitter: 1m  # rand(0, refresh_max_jitter). Default `refresh_check_interval`.
```
