### ISSUE TITLE
Spice should Auto-quote table identifiers in the connected source

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1127]
**Describe the bug**
When creating a dataset in Spice we should auto-quote the table identifiers when querying against the remote data source.

**To Reproduce**
Create a dataset with a table that has dashes.

`from: databricks:my-dashed-catalog.my-dashed-schema.my-dashed-table`

**Expected behavior**
Spice can create the data connector and has no issue querying the dataset.

**Actual behavior**

```bash
2024-04-17T00:10:49.612376Z  WARN runtime: Failed to initialize data connector for dataset databricks_demo, retrying: Unable to attach data connector databricks: Unable to resolve table provider: Analysis error: 
[INVALID_IDENTIFIER] The identifier catalog-dash-test is invalid. Please, consider quoting it with back-quotes as `catalog-dash-test`. SQLSTATE: 42602 (line 1, pos 7)

== SQL ==
catalog-dash-test.default.databricks_demo
-------^^^
```

## Databricks repro yaml:

```yaml
from: databricks:catalog-dash-test.default.databricks_demo
name: databricks_demo
params:
  endpoint: dbc-f34ee0b7-90f2.cloud.databricks.com
  databricks-cluster-id: 0411-004445-wrquoakh
```
