### ISSUE TITLE
Enhancement: Spark Data Connector

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1157]
## Goal-State/What/Result

A generic Spark Data Connector that can connect to any Spark cluster that supports the [Spark Connect API](https://spark.apache.org/docs/latest/spark-connect-overview.html).

## Why/Purpose

We already have a specific version of this for the Databricks connector - it should be relatively easy to add a generic Spark Data Connector.

## By When

**Done-Done:** Monday, April 29 (v0.12.0-alpha release)

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials

## Spec

An example Spicepod connecting to a Spark cluster
```yaml
version: v1beta1
kind: Spicepod
name: spark-app
datasets:
- from: spark:my_dataset
  name: my_dataset
  params:
    spark_remote: sc://localhost
```
- `spark_remote`: Same as the `SPARK_REMOTE` environment variable: https://spark.apache.org/docs/latest/spark-connect-overview.html#set-sparkremote-environment-variable

`spark_remote` may contain secrets, so it can optionally be specified as a secret with the key `spark_remote` in the secret `spark`. The `param` will override the `secret` if both exist.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- [ ] #1213
-
