### ISSUE TITLE
Add `refresh_period`  configuration for acceleration.

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1174]
```
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    time_column: tpep_pickup_datetime
    acceleration:
      enabled: true
      refresh_interval: 10m
      refresh_period: 10m
```
