### ISSUE TITLE
Enhancement: Option to allow queries against accelerated tables that return 0 results to fallback to federated source

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1192]
## Goal-State/What/Result

When a query that targets a dataset configured with acceleration returns 0 results, a new dataset acceleration option (`on_zero_results: use_source`) can be configured to specify that the query should fallback to querying against the federated source.

## Why/Purpose

This allows users to get the benefits of fast accelerated queries when there is data already accelerated, but still get the results from the source if needed.

## By When

Wed, Apr 24

**Issue/Spec written and reviewed:** Wed, Apr 24
**Done-Done:** Wed, Apr 24

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] ~~Samples/Quickstarts/Tutorials~~ N/A

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

`dataset.yaml`
```yaml
from: databricks:my_dataset
name: my_dataset
params:
  endpoint: my-workspace.databricks.com
  databricks-cluster-id: 1111-222222-abcdefgh
acceleration:
  enabled: true
  refresh_sql: SELECT * FROM my_dataset WHERE city = 'Seattle'
  on_zero_results: use_source
```

A query against `my_dataset` within Spice that looks like `SELECT * FROM my_dataset WHERE city = 'Portland'` would initially query against the acceleration, see that it returns 0 results and then falls back to querying against databricks directly.

## How/MAP

- [x] Add `on_zero_results: use_source` option to Acceleration parameter
- [x] Intercept query result from Accelerated table and redirect to federated table if 0 rows are returned from the table scan
- [x] Metrics to track how often the fallback occurs
- [x] Docs

### Implementation (issues)

- [x] #1196

### QA

Manual testing against our Azure Databricks instance
