### ISSUE TITLE
FallbackOnZeroResults doesn't work when the federated source is an S3 bucket

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1243]
**Describe the bug**
This Spicepod will produce an error:

```yaml
version: v1beta1
kind: Spicepod
name: fallback_demo
datasets:
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  acceleration:
    enabled: true
    refresh_sql: |
      SELECT * FROM taxi_trips WHERE passenger_count = 1;
    on_zero_results: use_source
```

with the query: `select tpep_pickup_datetime, passenger_count from taxi_trips where passenger_count = 9;`
