### ISSUE TITLE
Accelerating large dataset says its both loaded and loading.  Querying shows no results

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1249]
**Describe the bug**
I loaded a large (~1b rows) dataset from clickhouse connector.  When starting spice I see the following output:

2024-04-30T23:53:37.389858Z  INFO spiced: Metrics listening on 127.0.0.1:9000
2024-04-30T23:53:37.426022Z  INFO runtime: Loaded dataset sample_table
2024-04-30T23:53:37.426085Z  INFO runtime::flight: Spice Runtime Flight listening on 127.0.0.1:50051
2024-04-30T23:53:37.427144Z  INFO runtime::opentelemetry: Spice Runtime OpenTelemetry listening on 127.0.0.1:50052
2024-04-30T23:53:37.426106Z  INFO runtime::accelerated_table: [refresh] Loading data for dataset sample_table
2024-04-30T23:53:37.428826Z  INFO runtime::http: Spice Runtime HTTP listening on 127.0.0.1:3000

Note it says it loaded AND that its loading.  But in this case, neither is true.  The data is still loading (and it eventually OOMS because its too large for my system).

Steps:

Create a large table:
create table sample_table(id UInt64, name String, age UInt64, email String, created_date DateTime) ENGINE=MergeTree() ORDER BY id;

populate it with some random data:
INSERT INTO sample_table (id, name, age, email, created_date) SELECT number AS id, 'name' || toString(number) as name, number % 100 AS age, 'email' || toString(number) || '@example.com' AS email, today() AS created_date FROM numbers(10000000000);

Make sure I'm accelerating into arrow:
``` yaml
version: v1beta1
kind: Spicepod
name: clickhouse_quickstart
datasets:
  - from: clickhouse:sample_table
    name: sample_table
    params:
      clickhouse_host: localhost
      clickhouse_db: default
      clickhouse_tcp_port: 9000
      clickhouse_user: <redacted>
      clickhouse_pass: <redacted>
      clickhouse_secure: false
    acceleration:
      enabled: true
      refresh_mode: full
      refresh_interval: 10s
```

**Expected behavior**
Clear messaging on the status of hte data being loaded.  If its never loaded it shouldn't say so.
