### ISSUE TITLE
Can't accelerate a simple dataset into Sqlite from Clickhouse

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1254]
**Describe the bug**
A table with this Schema:
create table sample_table(id UInt64, name String, age UInt64, email String, created_date DateTime) ENGINE=MergeTree() ORDER BY id;

Fails to accelerate into SQLite. 

**To Reproduce**
Create a table in Clickhouse (see Schema above).

Try to accelerate with Spice into SQLite

```yaml
version: v1beta1
kind: Spicepod
name: clickhouse_quickstart
datasets:
  - from: clickhouse:sample_table
    name: sample_table
    params:
      clickhouse_host: localhost
      clickhouse_db: default
      clickhouse_tcp_port: 9000
      clickhouse_user: myuser
      clickhouse_pass: mypassword
      clickhouse_secure: false
    acceleration:
      engine: sqlite
      mode: file
      enabled: true
      refresh_mode: full
      refresh_interval: 10s
      refresh_sql: SELECT * FROM sample_table limit 100000;
      params:
        sqlite_file: /Users/aurashb/Development/demos/clickhouse/clickhouse.db
```

Observe the error at start:
2024-05-01T00:48:23.434047Z ERROR runtime::accelerated_table: Error adding data for sample_table: External error: Unable to insert data into the Sqlite table: Rusqlite("Failed to build insert statement: Columns and values length mismatch: 5 != 4")

**Expected behavior**
dataset loads and is accelerated in sqlite.
