### ISSUE TITLE
Spice doesn't complain when spicepod has invalid params

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1255]
**Describe the bug**
I accidentally put the wrong params in my spicepod and it didn't complain

```
version: v1beta1
kind: Spicepod
name: clickhouse_quickstart
datasets:
  - from: clickhouse:sample_table
    name: sample_table
    params:
      clickhouse_host: localhost
      clickhouse_db: default
      clickhouse_tcp_port: 9000
      clickhouse_user: <redacted>
      clickhouse_pass: <redacted>
      clickhouse_secure: false
    acceleration:
      engine: sqlite
      mode: file
      enabled: true
      refresh_mode: full
      refresh_interval: 10s
      refresh_sql: SELECT * FROM sample_table limit 100000;
      params:
        duckdb_file: /Users/aurashb/Development/demos/clickhouse/clickhouse.db:
```

**To Reproduce**
Note the spicepod above has a duckdb_file instead of sqlitefile.  

**Expected behavior**
An error indicating my configuration is wrong.
