### ISSUE TITLE
Acceleration backends return default values instead of NULL

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1262]
**Describe the bug**

Acceleration backend returns default values instead of NULL.

**To Reproduce**

1. Create test local DuckDB database

```shell
duckdb ./test.db

CREATE TABLE test_table (i INTEGER);
INSERT INTO test_table VALUES (1);
INSERT INTO test_table VALUES (NULL);
INSERT INTO test_table VALUES (2);
.exit
```

1. Create spicepod.yaml that uses `nullable_integers.db` as data source

```yaml
version: v1beta1
kind: Spicepod
name: test
datasets:
  - from: duckdb:test_table
    name: test_table
    # acceleration:
    #   enabled: true
    #   engine: duckdb
    params:
      open: ./test.db
```

3. Run `select * from test_table`  query using Spice REPL
```
sql> select * from test_table;
+---+
| i |
+---+
| 1 |
|   |
| 2 |
+---+
```
5. Uncomment acceleration section and repeat the query

```
sql> select * from test_table;
+---+
| i |
+---+
| 1 |
| 0 |
| 2 |
+---+
```
