### ISSUE TITLE
The DuckDb file connection failed to establish due to an existing open write connection

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#1264]
**Describe the bug**

When connecting to duckdb database, which has open write connection, spice fails to load:

> 2024-05-01T06:30:13.025926Z  WARN runtime: Failed to get data connector from source for dataset data: Unable to initialize data connector duckdb: Unable to create DuckDB connection pool: DuckDBError: IO Error: Could not set lock on file "data.db": Conflicting lock is held in /opt/homebrew/Cellar/duckdb/0.10.1/bin/duckdb (PID 80599) by user evgenii. See also https://duckdb.org/docs/connect/concurrency

**To Reproduce**

- prepare persisted duck db dataset

```shell
duckdb data.db # open db
```

In duckdb shell: Load httpfs and create table from s3
```
INSTALL httpfs;
LOAD httpfs;
create table data as select * from read_parquet('s3://spiceai-demo-datasets/cleaned_sales_data.parquet') limit 100;
```

- configure spicepod with duckdb dataset

```yaml
version: v1beta1
kind: Spicepod
name: duckdb-connector
datasets:
  - from: duckdb:data
    name: data
    description: data from duckdb
    params:
      open: data.db
```

- keeping duckdb repl connected, start spice

![CleanShot 2024-05-01 at 15 27 51@2x](https://github.com/spiceai/spiceai/assets/827338/9195a70b-c745-4432-8439-a2cb86eedce2)

**Expected behavior**
Spice should connect to duckdb in readonly mode
