### ISSUE TITLE
Snowflake error when accelerating tpch_sf100 database

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1289]
```
- from: snowflake:snowflake_sample_data.tpch_sf100.lineitem
  name: lineitem
  params: 
    account: ztyvqyb-vgb35424
    warehouse: COMPUTE_WH
  acceleration:
    enabled: true

```

There is the following error when trying to fetch tpch_sf100.lineitem (after ~2 mins fetching)

>2024-05-03T00:24:19.010201Z ERROR runtime::accelerated_table: [refresh] Failed to load data for dataset lineitem: Unable to scan table provider: Execution error: Unable to query arrow: Error executing query: error decoding response body
