### ISSUE TITLE
Loading multiple datasets from Spark/Databricks in different catalogs/schemas results in an error on query

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1308]
**Describe the bug**
When loading multiple datasets across different catalogs/schemas - its possible to run into the following error:

```
sql> select * from eth_blocks
Error An internal error occurred. Execute '.error' to show details.
No results.
sql> .error
Status { code: Internal, message: "Execution error: Analysis error: 
[TABLE_OR_VIEW_NOT_FOUND] The table or view `blocks` cannot 
be found. Verify the spelling and correctness of the schema and 
catalog.\nIf you did not qualify the name with a schema, verify the 
current_schema() output, or qualify the name with the correct schema 
and catalog.\nTo tolerate the error on drop use DROP VIEW IF EXISTS 
or DROP TABLE IF EXISTS. SQLSTATE: 42P01;\n'UnresolvedRelation
 [blocks], [], false\n", source: None }
```

**To Reproduce**
Login to a Sparks cluster with spice login spark --spark_remote <remote>. For a Databricks Spark cluster, this can be of the format sc://{databricks_host}:443/;user_id=spice.ai;session_id={Uuid::v4()};token={token};x-databricks-cluster-id={cluster_id}

Load datasets from the same spark cluster that live in two different datasets, and do a simple `SELECT * FROM <table>` on both. One of them should produce the above error.

Example spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: spark

datasets:
- from: spark:eth.default.blocks
  name: eth_blocks
- from: spark:eth.beacon.slots
  name: eth_beacon_slots
```

`SELECT * FROM eth_blocks`
`SELECT * FROM eth_beacon_slots`

**Expected behavior**
Both queries complete.
