### ISSUE TITLE
Dangling reference to SQLite backend when using the same .db file for acceleration the second time

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1311]
**Describe the bug**
SQLite data accelerator reports dangling reference when using the same SQLite file and same name parameter to accelerate for more than 1 time.

**To Reproduce**
* Ensure that there's no dbfile called eth_recent_blocks_sqlite.db in the same repository of spicepod
* Copy and paste this into Spicepod.yaml
```
version: v1beta1
kind: Spicepod
name: fallback_demo
datasets:
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
      engine: sqlite
      mode: file
      params:
        sqlite_file: ./random_db1.db
```
* Run `spice run`, notice that the data loaded normally
* Stop Spice run time
* Run `spice run` again, the following error message will show:
`Failed to initialize data connector for dataset eth_recent_blocks1: Unable to attach data connector spiceai: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: There is a dangling reference to the Sqlite struct in TableProviderFactory.create. This is a bug.`
* Notice: The above behavior disappear when changing the `name` parameter before starting the spice runtime for the second time. For example, using the spicepod.yaml config as below:
```
version: v1beta1
kind: Spicepod
name: fallback_demo
datasets:
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks1
    acceleration:
      engine: sqlite
      mode: file
      params:
        sqlite_file: ./random_db1.db

```

**Expected behavior**
No error message should show when accelerating using the same sqlite database file and same name for more than 1 time.
