### ISSUE TITLE
Enhancement: Snowflake more auth methods support

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1331]
## Goal-State/What/Result

Users are able to use [Snowflake Key-Pair](https://docs.snowflake.com/en/user-guide/key-pair-auth) and [Snowflake’s built-in OAuth](https://docs.snowflake.com/en/user-guide/oauth-snowflake-overview) (tentative) to authenticate and perform federated queries against their snowflake warehouse or accelerate their warehouse data using Spice.

Milestones:

- M1 Key-Pair Auth support
- M2 OAuth support (tentative)

## Why/Purpose

Users prefer to utilize familiar authentication mechanisms they are accustomed to. Key-pair and OAuth are among the most popular methods supported by Snowflake.

Support for key-pair and OAuth authentication eliminates the need for users to share passwords directly, enhancing security and user experience.

## By When

0.13-alpha

**Issue/Spec written and reviewed:** 05/07
**M1:** 05/07
**M2:** 05/10

...
**Done-Done:** 05/10

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

#### Key-pair auth

- [x] Snowflake [key-pair auth](https://docs.snowflake.com/en/user-guide/key-pair-auth) is supported by Snowflake data connector:
```
- from: snowflake:database.schema.table
  name: my_table
  params: 
    snowflake_warehouse: warehouse_name
    snowflake_auth_type: auth_key_pair | auth_snowflake (username/password; default)
    snowflake_private_key_path ./rsa_key.p8
    snowflake_passphrase_key:  The secret passphrase  for private key
    snowflake_passphrase:  The raw secret passphrase, ignored if passphrase_key is provided.
```
- [x]  Snowflake [key-pair auth](https://docs.snowflake.com/en/user-guide/key-pair-auth) support is added to Spice CLI:
```
spice login snowflake -a account -u username -k 'key-path/rsa_key.p8` -p passphrase (optional)
spice login snowflake -account -u username --private-key-path 'key-path/rsa_key.p8` -passphrase passphrase (optional)
```

#### OAuth (Tentative)

-[ ] ~Tentative: Snowflake OAuth is supported~. Decision is to skip OAuth implementation at this moment.

## How/MAP
 - [x] #1305
 - [x] #1340

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1314
- https://github.com/spiceai/spiceai/pull/1325
- https://github.com/spiceai/docs/pull/234
