### ISSUE TITLE
Enhancement: Incremental append mode based on temporal difference between acceleration and source

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1357]
## Goal-State/What/Result

A batch-based acceleration appending mechanism to only fetch the new diffs based on temporal column from the source to the acceleration.

m1 - function done
m2 - doc done

## Why/Purpose

To enable a "pseudo-append" mode for time-series data and improve the efficiency of refresh data fetches to the source data provider as requested by users.

## By When

**Issue/Spec written and reviewed:** May 13 AEST 

**M1:** May 13 AEST (stretch, same for below)
**M2:** May 13 AEST 
**Done-Done:** May 13 AEST

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [x] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] ~~Samples/Quickstarts/Tutorials~~
- [ ] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

No UX change. When time_column is specified along with append data mode, it will use the incremental append mode to fetch the new data.
```
datasets:
  - from: databricks:my_dataset
    name: accelerated_dataset
    time_column: created_at
    acceleration:
      enabled: true
      refresh_mode: append
      refresh_check_interval: 10m
      refresh_sql: |
        SELECT * FROM accelerated_dataset WHERE city = 'Seattle'
```

## How/MAP

- Move refresh into its own mod so it can be easier to add new refresh related function.
- Allow a new refresh mode - append batch (name TBD)
- Use latest temporal value to fetch data from the source when refresh mode is `append_batch`.
- Docs

### Implementation (issues)

- Refactor refresh into its own mode from accelerated table
- Add a new refresh mode `append_batch` (TBD)
- Fetch data from source table provider using latest temporal value constraint
- Modify the docs
