### ISSUE TITLE
Configure NQL via `spicepod.yaml`

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#1392]
### Requirements
- Following #1366 and #1390, allow users to specify where and how to run NQL. 

### Assumptions
1. Specifications only need to work for Text -> SQL model. We should design with the knowledge that more tasks will be needed.

### Example

```yaml
llms:
  - from: huggingface:huggingface.co/spiceai/darts:latest
    name: from_hf 
    params:
      - weights: <file> (optional) 
      - tokenizer: <file> (optional)  
      - chat_template: <file or inline> (optional) 

  - from: spice.ai/taxi_tech_co/taxi_drives/models/drive_stats:60cb80a2-d59b-45c4-9b68-0946303bdcaf
    name: from_spice
    params:
      - chat_template: <file or inline> (optional) 

  - from: file:/absolute/path/to/folder/with/model/
    name: local_model
    params:
      - weights: <file> (optional) 
      - tokenizer: <file> (optional)  
      - chat_template: <file or inline> (optional) 

  - from: openai:<model_id>
    name: my_openai_model
    params:
      model: (optional) default: gpt-3.5-turbo
```

### Secrets
 - Use `OPENAI_API_KEY` for `openai`.
 - Uses all HuggingFace env variables from [documentation](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables), especially `HF_TOKEN` or `HF_TOKEN_PATH`.
 - Uses SpiceAI authentication (i.e. from datasets) for spice.ai models.

**Comment by lukekim** [comment]
```yaml
llms:
  - from: huggingface:spiceai/darts:latest
    name: from_hf 
    params:
      - weights_path: <file> (optional) 
      - tokenizer_path: <file> (optional)  
      - system_prompt: <file or inline> (optional) 

  - from: spice.ai/taxi_tech_co/taxi_drives/models/drive_stats:60cb80a2-d59b-45c4-9b68-0946303bdcaf
    name: from_spice
    params:
      - system_prompt: <file or inline> (optional) 

  - from: file://absolute/path/to/folder/with/model/
    name: local_model
    params:
      - weights_path: <file> (optional) 
      - tokenizer_path: <file> (optional)  
      - system_prompt: <file or inline> (optional)

  - from: openai:<model_id>
    name: my_openai_model
    params:
      endpoint: (optional): default<>
      model: (optional) default: gpt-3.5-turbo
      openai_org_id: <ORG_ID>
      openai_project_id: <PROJECT_ID>
      openai_api_key: <API_KEY>
  ```
