### ISSUE TITLE
Enhancement: Specify Primary Key/Indexes for Acceleration Engines

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1412]
## Goal-State/What/Result

Primary Keys/Indexes can be created for datasets configured with a DBMS-backed Accelerator Engine (DuckDB, Sqlite, PostgreSQL). The primary key/indexes will be applied to the accelerated table, and does not need to match the values in the federated source (if any). New data that conflicts with the primary key will be dropped by default, but this is configurable to UPSERT instead.

## Why/Purpose

Primary Keys ensure data integrity in the accelerated table, which becomes more important for non-full refresh modes where data may become duplicated.

Indexes are used to speed up queries that filter on the indexed column(s).

Both of these components (primary keys/indexes) are table stakes features to be able to configure on a DBMS for increasing performance and ensuring data quality, and we should expose them.

## By When

**Issue/Spec written and reviewed:** Fri May 17
**Done-Done:** Fri June 14

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

A new `primary_key` node is added to the `acceleration` node in the dataset configuration. Multiple values can be specified here, each one should reference a column defined in that table. A compound key will be created if multiple columns are specified.

A new `indexes` node is added to the `acceleration` section. Each value can be either a column reference, in which case the equivalent of `CREATE INDEX ON my_dataset (column_ref);` will be executed against the accelerator engine, or the full `CREATE INDEX` statement can be specified (in the [PostgreSQL syntax](https://www.postgresql.org/docs/current/sql-createindex.html)).

```yaml
datasets:
- from: eth.blocks
  name: blocks
  time_column: timestamp
  acceleration:
    engine: duckdb
    refresh_mode: append
    refresh_check_interval: 1m
    retention_check_enabled: true
    retention_period: 24h
    retention_check_interval: 1h
    primary_key: "(hash, timestamp)"
    indexes:
      number: enabled # same as `CREATE INDEX ON blocks (number);`
      "(number, hash)": unique # same as `CREATE UNIQUE INDEX ON blocks (number, hash);`
    on_conflict: 
     "(hash, number)": drop # possible values: drop (default), upsert
     "(hash, timestamp)": upsert
```

Take a look at sqlmesh: https://sqlmesh.readthedocs.io/en/stable/

Specifying `primary_key` or `indexes` with `engine: arrow` is not supported and will report a warning.

If there are multiple rows in a single Append data payload that violate a primary key constraint, that payload will be rejected. (This matches PostgreSQL behavior)

## How/MAP

`sqlparser-rs` can correctly parse CREATE INDEX statements in the PostgreSQL syntax: https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/mod.rs#L2035

If specifying the full `CREATE INDEX` statement under `indexes`, it should reference the dataset name, otherwise it will report an error. (Alternative is to ignore table name and let them put whatever?)

### Implementation (issues)

- [x] #1630
- [x] #1631
- [x] #1689
- [x] #1632
- [x] #1633
- [x] #1634
- [x] Warning when Arrow engine tries to apply indexes
- [x] #1652
- [x] #1659
- [x] Performance testing on loading data times with primary keys/indexes
- [x] Performance testing on query times with primary keys/indexes
- [x] Add docs for primary key/indexes feature
- [x] Add sample for primary key/indexes

### QA

Test that a single data update that violates a primary key is rejected from the source.
Test that duplicate data is dropped on Append mode when a primary key is specified and `primary_key_on_conflict` is set to `drop`.
Test that new rows that would violate a primary key in Append mode are upserted instead when `primary_key_on_conflict` is set to `drop`.
