### ISSUE TITLE
Changing wrongly configured dataset to correct configuration doesn't cause dataset reloading in S3

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1458]
**Describe the bug**
Using S3 connector and start the spice runtime with a wrongly configured endpoint. And then change the wrong endpoint to the correct one, the correct configuration doesn't cause dataset to be loaded

**To Reproduce**
Use the following wrong spicepod configuration, start spice runtime
```
from: s3://spiceai-demo-datasets/taxi_trips/202
name: taxi_trips
description: taxi trips in s3
acceleration:
  enabled: true
  refresh_mode: append
  refresh_check_interval: 10s
```
Logs shows that there's error when connecting to S3.
```
2024-05-21T23:20:45.668129Z  INFO spiced: Metrics listening on 127.0.0.1:9000
2024-05-21T23:20:46.021968Z  WARN runtime: Cannot connect to S3. Object Store error: Object at location taxi_trips/202 not found: Client error with status 404 Not Found: No Body
```
Change the dataset to correct configuration as below
```
from: s3://spiceai-demo-datasets/taxi_trips/2024/
name: taxi_trips
description: taxi trips in s3
acceleration:
  enabled: true
  refresh_mode: append
  refresh_check_interval: 10s
```
Log still shows that there's error connecting to S3.

**Expected behavior**
Dataset should get correctly reloaded after the configuration is updated

**Screenshots**
![image](https://github.com/spiceai/spiceai/assets/130200611/c49635fe-5c2a-4c05-8d5d-e8d7594054cd)
