### ISSUE TITLE
spiceai data connector returns lengthy error when dataset from is misconfigured

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1462]
**Describe the bug**
spiceai data connector returns lengthy error when dataset name is misconfigured

**To Reproduce**
use the following wrong configuration, which contains a wrong dataset from in spicepod.yaml
```yaml
from: spiceai:path.to.my_dataset
name: my_dataset
acceleration:
  mode: file
```

A very wordy error will be presented
![image](https://github.com/spiceai/spiceai/assets/130200611/4606507a-72ec-4216-9b99-2ae3a42ca65e)

**Expected behavior**
Error for misconfigured `from` in spice ai data connector should be succinct and actionable
