### ISSUE TITLE
Unable to connect to FTP server vsftpd

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1464]
**Describe the bug**
When trying to connect using the FTP Data Connector to an FTP server hosted by [vsftpd](https://security.appspot.com/vsftpd.html), it fails with the following error:

> 2024-05-22T00:00:31.278761Z  WARN runtime: Cannot connect to FTP. Object Store error: Generic FTP error: Invalid response: [550] 550 No support for resume of ASCII transfer.

**To Reproduce**
Create an Ubuntu VM/container and install vsftpd. This guide can be used: https://www.geeksforgeeks.org/how-to-setup-and-configure-an-ftp-server-in-linux/

```bash
sudo apt install vsftpd
sudo systemctl status vsftpd
sudo adduser ftpuser
sudo mkdir /ftp
sudo chown ftpuser /ftp
sudo nano /etc/vsftpd.conf # Use the contents of the below vsftpd.conf
```

`/etc/vsftpd.conf`
```conf
listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
secure_chroot_dir=/var/run/vsftpd/empty
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO

pasv_min_port=5000
pasv_max_port=10000
local_root=/ftp
```

Spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: ftp

datasets:
- from: ftp:[IP of VM/Container]/demo.parquet
  name: demo
  params:
    file_format: parquet
    ftp_user: ftpuser
    ftp_pass: ftppass
```

**Expected behavior**
The FTP connection works. Using a separate FTP client (Transmit 5) works.

**Screenshots**
<img width="1242" alt="Screenshot 2024-05-22 at 9 15 30 AM" src="https://github.com/spiceai/spiceai/assets/879445/9e247968-fc05-4d53-ada1-5519978ad1ab">
