### ISSUE TITLE
DuckDB data connector does not load support FROM clauses

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1465]
Principle: Spice duckdb data connector from should support [EVERYTHING] supported by `select * from [EVERYTHING]` in duckdb

Example:

```yaml
- from: duckdb:read_parquet('train-00000-of-00011.parquet');
    name: star_coder
    params:
      open: ./test.db
```

Produces:

```bash
2024-05-22T00:13:38.382337Z  INFO runtime: Registered dataset tpch_customer
2024-05-22T00:13:38.395784Z  WARN runtime: Unable to get read provider for duckdb: Unable to get schema: Unable to get schema: Catalog Error: Table with name read_parquet('train-00000-of-00011.parquet'); does not exist!
Did you mean "pg_attribute"?
LINE 1: SELECT * FROM "read_parquet('train-00000-of-00011.par...
```

Expected to use anything that DuckDB supports.

- https://duckdb.org/docs/data/overview
- https://duckdb.org/docs/sql/query_syntax/from.html

E.g.

DuckDB:
```sql
FROM <param>;
```

Spicepod:
```yaml
datasets:
  - from: duckdb:<param>
```

Solution: Support a `from_duckdb_function` parameter to determine whether the dataset is from duckdb table or function. `from_duckdb_function`  default to be false.

Examples:
* Read from parquet using read_parquet function in duckdb
```yaml
  - from: duckdb:read_parquet('test_parquet.parquet');
    name: test_parquet
    params:
      open: ./test.db
      from_duckdb_function: true
```
* Read from parquet without providing open parameter
```yaml
  - from: duckdb:read_parquet('test_parquet.parquet');
    name: test_parquet
    params:
      from_duckdb_function: true
```
* Read from google sheet
```yaml
- from: SELECT *
  FROM read_csv_auto('https://docs.google.com/spreadsheets/export?format=csv&id=1GuEPkwjdICgJ31Ji3iUoarirZNDbPxQj_kf7fd4h4Ro');
   name: google_sheet_table
   params:
      open: ./test.db
      from_duckdb_function: true
```
* Read from a table named `read_parquet('test_parquet.parquet')` in duckdb
```yaml
  - from: duckdb:read_parquet('test_parquet.parquet');
    name: test_parquet
    params:
      open: ./test.db
      from_duckdb_function: false
```
```yaml
  - from: duckdb:read_parquet('test_parquet.parquet');
    name: test_parquet
    params:
      open: ./test.db
```
* Read from csv file
```yaml
  - from: duckdb:"./test.csv";
    name: my_table
    params:
      open: ./test.db
      from_duckdb_function: false
```
```yaml
  - from: duckdb:"./test.csv";
    name: my_table
    params:
      open: ./test.db
```
```yaml
  - from: duckdb:read_csv('test.csv');
    name: my_table
    params:
      open: ./test.db
      from_duckdb_function: true
```

**Comment by Jeadie** [comment]
We are going to initially keep the following, more arbitrary `from` clause out of scope
```yaml
- from: SELECT *
  FROM read_csv_auto('https://docs.google.com/spreadsheets/export?format=csv&id=1GuEPkwjdICgJ31Ji3iUoarirZNDbPxQj_kf7fd4h4Ro');
   name: google_sheet_table
   params:
      open: ./test.db
      from_duckdb_function: true
```

A similar effect can be had with a basic DuckDB function and a view, i.e.
```yaml
datasets:
- from: duckdb:read_csv_auto('https://docs.google.com/spreadsheets/export?format=csv&id=1GuEPkwjdICgJ31Ji3iUoarirZNDbPxQj_kf7fd4h4Ro')
  name: base_ds
view:
  - name: desired_table
     sql: SELECT a, b, c FROM base_df
```
