### ISSUE TITLE
Unable to accelerate Spark quick start dataset

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1466]
**Describe the bug**

There is the following error when I try to enable acceleration for Spark quick start sample dataset

>2024-05-22T00:08:10.489778Z ERROR runtime::accelerated_table::refresh: [refresh] Failed to load data for dataset nyc_taxi_trip: Unable to get data from connector: Unable to scan table provider: Execution error: Io error: status: Unknown, message: "h2 protocol error: error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} }

**To Reproduce**

1. Follow instructions to create the spice app connected to Spark: https://github.com/spiceai/quickstarts/pull/115
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spark:nyc_taxi_trip
    name: nyc_taxi_trip
    params:
      spark_remote: sc://localhost:15002
```
1. Update spicepod to enable acceleration
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spark:nyc_taxi_trip
    name: nyc_taxi_trip
    params:
      spark_remote: sc://localhost:15002
    acceleration:
      enabled: true
```
1. See error

>2024-05-22T00:08:10.489778Z ERROR runtime::accelerated_table::refresh: [refresh] Failed to load data for dataset nyc_taxi_trip: Unable to get data from connector: Unable to scan table provider: Execution error: Io error: status: Unknown, message: "h2 protocol error: error reading a body from connection: stream closed because of a broken pipe", details: [], metadata: MetadataMap { headers: {} }

**Expected behavior**
Accelerated table version is created or there is user friendly error
