### ISSUE TITLE
Refresh Mode for accelerated Spice AI data source

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#1467]
**Describe the bug**
Various issues when using different parameters for refreshing an accelerated dataset.

```yaml
datasets:
  # ❌ Does not refresh the accelerated table
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
      enabled: true
      refresh_mode: full

  # ❌ Does not refresh the accelerated table
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
      enabled: true
      refresh_mode: append

  # ✅ Refreshes the accelerated table
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
      enabled: true
      refresh_mode: full
      refresh_check_interval: 10s
      
  # ❌ Does not refresh the accelerated table
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    acceleration:
      enabled: true
      refresh_mode: append
      refresh_check_interval: 10s
```
