### ISSUE TITLE
Improve Spark connection error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1468]
**Describe the bug**

I see the following error when running Spice with Spark dataset that unable to connect to Spark

>2024-05-22T01:03:34.057228Z  WARN runtime: Tonic Transport error: transport error

**To Reproduce**
1. Create the following Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spark:nyc_taxi_trip
    name: nyc_taxi_trip
    params:
      spark_remote: sc://does-no-exist:15002
```
1. Run Spice
1. See warning

>Spice.ai runtime starting...
2024-05-22T01:05:30.831888Z  INFO spiced: Metrics listening on 127.0.0.1:9000
2024-05-22T01:05:30.984759Z  WARN runtime: Tonic Transport error: transport error
2024-05-22T01:05:46.069022Z  WARN runtime: Tonic Transport error: transport error
2024-05-22T01:06:01.154857Z  WARN runtime: Tonic Transport error: transport error

**Expected behavior**
The warning points that Spark connector is unable to connect to Spark server
