### ISSUE TITLE
Spark should not crash when unable to parse `spark_remote` param

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1469]
**Describe the bug**

Spice crashes when failed to parse the connection URL (`spark_remote`), for example `sc://localhost` (should be `sc://localhost:15002`)

**To Reproduce**

1. Create Spicepod
```
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
  - from: spark:nyc_taxi_trip
    name: nyc_taxi_trip
    params:
      spark_remote: sc://localhost
```
1. Run Spice
1. See error

>Spice.ai runtime starting...
2024-05-22T01:10:17.615471Z  INFO spiced: Metrics listening on 127.0.0.1:9000
thread 'main' panicked at /Users/sg/.cargo/git/checkouts/spark-connect-rs-9a8e8da9cd554d24/29b0634/core/src/session.rs:47:66:
called `Result::unwrap()` on an `Err` value: InvalidConnectionUrl("Failed to parse the connection URL")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
exit status 101
