### ISSUE TITLE
Large Utf8 not supported in DuckDB data accelerator

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1481]
**Describe the bug**
Large Utf8 not supported in DuckDB data accelerator due to the lack of support in duckdb-rs, will require upstream fix to 

**To Reproduce**
Use the folllowing spicepod.yaml config:
```yaml
from: s3://spiceai-demo-datasets/taxi_trips/2024/
name: taxi_trips
description: taxi trips in s3
acceleration:
  engine: duckdb
  enabled: true
  refresh_check_interval: 10s
```

Error log shown:
`2024-05-22T00:06:46.964431Z WARN runtime: Unable to attach data connector s3: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create duckdb table: Invalid Input Error: column Field { name: "store_and_fwd_flag", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } is not supported yet, please file an issue https://github.com/wangfenjin/duckdb-rs`

**Expected behavior**
Large Utf8 is supported in duckdb-rs and spice duckdb data connector
