### ISSUE TITLE
Clickhouse data connector shouldn't require password 

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1482]
**Describe the bug**
Clickhouse can be connected without password, however, current clickhouse connector will require user to input a password, and user cannot connect without password.

**To Reproduce**
Connect to clickhouse with following spicepod config. Here my clickhouse server is exposed at port 19000
```yaml
  - from: clickhouse:default.sample_table
    name: my_dataset
    params:
      clickhouse_host: localhost
      clickhouse_tcp_port: 19000
      clickhouse_db: default
      clickhouse_user: default
```

The following error will show:
![image](https://github.com/spiceai/spiceai/assets/130200611/79042643-ff5d-4124-8d40-f15ddac68c17)

The workaround is to use a connection string without password. But ideally, user should be able to connect using the spicepod configuration above.
```yaml
  - from: clickhouse:default.sample_table
    name: my_dataset
    params:
      clickhouse_connection_string: tcp://default@localhost:19000/default
      clickhouse_connection_timeout: 10000
      clickhouse_secure: false
```

**Expected behavior**
User can connect to clickhouse data connector without `clickhouse_pass` or `clickhouse_pass_key`
