### ISSUE TITLE
DuckDB data connector should create a DuckDB file for user when .open parameter is not specified

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1483]
- Scoped out from https://github.com/spiceai/spiceai/issues/1463

**Comment by Sevenannn** [comment]
Need more clarity. 
* What name should the duckdb file created for user be. Should it be another parameter configured by user?
* What will be the use case for the newly created duckdb file? Since there's will be no table to connect to, and runtime will give a data connector failure.

**Comment by Sevenannn** [comment]
Principle: Spice duckdb open parameter should mirror the DuckDB CLI `duckdb` command
* Create in-memory database only when no open parameter is provided.
```yaml
  - from: duckdb:not.exist.table;
    name: create_inmem_duckdb
```
* Open or create persistent database file specified by [FILE_NAME] only when the open parameter is provided.

Open persistent database file specified by [FILE_NAME]
```yaml
  - from: duckdb:my.awesome.table;
    name: create_file_based_duckdb
    params:
      open: ./exist.db
```
Create persistent database file specified by [FILE_NAME]
```yaml
  - from: duckdb:not.exist.table;
    name: create_file_based_duckdb
    params:
      open: ./not_exist.db
```
