### ISSUE TITLE
Spice should load datasets concurrently instead of sequentially

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1525]
**Describe the bug**
Currently when Spice starts up, it loads datasets sequentially. One of the steps to loading a dataset is that is queries the remote source to check the connection and fetch the schema. This can be slow, and if there are many datasets it can cause the startup to take a while.

**To Reproduce**
Use this spicepod, run spice and observe the slow startup

```yaml
version: v1beta1
kind: Spicepod
name: spiceai

datasets:
- from: eth.recent_blocks
  name: blocks
- from: eth.recent_transactions
  name: tx
- from: eth.recent_logs
  name: eth.logs
- from: eth.recent_traces
  name: eth.recent_traces
- from: eth.beacon.slots
  name: eth_beacon.slots
```

**Expected behavior**
Each dataset is loaded concurrently, improving the startup time.
