### ISSUE TITLE
Enhancement: Move Databricks Delta implementation from delta-rs to delta-kernel-rs

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1696]
## Goal-State/What/Result

The Spice Databricks Deltalake mode uses [`delta-kernel-rs`](https://github.com/delta-incubator/delta-kernel-rs) instead of `delta-rs`. Spice will also support connecting to any object store that Databricks supports (i.e. AWS S3, Azure Blob, GCS), not just S3.

## Why/Purpose

Connecting directly to object store to perform queries on Deltalake tables will be the most performant way to query Databricks data stored in Deltalake tables. Unfortunately the current implementation of this approach bypasses the Unity Catalog, which is a non-starter for many enterprises that would like to control data governance via a centralized catalog. Fortunately, those customers have an alternative in Spice by using Spark Connect or ODBC. The downside is a loss in performance relative to what can be achieved with a direct Deltalake connection.

The `delta-kernel-rs` incubation project is a lightweight implementation of the Deltalake protocol and allows Spice to remove usage of `delta-rs` which is a burden on maintainability since the Spice maintainers often need to manage [a fork](https://github.com/spiceai/delta-rs/tree/spiceai-39) to ensure alignment on DataFusion versions. `delta-rs` provides many more features than Spice actually uses, so a smaller binary is possible by removing `delta-rs` as well.

The downside of replacing `delta-rs` with `delta-kernel-rs` is that the kernel project is still in alpha and may have bugs that the `delta-rs` project doesn't. Another downside is that the kernel project only (currently?) supports querying, not updating delta tables, whereas the `delta-rs` project supports both.

## By When

**Issue/Spec written and reviewed:** July 2, 2024
**Done-Done:** July 4, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

The current YAML for specifying a direct connection is by setting a `mode` option to `s3`:

```yaml
params:
  # The execution mode for querying against Databricks.
  # The default is spark_connect. Possible values:
      # spark_connect: Use Spark Connect to query against Databricks.
      # s3: Query directly from Delta Tables in S3.
  mode: spark_connect # / s3
  # The format of the data to query. The default is deltalake. Only valid when mode is s3. Possible values:
    # deltalake: Query Delta Tables.
  format: deltalake 
```

This will be changed to specifying `delta_lake` for `mode` and removing the `format` parameter:

```yaml
params:
  # The execution mode for querying against Databricks.
  # The default is spark_connect. Possible values:
      # spark_connect: Use Spark Connect to query against Databricks.
      # delta_lake: Query directly against Delta Tables in object stores.
  mode: spark_connect # / delta
  # format goes away with this change, since its implicit in mode
```

Create a DataFusion TableProvider based on the `delta-kernel-rs` Default Engine which can scan a Delta table and return Arrow records.

Ensure that filter pushdown is supported by converting DataFusion expressions to the equivalent `delta-kernel-rs` expressions in their `ScanBuilder`.

## How/MAP

TBD

### Implementation (issues)

- TBD

### QA

- [x] Test with large Delta tables in S3
- [x] Test with large Delta tables in Azure
- [x] ~~Test with large Delta tables in GCS~~
- [x] Test regressions from `delta-rs`
