### ISSUE TITLE
Enhancement: Load secrets from multiple secret stores & secrets UX refresh

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1701]
## Goal-State/What/Result

Simple, easy-to-understand secrets UX that allows specifying which store a secret should be loaded from.

## Why/Purpose

The current experience for configuring secrets is hard to understand and the code to support it is more complicated than it needs to be. We also want to give flexibility to load secrets from environment variables + another secret store.

## By When

**Issue/Spec written and reviewed:** July 15, 2024
**Done-Done:** July 19, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

The current UX for configuring secrets relies on a lot of "magic" that requires understanding that secrets are namespaced based on the connector that is used. The default file we use is a TOML file instead of a more familiar `.env` most developers have used before. It isn't clear from the spicepod YAML if a secret is needed or not, that feedback only comes at runtime and is hard to discover.

This enhancement will make the secrets experience much simpler and easier to understand. It will be explicit, so its easy to see when secrets are required and where they come from. It will also make the code simpler by removing concepts that are no longer required.

The secrets implementation will be changed as follows:
- The "secret" namespace will be removed. All secrets will live in a flat namespace that isn't separated by connector.
- The method of specifying `<secret_name>-key` in the `params` for telling Spice which secret to use will be removed.
- Multiple secret stores can be specified at the top of a Spicepod. The `file` and `env` secrets stores will be combined into a single `env` secret store that reads from the environment, but also natively knows how to read from a `.env` file. The `.env` file is the [standard format developers](https://www.npmjs.com/package/dotenv#%EF%B8%8F-usage) expect. We will no longer have a global auth file, i.e. `~/.spice/auth` will no longer be referenced. Only project-specific `.env` files.

```yaml
secrets:
  - from: env
    name: env
    params:
      file_path: /path/to/custom/.env # Optional, default is `.env` and `.env.local` next to the spicepod.yaml
```

- Referencing a secret is done directly in the `params` and uses the syntax `${{ <store_name>:<key> }}` where `store_name` is the name of the secret store referenced in the spicepod, and `key` is the name of the key within that secret store to pull the secret value from. For the `env` secret store, the `key` is the name of the environment variable. For other examples see the examples section below.

```yaml
datasets:
  - from: postgres:my_table
    name: my_table
    params:
      pg_host: localhost
      pg_port: 5432
      pg_password: ${{ env:MY_PG_PASS }} # pulls the password from the environment variable `MY_PG_PASS` which can be in the environment or specified in a .env file
```

- An alternative to referencing a store name explicitly is to use `${{ secrets:<key> }}`. This indicates we want to use a secret named `<key>` and Spice will check all of the loaded secret stores in order of precedence until it finds it.
- The secret stores are ordered in the YAML file from lowest to highest precedence. i.e. a store appearing last has the highest precedence and will override the other stores.
- Not specifying a required password is allowed, Spice will try to load a sensible default that roughly matches the behavior we have today around secrets.
  - Each connector will have a prefix it expects, i.e. the postgres connector prefix will be `pg_`. Then the rule for finding the default environment variable name is `SPICE_{PREFIX}{KEY}`. i.e. `SPICE_PG_PASSWORD`. This will be repeated for each supported secret store, with a format that makes sense for it.

- Using the secret within a larger string is allowed. This allows for constructing a connection string with non-sensitive info along with the embedded passwords, i.e.:

```yaml
datasets:
  - from: postgres:my_table
    name: my_table
    params:
      pg_connection_string: postgresql://postgres:${{ env:MY_PG_PASS }}@localhost:5432/my_db
```

#### `env`

```yaml
secrets:
  - from: env
    name: my_env
    params:
      file_path: /path/to/.my_env
```

Reference in `params` with `${{ my_env:SECRET_KEY }}` or `${{ secrets:SECRET_KEY }}`.

#### `kubernetes`

Kubernetes supports namespacing secret keys using the [Secret API](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/). Therefore, the `kubernetes` secret store requires specifying the secret name that will be loaded after the colon `:` in `kubernetes:<secret_name>`. Loading data from multiple secrets requires defining multiple kubernetes secret stores, each referencing a different secret name.

```yaml
secrets:
  - from: kubernetes:my_secret_name
    name: k8s_some_secret_name

datasets:
  - from: postgres:my_table
    name: my_table
    params:
# Precedence is looking for `my_pg_password` in `kubernetes:my_secret_name`
      pg_password: ${{ secrets.my_pg_password }}
```

Reference in `params` with `${{ k8s_some_secret_name:my_pg_password }}` or `${{ secrets:my_pg_password }}`.

#### `keyring`

The `keyring` secret store no longer needs a single password stored as a JSON object with the keys of the JSON object being the secret keys. Now each individual key can be used as intended, with the name specified explicitly in the YAML.

```yaml
secrets:
  - from: keyring
    name: keyring

datasets:
  - from: postgres:my_table
    name: my_table
    params:
# Precedence is looking for `my_pg_password` in `keyring`
      pg_password: ${{ secrets.my_pg_password }}
```

Reference in `params` with `${{ keyring:my_pg_password }}` or `${{ secrets:my_pg_password }}`.

#### `aws_secrets_manager`

Similar to Kubernetes, `aws_secrets_manager` namespaces secrets.

```yaml
secrets:
  - from: aws_secrets_manager:my_secret_name
    name: aws_secret

datasets:
  - from: postgres:my_table
    name: my_table
    params:
# Precedence is looking for `my_pg_password` in `aws_secret:my_secret_name`
      pg_password: ${{ secrets.my_pg_password }}
```

Reference in `params` with `${{ aws_secret:my_pg_password }}` or `${{ secrets:my_pg_password }}`.

#### `precedence`

```yaml
secrets:
  - from: kubernetes:my_secret_name
    name: k8s_pg
  - from: kubernetes:some_other_secret
    name: k8s_other
  - from: env # Highest precedence, will override others if exists
    name: env

datasets:
  - from: postgres:my_table
    name: my_table
    params:
# Precedence is looking for `my_pg_password` in `env`, `kubernetes:some_other_secret`, and `kubernetes:my_secret_name`
      pg_password: ${{ secrets.my_pg_password }}
```

## How/MAP

- [x] We let users that are using the old style of secrets know that they need to migrate.
- [x] Docs
- [x] Quickstarts
- [x] Samples
- [x] CLI changes

### Implementation (issues)

- 
-
