### ISSUE TITLE
Enhancement: Anonymous and optional usage telemetry

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1715]
## Goal-State/What/Result

Opt-out, anonymous, privacy-preserving usage telemetry of Spice is collected, including versions, component usage, and runtime performance KPIs.

## Why/Purpose

To understand Spice usage so that future versions can be improved.

## By When

**Issue/Spec written and reviewed:** Tue, Jul 30
**Done-Done:** v0.17.2-beta (Mon, Aug 26)

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Scope

While the spec makes provisions for the Spice SDKs to also make use of the Usage Telemetry APIs, this spec only focuses on the metrics for `spiced`.

### Enablement

Anonymous usage telemetry is enabled by default, but supports opt-out.

The usage telemetry components can be disabled at compile-time by removing the `telemetry` feature flag, which will remove all usage telemetry code from being compiled into the final binary.

It can also be disabled at runtime via a `spiced` command line argument `--telemetry-enabled false`.

Disabling via the `runtime` section in `spicepod.yml` is possible with:

```yaml
runtime:
  telemetry:
    enabled: false
```

### Anonymous Instance ID

An `instance_id` is populated for each telemetry metric. This `instance_id` will be a SHA256 hash of the current hostname + the name of the root spicepod. 
`instance_id = SHA256(hostname + spicepod.name)`

This allows aggregating and de-duplicating telemetry metrics by unique instances. The hash protects privacy by making it impossible get the original hostname/spicepod name inputs.

### Usage Metrics

All usage metrics are batched, aggregated and sent once an hour, except `ping` which is every 5 minutes. The metrics will be kept in Arrow format (see below for schema) and sent via Flight.

- Ping (`ping`)
  - Dimensions: N/A
- Bytes scanned (`bytes_scanned`)
  - Description: Total bytes scanned by DataFusion when serving queries during the interval period.
  - Dimensions: `data_connector`, `accelerator`, `protocol`
  - For accelerated queries, this will accurately represent the number of bytes scanned to serve a query. 
  - For federated queries, this will reflect the number of bytes returned by the remote source since there isn't a way to tell how many bytes the source system scanned to serve the query.
- Bytes returned (`bytes_returned`)
  - Description: Total bytes returned by Spice to the requesting clients during the interval period.
  - Dimensions: `data_connector`, `accelerator`, `protocol`
  - For accelerated queries, this will accurately represent the number of bytes scanned to serve a query. 
  - For federated queries, this will reflect the number of bytes returned by the remote source since there isn't a way to tell how many bytes the source system scanned to serve the query.
- Total query time (`query_duration_ms`)
  - Description: The total amount of time spent planning and executing queries during the interval period.
  - Dimensions: `data_connector`, `accelerator`, `protocol`
  - Will be rendered in the final chart as `Total query minutes` to indicate the volume of queries being executed.
- Aggregate query count (`query_count`)
  - Description: The number of individual queries executed.
- P90/95/99 query time
  - Raw Metric: `query_duration_ms` (re-used from above)
  - Aggregated Metrics: `query_duration_ms_p90`, `query_duration_ms_p95`, `query_duration_ms_p99`
  - Description: The time spent planning & executing queries broken down into percentiles per-query.
  - Raw Dimensions: `data_connector`, `accelerator`, `protocol`
  - Aggregated Dimensions: None, `data_connector`, `accelerator`
    - Note: Spice needs to calculate any aggregations that SCP needs locally, as its impossible to generate on the server without the raw data.
- P90/95/99 query execution time
  - Raw Metric: `query_execution_duration_ms`
  - Aggregated Metrics: `query_execution_duration_ms_p90`, `query_execution_duration_ms_p95`, `query_execution_duration_ms_p99`
  - Description: The time spent only on executing queries broken down into percentiles per-query. This returns 0 for cached queries.
  - Raw Dimensions: `data_connector`, `accelerator`, `protocol`
  - Aggregated Dimensions: None, `data_connector`, `accelerator`

The percentile calculations will be done in DataFusion via the [`approx_percentile_cont`](https://datafusion.apache.org/user-guide/sql/aggregate_functions.html#approx-percentile-cont) method. This is based on the t-digest algorithm which is the gold standard for calculating percentiles in constant memory on large datasets. It calculates the exact result on small datasets.

#### Dimensions added to all telemetry

These dimensions are included for all metrics, even those marked with `N/A` above.

- InstanceId (`instance_id`)
	- `spiced` SHA256(hostname + spicepod.name), enriched to SHA256(instance_id + ip) on server
	- `*-sdk` SHA256(hostname + spiced.host:port), enriched to SHA256(instance_id + ip) on server
- Spicepod ID (`spicepod_id`)
    - `spiced` SHA256(spicepod.name)
- Client (`client`)
	- `spiced` 
	- `go-sdk`
	- `java-sdk` 
- Client Version (`client_version`)
	- `v0.17.1-beta`

#### Specific Dimensions

The dimensions listed here are only added to the metric items when indicated in the above section defining each metric

- `accelerator`
  - Description: The data accelerator that was used (if any) in the measured operation
  - Values: `duckdb` | `sqlite` | `postgres` | `arrow` | `none` 
- `data_connector`
  - Description: The data connector that was used in the measured operation
  - Values: `databricks` | `postgres` | etc
- `model_provider`
  - Description: The model that was used in the measured operation
  - Values: `huggingface` | `openai` | etc
- `client_protocol`
  - Description: The protocol the client used to initiate the query.
  - Values: `http` | `flight` | `flightsql` | `internal`
    - Note: `internal` will represent any query not initiated by the user, such as acceleration refreshes or schema inference queries.

### Client Usage Telemetry Arrow Schema

This is the Arrow schema that telemetry clients (`spiced`, `go-sdk`, `java-sdk`, etc) will send to the flight endpoint at https://data.spiceai.io

```yaml
fields:
  # The name of the aggregated metric, as defined above
  - metric: utf8 (nullable: false)
  # One of sum, gauge, histogram
  - metric_type: utf8 (nullable: false)
  # (Optional) Unix timestamp in nanoseconds when the aggregation period started, if applicable for the metric type. Applies to sum, histogram.
  - start_timestamp_nano: int64 (nullable: true)
  # Unix timestamp in nanoseconds when metric was recorded.
  - timestamp_nano: int64 (nullable: false)
  - dimensions: list<struct<key: utf8 (nullable: false), value: utf8 (nullable: true)>> (nullable: true)
      # SHA256(hostname + spicepod.name).
      - instance_id: utf8 (required)
        # SHA256(spicepod.name)
      - spicepod_id: utf8
      - client: utf8 (required)
      - client_version: utf8 (required)
  # The value of the metric.
  - value: float64 (nullable: true)
```

## How/MAP

The required telemetry based on queries will be extracted from the `runtime.query_history` table. The schema of that table will be updated to include any missing columns needed.

A new `telemetry` crate will be added which will contain the interface to the mechanism that actually transmits the telemetry to the SCP. This can be re-used by the Rust SDK.

### Implementation (issues)

- [x] #2209
- [x] #2241
- [x] #2210
- [x] #2211
- [x] #2212
- [x] #2213
- [x] #2214
- [x] #2215
- [x] #2216
- [x] #2217
- [x] #2218
- [x] #2219
- [x] #2220
- [x] #2221
- [x] #2222
- [x] Docs to explain what telemetry we collect and how to disable
