### ISSUE TITLE
Unable to accelerate dataset with struct field using PostgreSQL

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1726]
**Describe the bug**
Unable to accelerate dataset with struct field using PostgreSQL

**Repo steps**

1. Create test duckdb dataset with struct column:
```
echo "   
CREATE TABLE my_table (
    s STRUCT(v VARCHAR, i INTEGER),
    key INT
);

INSERT INTO my_table (s, key) VALUES
(STRUCT_PACK(v := 'a', i := 42), 1);

SELECT * FROM my_table;
" | duckdb my_database.duckdb
```
1. Create Spicepod with the dataset created

```
version: v1beta1
kind: Spicepod
name: test
datasets:
  - from: duckdb:my_table
    name: my_table
    params:
      open: ./my_database.duckdb
    acceleration:
      enabled: true
      engine: postgres
      params:
     .# ..
```
1. Run spice and observe the error

>thread 'tokio-runtime-worker' panicked at crates/arrow_sql_gen/src/statement.rs:609:14:
not implemented: Data type mapping not implemented for Struct([Field { name: "v", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "i", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }])
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
