### ISSUE TITLE
Error when query has inner join across a federated dataset and an accelerated dataset of spice.ai

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1731]
**Describe the bug**
Error when query has inner join across a federated dataset and an accelerated dataset of spice.ai

**To Reproduce**
- run query `with a as (select hash from eth.blocks limit 10) select * from a  inner join  eth.recent_transactions xyz on a.hash = xyz.block_hash;`, see `.error`: `Status { code: Internal, message: "Failed to execute query: federation_optimizer_rule\ncaused by\nSchema error: Schema contains qualified field name xyz.hash and unqualified field name hash which would be ambiguous", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 19 Jun 2024 09:54:09 GMT", "content-length": "0"} }, source: None }`
- prefix the query with `explain` returns `No result`

**Expected behavior**
The query should return valid result

**Spicepod**
```
datasets:
  - from: spice.ai/eth.blocks
    name: eth.blocks
    params:
      endpoint: https://flight.spiceai.io
  - from: spice.ai/eth.recent_blocks
    name: eth.recent_blocks
    params:
      endpoint: https://flight.spiceai.io
    acceleration:
      enabled: true
  - from: spice.ai/eth.recent_transactions
    name: eth.recent_transactions
    params:
      endpoint: https://flight.spiceai.io
    acceleration:
      enabled: true
```

**Output of the `describe table`**
will be same when run with above spicepod

**Output of `explain query`**
`No result` which is wrong

**spice, spiced, OS info**
latest trunk -> c6aabb4c5267f75921b20b8361f72007e301ee14

**Have you tried this on the latest `trunk` branch?**
yes

**Screenshots**

**Additional context**
