### ISSUE TITLE
UUID types should show as proper UUID strings instead of base64 encoded values

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1759]
**Describe the bug**
When connecting to DataSources that natively support a UUID type (i.e. Postgres, Clickhouse) we convert it to a `DataType::FixedSizeBinary(16)`. Because there is no native UUID type in Arrow, we need to treat these as Strings. The built-in function [`uuid()`](https://github.com/apache/datafusion/blob/3051d1928eae8f684e1049a2cb00a8e721d70182/datafusion/functions/src/string/uuid.rs#L62) in DataFusion also returns a `DataType::Utf8`, so that would match as well.

This may automatically fix: #1736

**To Reproduce**
Connect to a Postgres table with a `uuid` column defined:

```sql
CREATE TABLE pg_table (
    int_column integer,
    uuid_column uuid
);

INSERT INTO pg_table (
    int_column,
    uuid_column
) VALUES (
    42,
    '123e4567-e89b-12d3-a456-426614174000'
);
```

**Expected behavior**
The UUID values show up in Spice as their proper String encoding

**Spicepod**
```yaml
datasets:
- from: postgres:uuid_table
  name: uuid_table
  params:
    pg_host: localhost
    pg_port: 5432
    pg_db: postgres
    pg_user: postgres
    pg_pass: password
```
