### ISSUE TITLE
DuckDB connector/accelerator: If open parameter is set, but DB is missing, spice runtime should automatically create a new database

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1799]
**Describe the bug**
If open parameter is set, but DB is missing, spice runtime should automatically create a new database.

**To Reproduce**
create a spicepod with a duckdb connector, and specify a database that doesn't exist:

```yaml
- from: duckdb:read_csv('/Users/abcd/Downloads/customers-100.csv')
    name: from_function
    params:
      open: /Users/abcd/code/github/spiceai/spiceai/a.db
```

**Expected behavior**
a.db should be created
