### ISSUE TITLE
Enhancement: GraphQL Data Connector Unnesting

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1802]
## Goal-State/What/Result

GraphQL data connector automatically unnests nested types to a specified nest depth with friendly columns names (the leaf name).

Parameter should be specified like:

```yaml
# Fetch stargazers of the spiceai repository every 1 hour, materialize locally
  - from: graphql:https://api.github.com/graphql
    name: stargazers
    params:
      json_path: data.repository.stargazers.edges
      unnest_depth: 1
```

An `unnest_depth` of undefined or 0, will result in the existing behavior (no unnesting).

Example:

Before column data: `{id: MDQ6VXNlcjcwNzIw, login: ashtom, name: Thomas Dohmke}`
After columns: `| MDQ6VXNlcjcwNzIw           | ashtom                        | Thomas Dohmke                             |`

Before column name: `unnest(stargazers.node).name`
After column name: `name`

## Why/Purpose

Significantly better developer UX. Without this feature, nested types are stored as a JSON blob in single column with a non-descriptive column name, such as `node`. The `unnest` function [can be used](https://docs.spiceai.org/data-connectors/graphql#piping-array-into-rows) however that is another step and still results in unfriendly colum names.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-
