### ISSUE TITLE
Enhancement: Databricks/UC/Spice.ai Catalog Providers

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1810]
## Goal-State/What/Result

Spice OSS can be used to connect to catalog providers to query all federated tables inside of a catalog. Initial catalog providers supported will be Databricks (via [Databricks-hosted Unity Catalog](https://www.databricks.com/product/unity-catalog)), [Unity Catalog OSS](https://github.com/unitycatalog/unitycatalog/tree/main) and Spice.ai.

## Why/Purpose

Configuring datasets individually becomes tedious beyond a handful. Integrating with catalog providers makes it easier to explore data and test it with Spice.

## By When

**Issue/Spec written and reviewed:** Tue, July 9
**Done-Done:** Wed, July 10

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

- A new `catalogs` top-level configuration will be added to the Spicepod.
- The `from` field specifies the catalog provider with an optional colon (`:`) and an identifier the catalog provider can use to determine which catalog is requested.
- The `name` field specifies the catalog registered in spice, and any schema/tables are registered automatically. (i.e. registering a catalog with `my_catalog` automatically registers any tables as `my_catalog.auto_schema.auto_table`). The `spice` name is reserved and will be rejected.
- A `params` field specifies any options needed for the catalog provider connection.
- A `dataset_params` field specifies any options needed for connecting to the tables in the catalog provider.
- An `include` field is an array of regex filters that are OR'ed together to filter down the list of tables
- Only federated queries will be supported, Accelerations need to be specified one dataset at a time in `datasets`.

### Unity Catalog Provider
The Unity Catalog Provider is invoked via `unity_catalog`. The colon `:` is required, and the identifier is the full URL to the [`getCatalog`](https://github.com/unitycatalog/unitycatalog/blob/main/api/Apis/CatalogsApi.md#getcatalog) Rest API call that returns the catalog details.

Currently the Unity Catalog OSS project does not require authentication. No other `params` are required.

The `dataset_params` corresponds to the same parameters required for the `delta_lake` data connector.

```yaml
catalogs:
  - from: unity_catalog:https://unity_catalog_host.com/api/2.1/unity-catalog/catalogs/catalog_name
    name: my_catalog
    dataset_params:
      # same params that delta_lake requires
```

### Databricks Catalog Provider
The Databricks Catalog Provider is also a flavor of Unity Catalog, but tailored for the Databricks environment. It includes the ability to specify the table format to use (either `spark_connect` or `delta_lake`), handles the authentication via Databricks token and will automatically construct the URL to the unity catalog API instead of requiring it to be specified in the `from` field.

```yaml
catalogs:
  - from: databricks:my_databricks_catalog
    name: my_catalog
    params:
      endpoint: dbc-a1b2345c-d6e7.cloud.databricks.com
      mode: spark_connect # delta_lake
      token: {databricks_token} # Can also be specified in secrets with `spice login databricks --token {databricks_token}`
    dataset_params:
      # same params that databricks requires for the specific mode, i.e. for spark_connect
      endpoint: dbc-a1b2345c-d6e7.cloud.databricks.com
      mode: spark_connect
      databricks_cluster_id: abc-123-akdjgha
      # for delta_lake
      endpoint: dbc-a1b2345c-d6e7.cloud.databricks.com
      mode: delta_lake
```

### Spice.ai Catalog Provider
The Spice.ai Catalog Provider provides access to all of the tables that an app has access to. This list is constructed via the `GET https://data.spiceai.io/v1/schemas` API using the API key of the logged in app.

It doesn't require any `params` or `dataset_params`.

```yaml
catalogs:
  - from: spice.ai
    name: spiceai
    include:
      - *.blocks
      - eth.*
```

## How/MAP

Implement [`CatalogProvider`](https://github.com/apache/datafusion/blob/f5e114e4f754c81d332f5105dd0242ab13f29a51/datafusion/core/src/catalog/mod.rs#L159) traits for each of the providers.

### Implementation (issues)

- 
-

### QA

- An integration test for the Spice.ai catalog provider
- Sample for Unity Catalog OSS
- Manual testing/bug bash for Databricks catalog provider
