### ISSUE TITLE
Warn if `endpoint` param for `s3` data connector ends in `/`

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1852]
**Describe the bug**
If the endpoint for the S3 Data Connector ends with a `/` then it will give an unhelpful error message. We should warn if it ends with a slash. This is relevant for custom S3 servers like Minio or Cloudflare R2.

```yaml
- from: s3://test-data-private/eth.recent_logs.parquet
  name: logs
  params:
    endpoint: https://{account_id}.r2.cloudflarestorage.com/
```

Fails with this error:
`WARN runtime: Cannot connect to S3. Object Store error: Object at location eth.recent_logs.parquet not found: Client error with status 404 Not Found: No Body`

Whereas, this works - and the only difference is the slash at the end of the endpoint

```yaml
- from: s3://test-data-private/eth.recent_logs.parquet
  name: logs
  params:
    endpoint: https://{account_id}.r2.cloudflarestorage.com
```
