### ISSUE TITLE
Postgres accelerator throws error `zero-length delimited identifier at or near """"` when ingesting data.

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1854]
**Describe the bug**
The contents of the file `https://public-data.spiceai.org/eth.recent_logs.parquet` causes an issue when accelerating into a PostgreSQL accelerator engine.

**To Reproduce**
Create a spicepod with this content (change the postgres parameters to match your local setup).

```yaml
version: v1beta1
kind: Spicepod
name: postgres_repro

datasets:
- from: https://public-data.spiceai.org/eth.recent_logs.parquet
  name: logs
  acceleration:
    enabled: true
    engine: postgres
    mode: file
    params:
      pg_host: localhost
      pg_port: 5432
      pg_user: postgres
      pg_pass: {password}
      pg_db: postgres
      pg_sslmode: disable
```

Observe this error:
2024-07-03T00:38:11.121565Z  INFO runtime: Dataset logs registered (https://public-data.spiceai.org/eth.recent_logs.parquet), acceleration (postgres:file), results cache enabled.
2024-07-03T00:38:11.122703Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset logs
2024-07-03T00:38:14.942605Z ERROR runtime::accelerated_table::refresh_task: Error adding data for logs: External error: Unable to insert Arrow batch to Postgres table: db error: ERROR: zero-length delimited identifier at or near """"

**Expected behavior**
The acceleration works.

**Comment by phillipleblanc** [comment]
I also got this error for this Spicepod, so it seems more widespread.

```yaml
datasets:
- from: https://public-data.spiceai.org/github_eth_addresses.csv
  name: addr
  acceleration:
    enabled: true
    engine: postgres
    mode: file
    params:
      pg_host: localhost
      pg_port: 5432
      pg_user: postgres
      pg_pass: {password}
      pg_db: postgres
      pg_sslmode: disable
```
