### ISSUE TITLE
SQLite accelerator fails with `Rusqlite("ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint")` without any primary keys specified

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1856]
**Describe the bug**
Running spice with this spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: sqlite_bug

datasets:
- from: https://public-data.spiceai.org/github_eth_addresses.csv
  name: addr
  acceleration:
    enabled: true
    engine: sqlite
```

Will result in this error:
`2024-07-03T00:53:26.174383Z ERROR runtime::accelerated_table::refresh_task: Error adding data for addr: External error: Unable to insert data into the Sqlite table: Rusqlite("ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint")`

There aren't any primary keys or unique constraints specified in the spicepod, so why it is trying to add them here?
