### ISSUE TITLE
Process ends with `os: process already finished` when trying to accelerate large dataset (sqlite, postgres)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1861]
**Describe the bug**

Unable to accelerate large MySQL dataset using sqlite file and postgres engines. Spiced process is terminated with the following error. Note: duckdb file acceleration works

>2024-07-03T01:12:05.889394Z INFO runtime::accelerated_table::refresh_task: Loading data for dataset test_table
os: process already finished

**To Reproduce**
1. Generate large MySQL dataset
```sql

CREATE TABLE IF NOT EXISTS test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED,
    salary DECIMAL(10, 2),
    is_active BIT DEFAULT b'1',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    profile_picture BLOB,
    preferences JSON,
    birth_date DATE,
    appointment_time TIME,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM('active', 'inactive', 'pending'),
    tags SET('tag1', 'tag2', 'tag3')
);

CREATE PROCEDURE PopulateTestTable()
BEGIN
    DECLARE i INT DEFAULT 1;

    -- Loop to insert 60 million rows in batches of 10000
    WHILE i <= 6000 DO
        INSERT INTO test_table (name, age, salary, is_active, profile_picture, preferences, birth_date, appointment_time, status, tags)
        SELECT
            CONCAT('Name_', FLOOR(RAND() * 1000000)),
            FLOOR(RAND() * 100),
            ROUND(RAND() * 100000, 2),
            b'1',
            NULL,
            JSON_OBJECT('theme', 'dark', 'notifications', true),
            DATE_SUB(CURDATE(), INTERVAL FLOOR(RAND() * 36525) DAY),
            SEC_TO_TIME(FLOOR(RAND() * 86400)),
            'active',
            'tag1,tag2'
        FROM
            (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
             SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t1,
            (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
             SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t2,
            (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
             SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t3,
            (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
             SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) t4;

        SET i = i + 1;
    END WHILE;
END

CALL PopulateTestTable();
```

3. Create test Spicepod using duckdb acceleration and confirm that acceleration is completed successfully
```yaml
 - from: mysql:testdb.test_table
   name: test_table
   params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_db: testdb
      mysql_user: root
      mysql_pass: <password>
      mysql_sslmode: disabled
   acceleration:
      enabled: true
      engine: duckdb
      mode: file
      refresh_mode: full
```

```
2024-07-03T01:08:51.035840Z INFO runtime::accelerated_table::refresh_task: Loaded 60,000,001 rows (12.59 GiB) for dataset test_table in 3m 47s 625ms.
```
5. Update acceleration to sqlite file and restart the app. Observe error below in ~3-5 mins after data loading has started

```yaml
 - from: mysql:testdb.test_table
   name: test_table
   params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_db: testdb
      mysql_user: root
      mysql_pass: <password>
      mysql_sslmode: disabled
   acceleration:
      enabled: true
      engine: sqlite
      mode: file
      refresh_mode: full
```
7. Update acceleration to postgres and restart the app. Observe error below in ~3-5 mins after data loading has started

```yaml
 - from: mysql:testdb.test_table
   name: test_table
   params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_db: testdb
      mysql_user: root
      mysql_pass: <password>
      mysql_sslmode: disabled
   acceleration:
      enabled: true
      engine: postgres
      refresh_mode: full
      params:
         ...
```

>2024-07-03T01:12:05.889394Z INFO runtime::accelerated_table::refresh_task: Loading data for dataset test_table
os: process already finished

**Expected behavior**
Data loading is completed successfully.
