### ISSUE TITLE
Query completes when federated but not accelerated

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1866]
**Describe the bug**
Using the Spice.ai data connector, I can run the following query and it won't complete if the data is locally accelerated, but it will if federated:

```SQL 
select * from eth_recent_traces trace JOIN eth_recent_transaction trans on trace.hash = trans.hash order by trans.block_number DESC;
```

**To Reproduce**

Spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: spiceai
datasets:
- from: spice.ai/eth.recent_traces
  name: eth_recent_traces
  acceleration:
    engine: duckdb
    enabled: true
    refresh_mode: full
- from: spice.ai/eth.recent_transactions
  name: eth_recent_transaction
  acceleration:
    engine: duckdb
    enabled: true
    refresh_mode: full
```

**Expected behavior**
I expect the query to complete with the same response as the federated query.
