### ISSUE TITLE
Arrays are not supported in SQLite

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1867]
**Describe the bug**
Using the Spice.ai data connector I can't accelerate a table into SQLite because arrays are not supported:

No arrays in SQLite:
2024-07-03T00:53:33.383925Z WARN runtime: Unable to attach data connector spiceai: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create table in Sqlite: ConnectionClosed
thread '' panicked at /Users/aurashb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.
thread '' panicked at /Users/aurashb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.
thread '' panicked at /Users/aurashb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.
thread '' panicked at /Users/aurashb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.

**To Reproduce**
Use the included spicepod and start spice.

**Expected behavior**
Data is accelerated into SQLite

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spiceai
datasets:
- from: spice.ai/eth.recent_transactions
  name: eth_recent_transactions
  acceleration:
    enabled: true
    engine: sqlite
    refresh_mode: full

```
