### ISSUE TITLE
Error in Append dataset

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1868]
**Describe the bug**
Append stream ended for dataset eth_recent_blocks - using sample from docs.spiceai.org I see the following error:

```shell
2024-07-03T00:18:28.377923Z  INFO runtime: Dataset eth_recent_blocks registered (spice.ai/eth.recent_blocks), acceleration (arrow, append), results cache enabled.
2024-07-03T00:18:28.798383Z  WARN runtime::accelerated_table::refresh_task: Append stream ended for dataset eth_recent_blocks
```

**To Reproduce**
Use the included spicepod and run spice.

**Expected behavior**
Append dataset loads with no warnings

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spiceai
datasets:
- from: spice.ai/eth.recent_blocks
  name: eth_recent_blocks
  acceleration:
    enabled: true
    refresh_mode: append

```

**Comment by Sevenannn** [comment]
## Question
- What is the use case of append acceleration without time_column specified? 
- What behavior is expected in Spice OSS when time_column is not set in spicepod? When no time_column is specified, **no new append data will be retrieved from server and added to spice runtime**. Should the stream be closed or remain open when all streams have been received?

## Observations
- Dataset can be queried in spice sql despite the warning log. No new data will be appended to the spice sql repl for the warning dataset.
```
sql> select number, timestamp from eth_recent_blocks limit 1;
+----------+------------+
| number   | timestamp  |
+----------+------------+
| 20264282 | 1720471907 |
+----------+------------+
```
- **Time_column is a required parameter** for an append dataset to get **new append data**, it is required for determining which data is new and to be appended by comparing with timestamps specified in spicepod configs (e.g. refresh_check_interval). Without time_column, we can only query the data, receiving a data stream, and stream ended when all streams are received.
- The above behaviors persist in prior Spice OSS versions, tested with v 0.13.3

## Solution
- Change the config in doc to below. Leave the warning log as it is, since the append stream does ended in reality
```
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    time_column: timestamp
    acceleration:
      enabled: true
      refresh_check_interval: 1s
      refresh_mode: append
```
