### ISSUE TITLE
Sqlite accelerator doesn't support binary format.

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1869]
- create a mysql data source with binary format
- use sqlite as accelerator
- start spiced
- see the error like
```
2024-07-03T00:37:32.666923Z ERROR runtime::accelerated_table::refresh_task: Error adding data for sample_data: External error: Unable to insert data into the Sqlite table: Rusqlite("unrecognized token: "'binary" in INSERT INTO "sample_data" ("col_tinyint", "col_smallint", "col_mediumint", "col_int", "col_bigint", "col_float", "col_double", "col_decimal", "col_date", "col_time", "col_datetime", "col_timestamp", "col_year", "col_char", "col_varchar", "col_tinytext", "col_text", "col_mediumtext", "col_longtext", "col_varbinary", "col_tinyblob", "col_blob", "col_mediumblob", "col_longblob", "col_bool", "col_enum", "column_json", "column_set", "col_binary") VALUES (0, 0, 0, 0, 0, 0, 0, 0.00, '1970-01-01', 40333123000000, '1970-01-01 00:00:00.000000', '2024-05-21 04:29:04.000000', 1970, 'char', 'varchar', 'tinytext', 'text', 'mediumtext', 'longtext', '123', 'tinyblob', 'blob', 'mediumblob', 'longblob', 0, 'value1', '{"a": 1}', '1,2,3', 'binary') at offset 729")
```

Spicepod
```
datasets:
  - from: mysql:mysql.new_table
    name: sample_data
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_sslmode: disabled
      mysql_user: root
      mysql_pass: my-secret
    acceleration:
      engine: sqlite
      enabled: true
```
