### ISSUE TITLE
Postgres accelerator does not support BINARY and TIME types from mysql datasource

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1871]
- create a mysql data source with binary format column and datetime format column
- use postgres as accelerator
- start spiced
- see the error like
```
2024-07-03T00:50:40.044091Z ERROR runtime::accelerated_table::refresh_task: Error adding data for sample_data: External error: Unable to insert Arrow batch to Postgres table: db error: ERROR: column "col_time" is of type time without time zone but expression is of type bigint
HINT: You will need to rewrite or cast the expression.

```
and
```
2024-07-03T00:55:36.609965Z ERROR runtime::accelerated_table::refresh_task: Error adding data for sample_data: External error: Unable to insert Arrow batch to Postgres table: db error: ERROR: invalid byte sequence for encoding "UTF8": 0x00
```

Spicepod
```
datasets:
  - from: mysql:mysql.new_table
    name: sample_data
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_sslmode: disabled
      mysql_user: root
      mysql_pass: my-secret
    acceleration:
      engine: postgres
      enabled: true
      params:
        pg_host: localhost
        pg_port: 25432
        pg_db: postgres
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
```

**Comment by Sevenannn** [comment]
Confirmed that mysql connector and postgres accelerator has no issue with `tiny_blob`, `medium_blob`, `long_blob`, `timestamp`, `datetime`, `datetime2` mysql types

**Comment by y-f-u** [comment]
Does binary works?

**Comment by Sevenannn** [comment]
For fix in [Support mysql BINARY, VARBINARY and Postgres Type::BYTEA #28](https://github.com/datafusion-contrib/datafusion-table-providers/pull/28)
spicepod config:
```
datasets:
  - from: mysql:mysql.test_table
    name: test_table
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_sslmode: disabled
      mysql_user: root
    acceleration:
      engine: postgres
      enabled: true
      params:
        pg_host: localhost
        pg_port: 5432
        pg_db: postgres
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
```

mysql create table statements:
```SQL
CREATE TABLE test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    data BINARY(16) -- Adjust size as needed
);

INSERT INTO test_table (name, data) VALUES
    ('Sample1', UNHEX('4D7953716C446174613031')), -- 'MySqlData01' in hex
    ('Sample2', UNHEX('4D7953716C446174613032')), -- 'MySqlData02' in hex
    ('Sample3', UNHEX('4D7953716C446174613033')); -- 'MySqlData03' in hex
```
MYSQL query result:
![image](https://github.com/user-attachments/assets/bdb697ec-ae8d-4c67-8979-a406d33705ac)


Verified the repl works for both char and binary datatype:
![image](https://github.com/user-attachments/assets/b82f93b1-aef4-4f1d-a2d7-629858f85645)
![image](https://github.com/user-attachments/assets/9f898695-87f2-4d4a-8962-d2aeb1eeeda4)

**Comment by Sevenannn** [comment]
For fix in [Postgres Type::TIME support](https://github.com/datafusion-contrib/datafusion-table-providers/pull/30)
MySQL create table statement
```
CREATE TABLE time_example (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_time TIME
);

INSERT INTO time_example (event_time) VALUES
    ('10:30:00'),  -- 10:30 AM
    ('14:45:30'),  -- 2:45:30 PM
    ('23:59:59'),  -- 11:59:59 PM
    ('00:00:00'),  -- Midnight
    ('07:15:45');  -- 7:15:45 AM
``` 

MySQL Query Result
![image](https://github.com/user-attachments/assets/9e4e58e0-f070-4ad2-99cd-25eeb5a926a8)

Spicepod Config:
```
  - from: mysql:mysql.time_example
    name: time_example
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_sslmode: disabled
      mysql_user: root
    acceleration:
      engine: postgres
      enabled: true
      params:
        pg_host: localhost
        pg_port: 5432
        pg_db: postgres
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
```
spice repl result:
![image](https://github.com/user-attachments/assets/0d5b0674-2c2d-4fda-bd25-b85329ceaed7)
