### ISSUE TITLE
Bug: Simba Spark ODBC driver memory leak

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#1888]
**Describe the bug**

Simba Spark ODBC drivers cause a memory leak when querying large datasets from databricks.

**To Reproduce**

1. Configure a large dataset (like `tpch.orders`) using a Databricks ODBC connection with the [Simba Spark ODBC driver](https://www.databricks.com/spark/odbc-drivers-download).
2. Run `spiced`.
3. Observe a memory leak once initial dataset acceleration load completes.

**Expected behavior**

Memory should clear during dataset load as resources are freed.

**Spicepod**
Add the relevant `spicepod.yml` section.

```
- from: odbc:samples.tpch.orders
  name: orders
  mode: read
  acceleration:
    engine: postgres
    params:
      pg_host: localhost
      pg_port: 5432
      pg_db: mydb
      pg_user: mydb_user
  params:
    odbc_connection_string: Driver=/opt/simba/spark/lib/64/libsparkodbc_sb64.so; ...
    max_num_rows_per_batch: 65536
```

**spice, spiced, OS info**
- spice version: `v0.15.1-alpha-rc.d534213b`
- spiced version: `v0.15.1-alpha-rc.d534213b`
- OS info: `Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux`

**Have you tried this on the latest `trunk` branch?**

Yes

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

Heaptrack output on a dataset load run points the blame to `Simba::Support::FormatStringV`.

![image (1)](https://github.com/spiceai/spiceai/assets/98815791/5ba4fe6c-6371-4e3a-8281-2f5908194ba6)

**Additional context**
