### ISSUE TITLE
Bug: Athena ODBC TPCH Q4 schema channel closed error

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#1920]
**Describe the bug**

When running TPCH Q4 in AWS Athena as an ODBC data connector, the query fails with a REPL and `spiced` error:

```
error: Execution error: Unable to query arrow: Internal communication channel error: Schema channel closed unexpectedly; code: QueryExecutionErro
```

**To Reproduce**

1. Configure AWS Athena as an ODBC connector with TPCH tables and data
2. Execute TPCH Q4

**Expected behavior**

The query should execute and return results, as it does in the Athena console.

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: odbc:tpch.customer
  name: customer
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.orders
  name: orders
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.nation
  name: nation
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.region
  name: region
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.supplier
  name: supplier
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.part
  name: part
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.partsupp
  name: partsupp
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED>;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
- from: odbc:tpch.lineitem
  name: lineitem
  mode: read
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=<SECRET REDACTED;PWD=<SECRET REDACTED>;SessionToken=<SECRET REDACTED>;
    max_num_rows_per_batch: 65536
```

**spice, spiced, OS info**
- spice version: `v0.15.2-alpha-rc.10ffdb8c`
- spiced version: `v0.15.2-alpha-rc.10ffdb8c`
- OS info: `Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux`

**Have you tried this on the latest `trunk` branch?**

Yes

**Context**

The query succeeds as expected when using acceleration (Arrow).
