### ISSUE TITLE
Bug: SQLite ODBC requires prepending column names with table name

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#1922]
**Describe the bug**

Take this example TPC-H query:

```sql
select
	s_acctbal,
	s_name,
	n_name,
	p_partkey,
	p_mfgr,
	s_address,
	s_phone,
	s_comment
from
	part,
	supplier,
	partsupp,
	nation,
	region
where
	p_partkey = ps_partkey
	and s_suppkey = ps_suppkey
	and p_size = 15
	and p_type like '%BRASS'
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = 'EUROPE'
	and ps_supplycost = (
		select
			min(ps_supplycost)
		from
			partsupp,
			supplier,
			nation,
			region
		where
			p_partkey = ps_partkey
			and s_suppkey = ps_suppkey
			and s_nationkey = n_nationkey
			and n_regionkey = r_regionkey
			and r_name = 'EUROPE'
	)
order by
	s_acctbal desc,
	n_name,
	s_name,
	p_partkey;
```

For nearly any regular database, this query will work as-is. For SQLite ODBC connections, REPL requires prepending every reference to a column with the associated table name and wrapping the column name in `"`, like `supplier."s_suppkey"`.

This is a very poor developer experience. Trying to run the query as-is returns a REPL error confirming the behavior:

```
Query Error No field named l_shipdate. Valid fields are lineitem."L_ORDERKEY", lineitem."L_PARTKEY", lineitem."L_SUPPKEY", lineitem."L_LINENUMBER", lineitem."L_QUANTITY", lineitem."L_EXTENDEDPRICE", lineitem."L_DISCOUNT", lineitem."L_TAX", lineitem."L_RETURNFLAG", lineitem."L_LINESTATUS", lineitem."L_SHIPDATE", lineitem."L_COMMITDATE", lineitem."L_RECEIPTDATE", lineitem."L_SHIPINSTRUCT", lineitem."L_SHIPMODE", lineitem."L_COMMENT".
```

**To Reproduce**

1. Configure an SQLite ODBC connector with TPCH tables and data
2. Attempt to execute any TPCH query
3. Observe behavior / error

**Expected behavior**

Queries should work without requiring specifying their originating column, and should not need to be wrapped with `"`.

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: odbc:customer
  name: customer
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:orders
  name: orders
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:region
  name: region
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:part
  name: part
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:partsupp
  name: partsupp
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:supplier
  name: supplier
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:nation
  name: nation
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
- from: odbc:lineitem
  name: lineitem
  mode: read
  acceleration:
    engine: arrow
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
    max_num_rows_per_batch: 65536
```

**spice, spiced, OS info**
- spice version: `v0.15.2-alpha-rc.10ffdb8c`
- spiced version: `v0.15.2-alpha-rc.10ffdb8c`
- OS info: `Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux`

**Have you tried this on the latest `trunk` branch?**

Yes
