### ISSUE TITLE
Spiced returns nothing when calling get_schema upon datasets

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1961]
**Describe the bug**
When 

**To Reproduce**
1. Configure the Spicepod as below
```yaml
  - from: spice.ai/eth.recent_blocks
    name: eth_recent_blocks
    time_column: timestamp
    acceleration:
      enabled: true
      refresh_mode: append
    params:
      endpoint: http://localhost:50053
```
2. Port forward spiced data sink to port 50053 on localhost
3. Run spice run, and observe the following error log
```
2024-07-12T05:41:22.111043Z  WARN runtime: Unable to get read provider for spiceai: Unable to retrieve schema
```
4.  Configure the [get_schema](https://github.com/spiceai/spiceai/blob/5155072f457dc85c3ca28abca539075d911e5ec5/crates/data_components/src/flight.rs#L165.) function here to print more information.  The code fail on [this line](https://github.com/spiceai/spiceai/blob/5155072f457dc85c3ca28abca539075d911e5ec5/crates/data_components/src/flight.rs#L188), which indicates that the stream is empty.

**Expected behavior**
Query against spiced shouldn't receive empty error batch on recent_blocks, recent_transactions, recent_traces dataset.

**spice, spiced, OS info**
- spice version: `spice version`
CLI version:     v0.15.2-alpha-rc.5155072f
Runtime version: v0.15.2-alpha-rc.5155072f
- spiced version: `spiced --version`
v0.15.2-alpha-rc.5155072f
- OS info: `uname -a`
Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Have you tried this on the latest `trunk` branch?**
Yes

**If possible, run `spiced` with DEBUG log level**

**Screenshots**

**Additional context**
