### ISSUE TITLE
Unity Catalog/Databricks catalog connector fails if any schema is missing tables

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1991]
**Describe the bug**
If any schema in a Databricks/Unity Catalog schema is missing tables, it will fail to deserialize the JSON response from the API with the following error:

`2024-07-16T08:18:26.454114Z ERROR runtime: Unable to register catalog db: Unable to load data connector for catalog db: Unable to get catalog provider for databricks: Unity Catalog API request failed: error decoding response body: missing field `tables` at line 1 column 2`

**To Reproduce**
Create a spicepod similar to this with access to a Databricks instance that has a catalog with an empty schema:

```yaml
catalogs:
  - from: databricks:main
    name: db
    include:
      - "tpch.*"
    params:
      endpoint: adb-4473752745667967.7.azuredatabricks.net
      mode: spark_connect
      databricks_cluster_id: 0423-065654-nu3nflpo
```

**Expected behavior**
The schema is skipped as it contains no tables
