### ISSUE TITLE
Enable annotating "categorical" on a field

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#202]
# Spec

## Pod Manifest Changes

```yaml
dataspaces:
  - from: rainbow
    name: attributes
    measurements:
    - name: distance
       selector: distance_miles
    categories:
      - name: color
        values:
         - red
         - orange
         - yellow
         - blue
         - green
         - indigo
         - violet
    tags:
    - is_new
    - is_double
```

## Internal data-handling changes

The datatype for the internal observation will change to:

```diff
type Observation struct {
	Time int64
+	Measurements map[string]float64
+      Categories map[string]string
	Tags []string
}
```

## Passed in Init() to DataProcessor

```golang
Init(params map[string]string, measurements map[string]string, categories map[string]string) error
```

Being a map of `name` to `selector`

**Comment by lukekim** [comment]
Can we make this simpler? Would this not work?

```yaml
dataspaces:
  - from: rainbow
    name: attributes
    fields:
      # Categorical
      - name: color
         type: string
         values:
         - red
         - orange
         - yellow
         - blue
         - green
         - indigo
         - violet
      - name: is_new
         type: tag
```
