### ISSUE TITLE
Bug: Secrets do not populate in `odbc_connection_string`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2075]
**Describe the bug**

Trying to use a secret in an ODBC connection string does not populate that string with the secret.

**To Reproduce**

1. Create an ODBC connection
2. Try to use a secret
3. Observe secret not being populated

**Expected behavior**

Secrets should be populated.

**Spicepod**

```yaml
version: v1beta1
kind: Spicepod
name: spice_app
secrets:
  - from: env
    name: env
datasets:
- from: odbc:customer
  name: customer
  params:
    odbc_connection_string: Driver={PostgreSQL Unicode};Server=localhost;Port=5432;Database=tpcd;Uid=${env:UID};Pwd=${env:PWD}
```

**Have you tried this on the latest `trunk` branch?**

Yes
