### ISSUE TITLE
BUG: wrong `mysql_user` gives an ambiguous error: `Driver error: Unknown authentication plugin...`

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#2076]
Creating a new mysql connector

e.g.

```
version: v1beta1
kind: Spicepod
name: mysql-demo
datasets:
  - from: mysql:mysql.huge_table
    name: huge_table
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_sslmode: disabled
      mysql_user: root1
      mysql_pass: root1
```

when `mysql_user` is wrong, spice gives an error
```
Unable to create MySQL connection pool: ConnectionPoolRunError: Driver error: `Unknown authentication plugin `sha256_password'.'
```
while if `mysql_pass` is wrong, the error makes more sense
```
Unable to create MySQL connection pool: ConnectionPoolRunError: Server error: `ERROR 28000 (1045): Access denied for user 'root'@'192.168.215.1' (using password: YES)'
```
