### ISSUE TITLE
Bug: ODBC Athena - TPCH Q20 fails for `mismtached input ')'`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2078]
**Describe the bug**

Running TPCH Q20 on ODBC Athena fails with the error:

```
Status { code: Internal, message: "External error: Execution error: Unable to query arrow: ODBC emitted an error calling 'SQLPrepare':\nState: HY000, Native error: 0, Message: [AmazonAthena][AthenaClientError]: ExceptionName: InvalidRequestException, ErrorType: 130, ExceptionMessage: line 1:700: mismatched input ')'. Expecting: 'PRECISION'", source: None }
```

**To Reproduce**

1. Configure ODBC Athena with a TPCH data source
2. Run TPCH Q20
3. Observe error

**Expected behavior**

The query should succeed.

**Spicepod**

```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: odbc:tpch.customer
  name: customer
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.orders
  name: orders
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.nation
  name: nation
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.region
  name: region
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.supplier
  name: supplier
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.part
  name: part
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.partsupp
  name: partsupp
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
- from: odbc:tpch.lineitem
  name: lineitem
  params:
    odbc_connection_string: Driver=/opt/athena/odbc/lib/libathena-odbc.so;Catalog=AwsDataCatalog;AwsRegion=us-east-2;Schema=tpch;Workgroup=primary;S3OutputLocation=s3://spiceai-s3-athena-results/;AuthenticationType=IAM Credentials;UID=...;PWD=...;SessionToken=...;
```

**Output of `explain query`**
```
VirtualExecutionPlan name=odbc compute_context=381a5ae6b6806918eec0cf3a2c5831c3c3858eeec399ec3a56385dbcf54acc44 sql=SELECT supplier.s_name, supplier.s_address FROM supplier JOIN nation ON true WHERE ((supplier.s_suppkey IN (SELECT partsupp.ps_suppkey FROM partsupp WHERE (partsupp.ps_partkey IN (SELECT part.p_partkey FROM part WHERE part.p_name LIKE 'forest%') AND (CAST(partsupp.ps_availqty AS DOUBLE) > (SELECT (0.5 * CAST(sum(lineitem.l_quantity) AS DOUBLE)) FROM lineitem WHERE ((((lineitem.l_partkey = partsupp.ps_partkey) AND (lineitem.l_suppkey = partsupp.ps_suppkey)) AND (lineitem.l_shipdate >= CAST('1994-01-01' AS DATE))) AND (lineitem.l_shipdate < (CAST('1994-01-01' AS DATE) + INTERVAL '0 YEARS 12 MONS 0 DAYS 0 HOURS 0 MINS 0.000000000 SECS'))))))) AND (supplier.s_nationkey = nation.n_nationkey)) AND (nation.n_name = 'CANADA')) ORDER BY supplier.s_name ASC NULLS LAST rewritten_sql=SELECT tpch.supplier.s_name, tpch.supplier.s_address FROM tpch.supplier JOIN tpch.nation ON true WHERE ((tpch.supplier.s_suppkey IN (SELECT tpch.partsupp.ps_suppkey FROM tpch.partsupp WHERE (tpch.partsupp.ps_partkey IN (SELECT tpch.part.p_partkey FROM tpch.part WHERE tpch.part.p_name LIKE 'forest%') AND (CAST(tpch.partsupp.ps_availqty AS DOUBLE) > (SELECT (0.5 * CAST(sum(tpch.lineitem.l_quantity) AS DOUBLE)) FROM tpch.lineitem WHERE ((((tpch.lineitem.l_partkey = tpch.partsupp.ps_partkey) AND (tpch.lineitem.l_suppkey = tpch.partsupp.ps_suppkey)) AND (tpch.lineitem.l_shipdate >= CAST('1994-01-01' AS DATE))) AND (tpch.lineitem.l_shipdate < (CAST('1994-01-01' AS DATE) + INTERVAL 12 MONTH))))))) AND (tpch.supplier.s_nationkey = tpch.nation.n_nationkey)) AND (tpch.nation.n_name = 'CANADA')) ORDER BY tpch.supplier.s_name ASC NULLS LAST
```

**Have you tried this on the latest `trunk` branch?**

Yes
