### ISSUE TITLE
Bug: ODBC SQLite - TPCH Q4 fails for `near 0 YEARS 3 MONS 0 DAYS ...`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2079]
**Describe the bug**

Running TPCH Q4 on ODBC SQLite fails with the error:

```
Status { code: Internal, message: "External error: Execution error: Unable to query arrow: ODBC emitted an error calling 'SQLPrepare':\nState: HY000, Native error: 1, Message: [SQLite]near \"'0 YEARS 3 MONS 0 DAYS 0 HOURS 0 MINS 0.000000000 SECS'\": syntax error (1)", source: None }
```

**To Reproduce**

1. Configure ODBC SQLite with a TPCH data source
2. Run TPCH Q4
3. Observe error

**Expected behavior**

The query should succeed

**Spicepod**

```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: odbc:customer
  name: customer
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:orders
  name: orders
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:region
  name: region
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:part
  name: part
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:partsupp
  name: partsupp
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:supplier
  name: supplier
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:nation
  name: nation
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
- from: odbc:lineitem
  name: lineitem
  params:
    odbc_connection_string: DRIVER={SQLite3};SERVER=localhost;DATABASE=tpch.sqlite;Trusted_connection=yes
```

**Output of `explain query`**
```
VirtualExecutionPlan name=odbc compute_context=33431d16e12d5c3589d2233a3c643bb973dc48ee30a1447a706f168d282ff614 sql=SELECT orders.o_orderpriority, count(1) AS order_count FROM orders WHERE (((orders.o_orderdate >= CAST('1993-07-01' AS DATE)) AND (orders.o_orderdate < (CAST('1993-07-01' AS DATE) + INTERVAL '0 YEARS 3 MONS 0 DAYS 0 HOURS 0 MINS 0.000000000 SECS'))) AND EXISTS (SELECT lineitem.l_orderkey, lineitem.l_partkey, lineitem.l_suppkey, lineitem.l_linenumber, lineitem.l_quantity, lineitem.l_extendedprice, lineitem.l_discount, lineitem.l_tax, lineitem.l_returnflag, lineitem.l_linestatus, lineitem.l_shipdate, lineitem.l_commitdate, lineitem.l_receiptdate, lineitem.l_shipinstruct, lineitem.l_shipmode, lineitem.l_comment FROM lineitem WHERE ((lineitem.l_orderkey = orders.o_orderkey) AND (lineitem.l_commitdate < lineitem.l_receiptdate)))) GROUP BY orders.o_orderpriority ORDER BY orders.o_orderpriority ASC NULLS LAST rewritten_sql=SELECT `orders`.`o_orderpriority`, count(1) AS `order_count` FROM `orders` WHERE (((`orders`.`o_orderdate` >= CAST('1993-07-01' AS DATE)) AND (`orders`.`o_orderdate` < (CAST('1993-07-01' AS DATE) + INTERVAL '0 YEARS 3 MONS 0 DAYS 0 HOURS 0 MINS 0.000000000 SECS'))) AND EXISTS (SELECT `lineitem`.`l_orderkey`, `lineitem`.`l_partkey`, `lineitem`.`l_suppkey`, `lineitem`.`l_linenumber`, `lineitem`.`l_quantity`, `lineitem`.`l_extendedprice`, `lineitem`.`l_discount`, `lineitem`.`l_tax`, `lineitem`.`l_returnflag`, `lineitem`.`l_linestatus`, `lineitem`.`l_shipdate`, `lineitem`.`l_commitdate`, `lineitem`.`l_receiptdate`, `lineitem`.`l_shipinstruct`, `lineitem`.`l_shipmode`, `lineitem`.`l_comment` FROM `lineitem` WHERE ((`lineitem`.`l_orderkey` = `orders`.`o_orderkey`) AND (`lineitem`.`l_commitdate` < `lineitem`.`l_receiptdate`)))) GROUP BY `orders`.`o_orderpriority` ORDER BY `orders`.`o_orderpriority` ASC NULLS LAST
```

**Have you tried this on the latest `trunk` branch?**

Yes
