### ISSUE TITLE
When updating dataset configuration in spicepod, it warns that it is already exists

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#2082]
**Describe the bug**

![CleanShot 2024-07-24 at 09 53 52@2x](https://github.com/user-attachments/assets/957f23da-3bdf-4aa6-a9c7-b8957c8e1334)

**To Reproduce**

1. setup spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: tpch-s3

datasets:
  - from: s3://spiceai-demo-datasets/tpch/nation/
    name: nation
    params:
      file_format: parquet
    acceleration:
      # params:
      #   test: test
      enabled: false
```

2. run spice, wait until dataset is loaded
3. uncomment acceleration params (doesn't change anything, but triggers watcher update)
4. Observe warning `Unable to attach data connector s3: Table already exists`

Note: dataset still seems to update correctly
