### ISSUE TITLE
BUG: tpch_q14 is broken for mysql federated query when dataset if defined with db prefix

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#2087]
**Describe the bug**
see title.

The error is
```
Status { code: Internal, message: "External error: Schema error: No field named \"sum(CASE WHEN tpch.part.p_type LIKE Utf8(\"\"PROMO%\"\") THEN tpch.lineitem.l_extendedprice * Int64(1) - tpch.lineitem.l_discount ELSE Int64(0) END)\". Valid fields are \"sum(CASE WHEN part.p_type LIKE Utf8(\"\"PROMO%\"\") THEN lineitem.l_extendedprice * Int64(1) - lineitem.l_discount ELSE Int64(0) END)\", \"sum(tpch.lineitem.l_extendedprice * Int64(1) - tpch.lineitem.l_discount)\".", source: None }
```

**To Reproduce**

- seed data using tpch-init tpch-gen mysql-init mysql-load

- run spiced with spicepod
```
  - from: mysql:tpch.part
    name: part
    params:
      mysql_sslmode: disabled
  - from: mysql:tpch.lineitem
    name: lineitem
    params:
      mysql_sslmode: disabled
```
- copy and run tpch_q14 query

**Expected behavior**
It should return result and not error out
