### ISSUE TITLE
Out of Memory when i accelerate parquet files having more than 1Billion records and connect it to apache superset using flightsql

### ISSUE THREAD

**Issue by michaelkovatt** [spiceai/spiceai#2096]
**Describe the bug**
I am trying to accelerate a 1 Billion Parquet file and have used helm deployment for deploying spice ai image to a Kubernetes pod.
The parquet file in a fileshare that is mounted on the POD and i have given the path in dataset configuration.

Tried below Datasets:
1. 1 Billion 
2.  200 Million

I have a 
In values.yaml the spec for the POD is below:

```
image:
  repository: spiceai/spiceai
  tag: latest
replicaCount: 1
resources:
  requests:
    memory: "80Gi"
    cpu: "20"
  limits:
    memory: "80Gi"
    cpu: "20"

```

In Superset i have created a dashboard after creating a connection using flightsql.

**To Reproduce**

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
For 1 Billion: Kubernetes POD is throwing OOM error.
For 200 Million: While accessing Superset dashboards, intermittently pod gets killed due to OOM

**Spicepod**
The dataset configuration is:
```
      - from: file://Test//Sample_1Biln.parquet
        name: Sample_1Biln_accelerated
        params:
          file_format: parquet
        acceleration:
          enabled: true
          refresh_check_interval: 1m
          refresh_mode: full
```

**Output of the `describe table`**
NA

**Output of `explain query`**
NA

**spice, spiced, OS info**
- spice image: `spiceai/spiceai:latest`
- spiced version: `v0.15.0-alpha`
- OS info: `Ubuntu`

**Have you tried this on the latest `trunk` branch?** No

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**
NA

**Additional context**
NA
