### ISSUE TITLE
Permission denied issue while using duckdb data connector with spice using HELM for Kubernetes deployment

### ISSUE THREAD

**Issue by michaelkovatt** [spiceai/spiceai#2097]
**Describe the bug**
Im getting a permission denied error. when i try to deploy spice ai using a dataset with duckdb data connector. Using Helm for kubernetes deployment

_WARN runtime: Unable to get read provider for duckdb: Unable to get schema: Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'parquet':
Failed to create directory "/.duckdb/": Permission denied_

**To Reproduce**

1. Prepare values.yaml
2. Create a dataconnector using duckdb function
3. Deploy using HELM commands
4. Kubetcl get logs <pod name> 

You will see the permission denied error

**Expected behavior**
Spice pod should run and duckdb data connector and extensions should be installed and dataset should be available.

**Spicepod Values.yaml**
```
image:
  repository: spiceai/spiceai
  tag: latest
replicaCount: 1
resources:
  requests:
    memory: "80Gi"
    cpu: "20"
  limits:
    memory: "80Gi"
    cpu: "20"

securityContext:
  runAsNonRoot: true
  runAsUser: 2000# UID
  runAsGroup: 2000# GID
  fsGroup: 2000
privileged: false


monitoring:
  podMonitor:
    enabled: false

spicepod:
  name: app
  version: v1beta1
  kind: Spicepod

  datasets:

      # Duckdb read_parquet function connector
      - from: duckdb:read_parquet('/TEST/Sheet1.parquet')
        name: parquet_notaccelerated
        params:
          open: local.duckdb
        acceleration:
          enabled: true
```

**Output of the `describe table`**
NA

**Output of `explain query`**
NA

**spice, spiced, Debian/Ubuntu**
- spiced version: `v0.15.0-alpha`

**Have you tried this on the latest `trunk` branch?**
NA

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`
Yes

**Screenshots**
![image](https://github.com/user-attachments/assets/08cf107c-7657-4ec5-b0d5-b3392ad3bbf9)

**Additional context**
NA
