### ISSUE TITLE
Secrets with special characters are not loading from file

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#2098]
**Describe the bug**
Secrets appear to be failing when loading from a file.  Secrets have "$#[$~?>" characters in it.  It seems one is not being escaped properly in file based .env secrets.  

**To Reproduce**

```yaml
version: v1beta1
kind: Spicepod
name: postgres-demo


secrets:
  - from: env
    name: env
    params:
      file_path: .env

datasets:
  - from: postgres:customer
    name: customer
    acceleration:
      enabled: true
    params:
      pg_host: <redacted host>
      pg_user: postgres
      pg_db: tpch
      pg_pass: ${env:PG_PASS}
      pg_sslmode: require
```

Use the following spicepod yaml as guidance, host name and secret were removed, but use the special characters in the .env file in the secrets.

**Expected behavior**
secrets load and can be used in the connection to the dataset.

**spice, spiced, OS info**
- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**
yes

**Additional context**
The postgres connector doesn't complain about the secrets, but instead says authentication failed.  The same secrets can be loaded in environment variables and the dataset loads successfully.
