### ISSUE TITLE
DuckDB acceleration query errors with `Failure while replaying WAL file`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2350]
```
sql> select * from region;
Query Error DuckDBError: IO Error: Failure while replaying WAL file "/home/william/.spice/data/partsupp.db.wal": Could not write file "/home/william/.spice/data/partsupp.db": Bad file descriptor
```

For a spicepod configured with TPCH SF0.5 like:

```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: duckdb:customer
  name: customer
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:region
  name: region
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:part
  name: part
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:partsupp
  name: partsupp
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:supplier
  name: supplier
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:orders
  name: orders
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:nation
  name: nation
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:lineitem
  name: lineitem
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
```
