### ISSUE TITLE
Bug: Attached accelerators fail when an accelerator fails initialization

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2368]
**Describe the bug**

Take the follow spicepod as an example:

```yaml
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: duckdb:customer
  name: customer
  acceleration:
    enabled: true
    engine: sqlite
    mode: file
    params:
        sqlite_file: ./customer.notsqlite
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:region
  name: region
  acceleration:
    enabled: true
    engine: sqlite
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
- from: duckdb:part
  name: part
  acceleration:
    enabled: true
    engine: sqlite
    mode: file
  params:
    duckdb_open: ./tpch.duckdb
```

An error is induced by using `.notsqlite`, which isn't a valid SQLite database extension.

In this example, the error from `.notsqlite` causes the database to fail initialization. However, the database isn't removed from the related SQLite accelerators during their table registration causing these connectors to fail as well.

**To Reproduce**

1. Configure a spicepod with DuckDB or SQLite accelerators
2. Configure one of the accelerators incorrectly to induce an error
3. See behavior

**Expected behavior**

The failing connector/accelerator should be excluded from attachment to the remaining connectors/accelerators.
