### ISSUE TITLE
DuckDB Accelerator fail to upsert change data in cdc samples

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2379]
**Describe the bug**
DuckDB Accelerator fail to upsert change data in cdc samples

**To Reproduce**
* Follow the spiceai/samples cdc-debezium, using the following spicepod.yaml
```
  - from: debezium:cdc.public.customer_addresses
    name: cdc
    params:
      debezium_transport: kafka
      debezium_message_format: json
      kafka_bootstrap_servers: localhost:19092
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      refresh_mode: changes
```
* Observe that query result from spice don't update when new data is inserted into postgres.

**Expected behavior**

**Spicepod**
Add the relevant `spicepod.yml` section.

**Output of the `describe table`**
Add any relevant `describe table` output here.

**Output of `explain query`**
Add any relevant `explain query` output here.

E.g. `explain select 1`
```
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

**spice, spiced, OS info**
- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

**Additional context**
