### ISSUE TITLE
DuckDB accelerator leaks memory

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2521]
**Describe the bug**

When loading TPCH SF100 to file-mode, even though DuckDB has record streaming, memory leaks consuming 100% of available system memory.

**To Reproduce**

1. Configure TPCH SF100 data source to DuckDB file-mode acceleration
2. Launch the Runtime
3. Observe high memory usage during accelerator load

**Expected behavior**

Memory usage should remain low and not leak, as the accelerator is accelerating to a file not to in-memory.

**Comment by peasee** [comment]
Follow the data setup from the DuckDB quickstart: https://github.com/spiceai/quickstarts/tree/trunk/duckdb

```
INSTALL tpch;
LOAD tpch;
CALL dbgen(sf = 100);
```

Configure a spicepod using DuckDB as a connector, accelerating to DuckDB:

```
version: v1beta1
kind: Spicepod
name: spice_app
datasets:
- from: duckdb:customer
  name: customer
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:region
  name: region
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:part
  name: part
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:partsupp
  name: partsupp
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:supplier
  name: supplier
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:orders
  name: orders
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:nation
  name: nation
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
- from: duckdb:lineitem
  name: lineitem
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
  params:
    duckdb_open: ./tpch100.duckdb
```

Using DuckDB as the connector could be exacerbating the problem, but regardless there still appears to be a leak.
