### ISSUE TITLE
Validation that gracefully handles accelerating multiple datasets into the same DuckDB file

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2531]
Currently this results in a hard crash:

```console
2024-09-05T03:51:48.557076Z  INFO runtime: Initialized results cache; max size: 128.00 MiB, item ttl: 1s
Assertion failed: (pointer.index < METADATA_BLOCK_COUNT), function Pin, file metadata_manager.cpp, line 54.
os: process already finished
```

Spicepod:
```yaml
version: v1beta1
kind: Spicepod
name: tpch-sf1.db
datasets:
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpch-sf1.db
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      params:
        duckdb_file: tpch-sf1-accelerated.db # Same as lineitem below
  - from: duckdb:lineitem
    name: lineitem
    params:
      duckdb_open: tpch-sf1.db
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
      params:
        duckdb_file: tpch-sf1-accelerated.db # Same as customer above
```
