### ISSUE TITLE
`acceleration.refresh_data_window` ignored

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#2577]
**Describe the bug**
Following the [Refresh Data Window Quickstart](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md), build from most recent trunk ignores `refresh_data_window` param

v0.17.3-beta works as expected

**To Reproduce**

[Refresh Data Window Quickstart](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md)

**Expected behavior**

Rows should be evicted when refresh_data_window is set

**Spicepod**

```yaml
version: v1beta1
kind: Spicepod
name: refresh-data-window-quickstart
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    time_column: tpep_pickup_datetime
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_data_window: 35040h # 4 years, this will evict 5 rows of data from the dataset
```

![CleanShot 2024-09-09 at 23 35 46@2x](https://github.com/user-attachments/assets/b3b0dc99-9bf6-45f8-b750-463f845bcae4)

![CleanShot 2024-09-09 at 23 35 54@2x](https://github.com/user-attachments/assets/1c56d865-5422-47c4-989d-424ba226236b)
