### ISSUE TITLE
The refresh will start again after the max retry attempt when run with invalid refresh sql

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2584]
**Describe the bug**
Configure an accelerated dataset with invalid Refresh SQL and max_retry_attempt, start the spice runtime. The refresh continues after maximum retry attempt.

**To Reproduce**
Use the following spicepod config, start the runtime
```
version: v1beta1
kind: Spicepod
name: refresh-data-window-quickstart
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    time_column: tpep_pickup_datetime
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_retry_enabled: false
      refresh_retry_max_attempts: 1
      refresh_check_interval: 5s
      # refresh_data_window: 35040h
      refresh_sql: "SELECT * FROM taxi_trips WHERE tpep_pickup_datetime > '2024-01-24T16:70:00'"
```

Observe the log, the refresh continues after retry_max_attempt
![image](https://github.com/user-attachments/assets/62238452-d239-4541-86da-2896d90695e8)

**Expected behavior**

**Spicepod**
Add the relevant `spicepod.yml` section.

**Output of the `describe table`**
Add any relevant `describe table` output here.

**Output of `explain query`**
Add any relevant `explain query` output here.

E.g. `explain select 1`
```
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

**spice, spiced, OS info**
- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

**Additional context**
