### ISSUE TITLE
Bug: physical plan is not yet implemented for GROUPING aggregate function

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2615]
## Describe the bug

When running some TPCDS queries on a connector with DuckDB in-memory and file-mode acceleration, the following REPL error occurs:

```
Query Error This feature is not implemented: physical plan is not yet implemented for GROUPING aggregate function
```

The error is observed on the following TPCDS queries:

- Q27
- Q36
- Q70
- Q86

As seen from TPCDS queries stored in the [datafusion-benchmarks](https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries)

## To Reproduce

1. Configure a connector with a TPCDS data source, using DuckDB in-memory or file-mode acceleration
2. Run specified TPCDS queries
3. See error

## Expected behavior

The queries should complete successfully.

## Testing Validation

In-memory DuckDB:
- [ ] Q27
- [ ] Q36
- [ ] Q70
- [ ] Q86

File-mode DuckDB:
- [ ] Q27
- [ ] Q36
- [ ] Q70
- [ ] Q86

## Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: tpcds1.duckdb
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
```
