### ISSUE TITLE
Forward-fill or zero-fill measurements

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#262]
Specified by the manifest using the `fill` option. Possible values are `previous` or `none`. E.g.

```yaml
dataspaces:
  - from: rainbow
    name: attributes
    fields:
      # Categorical
      - name: color
         type: string
         fill: previous
         values:
         - red
         - orange
         - yellow
         - blue
         - green
         - indigo
         - violet
      - name: is_new
         type: tag
```
