### ISSUE TITLE
Bug: Error during planning: Correlated column is not allowed in predicate

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2620]
## Describe the bug

When running TPCDS Q41 in with DuckDB in-memory acceleration, observe the following error:

```
Status { code: Internal, message: "Failed to execute query: check_analyzed_plan\ncaused by\nError during planning: Correlated column is not allowed in predicate: item.i_manufact = outer_ref(i1.i_manufact) AND (item.i_category = Utf8(\"Women\") AND (item.i_color = Utf8(\"cream\") OR item.i_color = Utf8(\"ghost\")) AND (item.i_units = Utf8(\"Ton\") OR item.i_units = Utf8(\"Gross\")) AND (item.i_size = Utf8(\"economy\") OR item.i_size = Utf8(\"small\")) OR item.i_category = Utf8(\"Women\") AND (item.i_color = Utf8(\"midnight\") OR item.i_color = Utf8(\"burlywood\")) AND (item.i_units = Utf8(\"Tsp\") OR item.i_units = Utf8(\"Bundle\")) AND (item.i_size = Utf8(\"medium\") OR item.i_size = Utf8(\"extra large\")) OR item.i_category = Utf8(\"Men\") AND (item.i_color = Utf8(\"lavender\") OR item.i_color = Utf8(\"azure\")) AND (item.i_units = Utf8(\"Each\") OR item.i_units = Utf8(\"Lb\")) AND (item.i_size = Utf8(\"large\") OR item.i_size = Utf8(\"N/A\")) OR item.i_category = Utf8(\"Men\") AND (item.i_color = Utf8(\"chocolate\") OR item.i_color = Utf8(\"steel\")) AND (item.i_units = Utf8(\"N/A\") OR item.i_units = Utf8(\"Dozen\")) AND (item.i_size = Utf8(\"economy\") OR item.i_size = Utf8(\"small\"))) OR item.i_manufact = outer_ref(i1.i_manufact) AND (item.i_category = Utf8(\"Women\") AND (item.i_color = Utf8(\"floral\") OR item.i_color = Utf8(\"royal\")) AND (item.i_units = Utf8(\"Unknown\") OR item.i_units = Utf8(\"Tbl\")) AND (item.i_size = Utf8(\"economy\") OR item.i_size = Utf8(\"small\")) OR item.i_category = Utf8(\"Women\") AND (item.i_color = Utf8(\"navy\") OR item.i_color = Utf8(\"forest\")) AND (item.i_units = Utf8(\"Bunch\") OR item.i_units = Utf8(\"Dram\")) AND (item.i_size = Utf8(\"medium\") OR item.i_size = Utf8(\"extra large\")) OR item.i_category = Utf8(\"Men\") AND (item.i_color = Utf8(\"cyan\") OR item.i_color = Utf8(\"indian\")) AND (item.i_units = Utf8(\"Carton\") OR item.i_units = Utf8(\"Cup\")) AND (item.i_size = Utf8(\"large\") OR item.i_size = Utf8(\"N/A\")) OR item.i_category = Utf8(\"Men\") AND (item.i_color = Utf8(\"coral\") OR item.i_color = Utf8(\"pale\")) AND (item.i_units = Utf8(\"Pallet\") OR item.i_units = Utf8(\"Gram\")) AND (item.i_size = Utf8(\"economy\") OR item.i_size = Utf8(\"small\")))", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 11 Sep 2024 06:35:33 GMT", "content-length": "0"} }, source: None }
```

TPCDS queries as seen in [datafusion-benchmarks](https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries)

## To Reproduce

1. Configure a connector with a TPCDS data source using DuckDB in-memory acceleration
2. Run TPCDS Q41
3. See error

## Expected behavior

The query should complete successfully.

## Testing Validation

- [ ] Q41 in-memory DuckDB

## Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: tpcds1.duckdb
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: memory
```
