### ISSUE TITLE
Bug: Binder Error: Referenced column "{}" not found in FROM clause!

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2651]
## Describe the bug

When running some TPCDS  queries in with DuckDB file-mode acceleration, observe the following errors:

Q42
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "sum(store_sales.ss_ext_sales_price)" not found in FROM clause!
```

Q54
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Values list "my_customers" does not have a column named "c_current_addr_sk"
```

Q62
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "substr(warehouse.w_warehouse_name,Int64(1),Int64(20))" not found in FROM clause!
```

Q66
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Could not ORDER BY column "x.w_warehouse_name": add the expression/function to every SELECT, or move the UNION into a FROM clause.
```

Q79
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "substr(ms.s_city,Int64(1),Int64(30))" not found in FROM clause!
```

Q85
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "substr(reason.r_reason_desc,Int64(1),Int64(20))" not found in FROM clause!
```

Q91
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "sum(catalog_returns.cr_net_loss)" not found in FROM clause!
```

Q99
```
Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "substr(warehouse.w_warehouse_name,Int64(1),Int64(20))" not found in FROM clause!
```

TPCDS queries as seen in [datafusion-benchmarks](https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries)

## To Reproduce

1. Configure a connector with a TPCDS data source using DuckDB in-memory acceleration
2. Run specified TPCDS queries
3. See error

## Expected behavior

The query should complete successfully.

## Testing Validation

- [ ] Q42 DuckDB file-mode accelerator
- [ ] Q54 DuckDB file-mode accelerator
- [ ] Q62 DuckDB file-mode accelerator
- [ ] Q66 DuckDB file-mode accelerator
- [ ] Q79 DuckDB file-mode accelerator
- [ ] Q85 DuckDB file-mode accelerator
- [ ] Q91 DuckDB file-mode accelerator
- [ ] Q99 DuckDB file-mode accelerator

## Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: tpcds1.duckdb
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds1.duckdb
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```
