### ISSUE TITLE
Postgres Accelerator TPCDS Error: "Schema mismatch: Query returned an unexpected data type for column sales_before: expected Decimal128(18, 2), received Decimal128(33, 2). 

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2696]
## Describe the bug

Running the following tpcds queries result in the error
67 78

## To Reproduce

TPCDS query reference: https://github.com/apache/datafusion-benchmarks/tree/main/tpcds/queries

spicepod.yaml
```
version: v1beta1
kind: Spicepod
name: tpcds-sf0.1.db
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds-sf0.1.db
    acceleration:
      enabled: true
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_user: postgres
        pg_pass: postgres
        pg_sslmode: disable
        pg_db: tpcds

```

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
