### ISSUE TITLE
Enhancement: Embedding and Vector Search Chunking

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#2719]
## Goal-State/What/Result

Compute, compare and store several embeddings per row, per column for a dataset by intelligently chunking the content. 

## Why/Purpose

Chunking long data to create several embedding is a common strategy to improve vector search quality. 

## By When

**Issue/Spec written and reviewed:** 25th September
**Done-Done:** v1.0-rc.2

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

### Spicepod UX
 - User's should be able to automatically enable chunking of the embedding column for their dataset.  
     - Fortunate rust library https://github.com/benbrandt/text-splitter  
 - Sane defaults for predominately text based chunking, but then can infer better defaults from the dataset.
     - E.g. if `params.file_format` provides a hint, there are better chunkers in [benbrandt/text-splitter](https://github.com/benbrandt/text-splitter)

Default options:
```yaml
datasets: 
  - from: github:github.com/spiceai/spiceai/files/trunk
    name: docs
    params:
      include: docs/**/*.md
    embeddings:
      - column: content
        use: embedding_model_name
        chunking:
          enabled: true
```

Overrides/schema
```yaml
embeddings:
  - column: string
    use: string
   chunking:
     enabled: bool # Optional, default false
     desired_chunk_size: usize # Optional, default to maximum (number of tokens)
     overlap_size: usize # Optional, default 0. (number of tokens)
     trim: bool, # optional, default true
```

### SQL UX
 - when `.datasets[*].embeddings[*].chunking.enabled == true`, the `{embedding_column}_embedding` will be of type `List(FixedSizeList(Float))` (currently, and if false, `FixedSizeList(Float)`). 
 - The `embedding_column` will not be chunked. Instead we need auxiliary data structure. Either 
    1. `{embedding_column}_offsets` of type `List(Uint32)` that show the sequential offsets of each `{embedding_column}_embedding` into `{embedding_column}`. Might be more SQL efficient for this to be `List(fixedList(uint32, 2))`. 
    2. An in-memory offset list (in `TableProvider`), that can be used in `VectorSearch` to show the specific subsection of `embedding_column` that relates to the vector, without exposing the offsets to users.

### Vector Search SQL 
- Ensure the underlying SQL query we would need to do based on above decisions is reasonable and performant.

```sql
SELECT
    {other fields + primary keys},
    content,
    content_offset,
    array_distance(embedding, :X) AS distance
FROM documents,
    UNNEST(content_embedding, content_offsets) AS t(embedding, content_offset)
WHERE {predicates}
ORDER BY distance ASC
LIMIT N;
```

### Vector Search HTTP API
 - For chunked embedding columns, `matches[*].value` returns the specific chunk from the specified column (from spicepod `datasets[*].embeddings[*].column`).To get the full document, a user should specify it in the HTTP request, under `additional_columns`.
