### ISSUE TITLE
Enhancement: Trigger refresh for file accelerated datasets based on file changes

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2762]
## Goal-State/What/Result

Allow refreshing the acceleration for a `file` data connector if the Spice runtime detects the file itself has changed via a file watcher.

```yaml
datasets:
  - from: file:/my_file.parquet
    name: my_file
    acceleration:
      enabled: true
      refresh_mode: full
      params:
        file_watcher: enabled
```

## Why/Purpose

Enables a better experience of using the file connector with acceleration

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-
