### ISSUE TITLE
SQLite Accelerator: "No message to commit transaction has been received."

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2841]
## Describe the bug

When accelerating a large CSV file to SQLite, I receive this error:

```bash
2024-09-26T07:43:40.461506Z  WARN runtime::accelerated_table::refresh_task: Failed to update dataset d1: External error: Unable to insert data into the Sqlite table: Other("No message to commit transaction has been received.")
2024-09-26T07:43:40.461760Z ERROR runtime::accelerated_table::refresh_task: Failed to refresh dataset d1: Dataset refresh failed with error: External error: Unable to insert data into the Sqlite table: Other("No message to commit transaction has been received.")
```

## To Reproduce

Load this Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: perf

runtime:
  task_history:
    enabled: false
  results_cache:
    enabled: true
    cache_max_size: 500MiB
    item_ttl: 15m

datasets:
  - from: s3://test-data-private/hvc_with_default.csv
    name: d1
    params:
      file_format: csv
      csv_has_header: true
      csv_delimiter: ","
      s3_endpoint: https://{r2-account-id}.r2.cloudflarestorage.com
      s3_key: ${env:S3_KEY}
      s3_secret: ${env:S3_SECRET}
      s3_auth: key
    acceleration:
      enabled: true
      engine: sqlite
      mode: file
      primary_key: accounts_sid
      indexes:
        accounts_sid: enabled
        parent_account_sid: enabled
      refresh_mode: full
      refresh_check_interval: 1h
```

## Expected behavior

The Spicepod loads properly.
