### ISSUE TITLE
Bug: GitHub/GraphQL connector does not respect LIMIT

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2850]
## Describe the bug

When running a query with a LIMIT in the GitHub/GraphQL connector, it does not respect it and instead returns all results:

```
sql> select count(*) from spiceai.issues
+----------+
| count(*) |
+----------+
| 931      |
+----------+

Time: 17.888681966 seconds. 1 rows.
sql> select count(*) from spiceai.issues limit 200
+----------+
| count(*) |
+----------+
| 931      |
+----------+

Time: 17.182362023 seconds. 1 rows.
```

## To Reproduce

1. Create a spicepod using the GitHub issues connector
2. Run a query with a limit
4. Observe unlimited rows

## Expected behavior

The rows should be limited as expected

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod-graphql-spicehq-decisions

datasets:
  - from: github:github.com/spiceai/spiceai/issues
    name: spiceai.issues
    params:
      github_token: ${secrets:GITHUB_TOKEN}
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
