### ISSUE TITLE
empty query result for first queries when acceleration enabled before booting

### ISSUE THREAD

**Issue by mjzk** [spiceai/spiceai#2915]
## Describe the bug

empty query result for first queries when the data is in loading and acceleration enabled before booting. For large dataset, this may happen. And then, in a long run, I get nothing for any query on the acceleration enabled dataset.

## To Reproduce

1.  start from spicepod.yaml

## Expected behavior

From the word "acceleration", if not data found in acceleration, do we query the `unaccelerated` data source?

### Spicepod

`spicepod.yml` :
```yaml
version: v1beta1
kind: Spicepod
name: spice_app
runtime:
  telemetry:
    enabled: false
datasets:
    # - ref: datasets/eth_recent_blocks
    - from: postgres:rides
      name: rides
      params:
        pg_host: 127.0.0.1
        pg_db: jin
        pg_port: 5432
        pg_user: jin
        pg_sslmode: disable
      acceleration:
        enabled: true
```

### Output of the `describe table`

seen in the #2914 

### Output of `explain query`
n/a

### spice, spiced, OS info

seen in the #2914 

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
n/a

## Screenshots

 
![image](https://github.com/user-attachments/assets/b5792e89-6592-4943-ac6f-2aae86bab6d7)

## Additional context
n/a
