### ISSUE TITLE
Bug with refresh_sql acceleration and chunked embedding column

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#2933]
```yaml
datasets:
  - from: github:github.com/apache/datafusion/pulls
    name: datafusion_pulls
    description: Datafusion docs at https://datafusion.apache.org
    metadata:
      instructions: |
        This dataset provides information on Apache Datafusion recent pull requests.
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
      refresh_check_interval: 15m
      refresh_jitter_enabled: true
      refresh_jitter_max: 1m
      refresh_sql: |
        SELECT * FROM datafusion_pulls LIMIT 300
    embeddings:
      - column: body
        use: openai_embeddings
        chunking:
          enabled: true
          target_chunk_size: 1024
```

**Comment by Jeadie** [comment]
Hypothesis that this is an issue with `refresh_sql` might be incorrect. Successful acceleration load on 
```yaml
datasets:
  - name: local
    from: file:nginx/docs/sample
    params:
      file_format: md
    acceleration:
      enabled: true
      refresh_sql: |
        SELECT * FROM local WHERE length(location) > 75
    embeddings:
      - column: content
        use: local_hf
        chunking:
          enabled: true
          target_chunk_size: 1024


embeddings:
 - name: local_hf
   from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
```
