### ISSUE TITLE
Bug: Reading multiple datasets from S3 causes error `Generic S3 error: error decoding response body`

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2936]
## Describe the bug

Configure multiple datasets to read from S3 (to reproduce I used 24 datasets), the error `Generic S3 error: error decoding response body` is shown.
![image](https://github.com/user-attachments/assets/e2b0aac1-c7a2-4ddf-9d24-1db33e05414c)

This is likely to be caused by IO tasks of reading from S3 & intensive CPU bound tasks from Datafusion running in the same runtime, causing IO tasks to be starved, as indicated by this post: https://github.com/apache/arrow-rs-object-store/issues/272

## To Reproduce

Run spice with the following spicepod configuration:
```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf1.db
datasets:
  - from: s3://spiceai-public-datasets/tpcds/call_center/
    name: call_center
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_returns/
    name: catalog_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_sales/
    name: catalog_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer_address/
    name: customer_address
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer_demographics/
    name: customer_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/date_dim/
    name: date_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/household_demographics/
    name: household_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/income_band/
    name: income_band
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/inventory/
    name: inventory
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/promotion/
    name: promotion
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/reason/
    name: reason
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/ship_mode/
    name: ship_mode
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store/
    name: store
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store_returns/
    name: store_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store_sales/
    name: store_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/time_dim/
    name: time_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/warehouse/
    name: warehouse
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_page/
    name: web_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_returns/
    name: web_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_sales/
    name: web_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_site/
    name: web_site
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```

## Expected behavior

Running multiple datasets using S3 connector shouldn't show such error

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
```
2024/10/02 14:48:00 INFO CLI version:     v0.19.0-beta-rc.c5e25c27
2024/10/02 14:48:00 INFO Runtime version: v0.19.0-beta-rc.dc2dbb5e
```
- spiced version: `spiced --version`
```
v0.19.0-beta-rc.dc2dbb5e
```
- OS info: `uname -a`
```
Darwin MacBookPro.home 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
