### ISSUE TITLE
Accelerating multiple datasets from S3 data connector with DuckDB file mode acceleration causes DuckDB error: ConnectionPoolError: timed out waiting for connection

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2937]
## Describe the bug

Accelerate multiple datasets from S3 data connector into file-based DuckDB (to reproduce I used 24 datasets), the following error is shown: 

![image](https://github.com/user-attachments/assets/726b1f48-c988-4d2b-b80d-dde212bfa61f)

This only happens when accelerating from S3 source. The issue is likely to be caused by similar reason to: https://github.com/spiceai/spiceai/issues/2936

## To Reproduce

Run spice with the following spicepod configuration:
```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf1.db
datasets:
  - from: s3://spiceai-public-datasets/tpcds/call_center/
    name: call_center
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_returns/
    name: catalog_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/catalog_sales/
    name: catalog_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer_address/
    name: customer_address
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/customer_demographics/
    name: customer_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/date_dim/
    name: date_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/household_demographics/
    name: household_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/income_band/
    name: income_band
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/inventory/
    name: inventory
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/promotion/
    name: promotion
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/reason/
    name: reason
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/ship_mode/
    name: ship_mode
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store/
    name: store
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store_returns/
    name: store_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/store_sales/
    name: store_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/time_dim/
    name: time_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/warehouse/
    name: warehouse
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_page/
    name: web_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_returns/
    name: web_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_sales/
    name: web_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://spiceai-public-datasets/tpcds/web_site/
    name: web_site
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```

## Expected behavior

Write to file-based DuckDB shouldn't fail to get connection

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
```
2024/10/02 14:48:00 INFO CLI version:     v0.19.0-beta-rc.c5e25c27
2024/10/02 14:48:00 INFO Runtime version: v0.19.0-beta-rc.dc2dbb5e
```
- spiced version: `spiced --version`
```
v0.19.0-beta-rc.dc2dbb5e
```
- OS info: `uname -a`
```
Darwin MacBookPro.home 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000 arm64
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
