### ISSUE TITLE
Bug: Postgres Accelerator connection_pool_size parameter cannot be configured

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2968]
## Describe the bug

The Spice Postgres accelerator documentation shows that Postgres `connection_pool_size` can be configured, however, it's missing in accelerator parameter spec and cannot be configured for Postgres acceleartor.
![Image](https://github.com/user-attachments/assets/d26885f4-4dd6-4e1c-ba7d-f48f2fe3b193)

## To Reproduce

Configure spicepod.yaml as below, and run spice
```
version: v1beta1
kind: Spicepod
name: gospice-sdk-sample

datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
    description: taxi trips in s3
    acceleration:
      engine: postgres
      params:
        pg_host: localhost
        pg_port: 5432
        pg_db: postgres
        pg_user: postgres
        pg_sslmode: disable
        connection_pool_size: 5
```

## Expected behavior

`connection_pool_size` parameter can be configured for Postgres accelerator

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
