### ISSUE TITLE
Enhancement: Enable vector search when base dataset has sufficient columns

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#2980]
## Goal-State/What/Result

Support `v1/search` and `DocumentSimilarity` tool for datasets that have embedding columns in their underlying connection. A local dataset does not have to recreate these embedding columns. Initially, only the `spice.ai` connector needs to be supported.

## Why/Purpose

Enable children spiced instances to read data/embeddings from a shared, parent spiced instance without needing to recompute vectors/chunking. 

## By When

**Issue/Spec written and reviewed:** 7th October
**Done-Done:** 10th October

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Context + Current State
Consider a common dataset with vector search support. 

```yaml
datasets:
  - from: file:/Users/jeadie/Github/my-repo/docs/
    name: my_app_docs
    acceleration:
      enabled: true
    embeddings:
      - column: content
        use: embedding_model
        column_pk:
          - location
        chunking:
          enabled: true
          target_chunk_size: 512
          overlap_size: 128

embeddings:
  - name: embedding_model
    from: openai
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
```

It requires the following state within `spiced`:
 - A column `content_embeddings` storing the embeddings for each row. In this example, since `datasets[0].embeddings[0].chunking.enabled: true`, `content_embeddings` will be of type `List(FixedSizedList(Float32/64))`. 
 - A column `content_offsets` storing the offsets into the `datasets[0].embeddings[0].column` (i.e. `content`) that the embedding was produced onto. Note: when `datasets[0].embeddings[0].chunking.enabled: false`, this column is not present.
 - The configuration of the embedding model to use. `datasets[0].embeddings[0].use` is a reference to the `embeddings[*].name` to use. 

### Inferring embedding columns in a dataset.
Ideas:
1. For child spice instance, user still provides `datasets[*].embeddings`. If `datasets[0].embeddings[0].column` already has associated columns (as above), don't create these columns, use existing. 
    - This solves issue about how to get the correct embedding model to embed search payloads. 
    - For read-only use cases, child spiced doesn't need to know understand chunking.
    - Possible to have discrepancy in 1. child's `datasets[0].embeddings[0]` configuration and 2. how the parent spiced is configure. (e.g. child has chunking params that is different to parents). 
2. For child spice instance, user does not provide `datasets[*].embeddings`. If any column(s) in dataset matches the pattern (e.g. `content`, `content_embeddings` & `content_offsets`) and has appropriate schema, don't create these columns, use existing. 
    - Does not handle where/how to get embedding model
    - No erroneous/duplicate `datasets[0].embeddings` metadata.
4. Pass down metadata in Flight Schema either at base `Schema` level, or the individual `Field` level. Use to decide if/how to use column for embeddings.     - Does not handle where/how to get embedding model
    - Will only ever work with spice connector (have no control over schema metadata for other connectors). 

Decision: Option 1.
 - When `datasets[0].embeddings[0].column` exists, user only needs to provide the following
```yaml
datasets:
- from: flightsql:my_app_docs
  name: child_ds
  params:
    flightsql_endpoint: http://127.0.0.1:50051
  embeddings:
      - column: content
        use: child_embed
        column_pk:
          - location

embeddings:
  - name: child_embed
    from: openai:embedding_model # Model name from parent spice instance.
    params:
      endpoint: http://127.0.0.1:8090 # Proxy embedding requests (e.g. for /v1/search) to parent.
```
A user could use a different embedding model locally (i.e. running the same model locally, or using a different query embedding model).

Any additional config for dataset will receive warning logs. 

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-
