### ISSUE TITLE
Enhancement: Full-text Search

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3015]
## Goal-State/What/Result
Provide full text search candiates, scored by BM25, through the `v1/search` HTTP endpoint. 

## Why/Purpose
Vector search produces search candidates from embedding-based semantic meaning, but can be less precise in circumstances where specific lexical matches can be important (e.g. Country, project name, etc (or partial match)). 

Providing candidates from a full text search experience can provide a more robust and effective out of the box experience for hybrid search.

Improvements in effectiveness can be measured in:
 - NDCG@10 on MTEB search benchmarks: https://github.com/spiceai/spiceai/actions/workflows/benchmarks_search.yml
 - Eval scores for search-based LLM testing, specifically Financebench: https://github.com/spiceai/spiceai/actions/workflows/financebench.yml

## By When

**Issue/Spec written and reviewed:** 14th May 2025
**Done-Done:** 9th June 2025

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## Spec
Note: See #3016 for details about how candidate generation will be 1. abstracted in code, 2. useable in the `v1/search` experience.

These specification detail how full text search will be integrated for a given dataset.

### Spicepod DX
Columns can be used in full text search by enabling `full_text_search` on a per-column basis.
```yaml
datasets:
 - name: dataset
   from: file:cleaned_sales_data.parquet
   columns:
     - name: product_line
       full_text_search:
         enabled: true
```

This can be used in combination with vector search, by specifying an embedding model for a column.
```yaml
datasets:
 - name: dataset
   from: file:cleaned_sales_data.parquet
   columns:
     - name: product_line
       full_text_search:
         enabled: true
       embeddings:
         - from: hf_minilm

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
```

Or across different columns.
```yaml
datasets:
 - name: dataset
   from: file:cleaned_sales_data.parquet
   columns:
     - name: customer_name
       full_text_search:
         enabled: true
     - name: product_line
       embeddings:
         - from: hf_minilm

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
```

Or with the same modality (i.e. 2 vector search columns)
```yaml
datasets:
 - name: dataset
   from: file:cleaned_sales_data.parquet
   columns:
     - name: customer_name
       embeddings:
         - from: openai
     - name: product_line
       embeddings:
         - from: hf_minilm

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2

  - name: oai
    from: openai
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
```

### Implementation
 - Needs to implement [`CandidateGeneration`](https://github.com/spiceai/spiceai/blob/003f854199e1f13e8c56ce6f6a7109b3e694385f/crates/search/src/generation.rs#L31) for Tantivy index. 
 - Create/store/write to FTS tantivy index for `TableProvider`, when specified in `dataset`. 
 - Need to construct `CandidateGeneration` in search pipeline when appropriate. 

### QA
 - Benchmarks for full-text search operations
 - Integration tests for full text search, full text search & vector search operations. 

#### QA - Benchmarking (MTEB) 
Below is the current score range for MTEB using a variety of embedding models. 

Using a hybrid approach, we expect a significant improvement, no less than the current min being greater than the current max by 5%. 

| config_name | min  | median | max |
| --- |--- |--- |--- |
| quora_openai-text-embedding-3-small_duckdb| 0.490 | 0.4977 | 0.504 |
| quora_minilm-l6-v2_arrow| 0.0844 | 0.0871 | 0.0983  |
| quora_openai-text-embedding-3- small_duckdb_chunking| 0.4722 | 0.4821 | 0.491 |
| quora_openai-text-embedding-3-small_arrow | 0.495 | 0.50 | 0.515 |
