### ISSUE TITLE
Enhancement: Results caching for search

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3018]
## Goal-State/What/Result

Search requests against tables with specific search terms and keywords are cached.

## Why/Purpose

To improve performance of search, and reduce cost by limiting search requests for the same content.

## By When

**Issue/Spec written and reviewed:** 20th May, 2025
**Done-Done:** 29th May, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

The runtime caching specifications are updated for search to use properties under `caching` to separate out different components that can be cached:

```yaml
runtime:
  caching:
    embeddings:
      enabled: true
      max_size: 128mb
      item_ttl: 5s
      eviction_policy: lru
      hashing_algorithm: siphash
    search_results:
      enabled: true
      max_size: 128mb
      item_ttl: 5s
      eviction_policy: lru
      hashing_algorithm: siphash
```

This allows for fine-grained control of each cached component. For example, a user can use a particular hashing algorithm on one component, and a different on another. A user can assign a larger cache size to one component, and a smaller size to another.

A property key of `max_size` instead of `cache_max_size` is used, removing `cache_` as the application of the property implies it is a cache as it is under a `caching` property.

#### Results Cache Deprecation

`runtime.results_cache` will be marked for deprecation after this enhancement. It will instead be replaced with `runtime.caching.sql_results`. Values in `runtime.results_cache` will still be accepted, but will log a warning for deprecation.

Values specified in `runtime.caching.sql_results` will override those from `runtime.results_cache`.

### Security Review

* Users should consider whether their embedded content is sensitive, and whether this data should be cached in memory. For these use-cases, users should disable the results cache.
* Malicious users could perform cache denial-of-service attacks, where they request excessive search terms or content which causes cache evictions of legitimate-use cache entries.
  * Users should ensure they use API keys to limit access to authorized users, preventing such requests from malicious users.

## How/Implementation Plan

* `CachedSearchResult` are created to wrap embedding and search results, respectively.
* The `Caching` struct is updated to add a `search` property, which is `Arc<dyn CacheProvider<CachedSearchResult>`
* Tool use and endpoints that invoke searches are updated to wrap around the cache providers for returning cached responses and storing responses in the cache. This ensures that cached items are also returned from tool use, and tool uses cache results that they invoke (like a tool use vector search).

## QA Plan

* [x] Add integration tests for expiring search entries
* [x] Add integration tests to compare the performance with/without caching
* [x] Add integration tests to compare the results with/without caching to ensure they match

## Release Notes

* **Search Result Caching:** Spice now supports runtime caching for search results, improving performance and reducing embedding and chat completion requests. Cached results are configurable independently for embeddings and search with options like maximum size, TTL, eviction policy and hashing algorithm.

Example `spicepod.yml` configuration:

```yaml
runtime:
  caching:
    search_results:
      enabled: true
      max_size: 128mb
      item_ttl: 5s
      eviction_policy: lru
      hashing_algorithm: siphash
```

For more information, refer to the [Caching documentation](#).
