### ISSUE TITLE
Nested Dremio object references are incorrectly quoted

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3066]
## Describe the bug

When using the Dremio Data Connector and using a deeply nested table identifier, Spice generates an incorrect SQL statement.

## To Reproduce

1. Create Dremio Connector
2. Run `SELECT` query from `spice sql`
3. Receive error: `Object 'some.real.table.path' not found. Please check that it exists in the selected context.`
4. Check Dremio and see that the following query was generated: `SELECT * FROM "some.real.table.path"`, which is invalid in Dremio

## Expected behavior

Expected a functional `SELECT` query. The Dremio query of `SELECT * FROM some.real.table.path` works correctly

### Spicepod

```yaml
datasets:
    - from: dremio:some.real.table.path
      name: dremio_dataset
      params:
        dremio_endpoint: grpc://<uri>:<port>
        dremio_password: <password>
        dremio_username: <user>
```

### Output of the `describe table`

N/A

### Output of `explain query`

N/A

### spice, spiced, OS info

- spice version: `v0.19.0-beta`
- spiced version: `v0.19.0-beta`
- OS info: OSX Sonoma 14.6

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ x ] No

**If possible, run `spiced` with DEBUG log level**

## Additional context

Reported by Killa on Discord
