### ISSUE TITLE
Datafusion logical plan contains unwanted columns in group-by clause

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#3085]
## Describe the bug

Datafusion physical plan execution returns duplicated groups/groups with missing data on aggregation.

This bug affects any non-federated connector/accelerator. Affected queries include TPCDS q33, q56, q60 and q66. 

Update 10/14: This is a Datafusion logical plan issue, the column is wrongly included in the group by clause in Query logical plan / physical plan.

## To Reproduce

1. Start Spice with S3 connectors connected to Spice TPCDS public datasets
2. Run the following two queries
Query 1
```SQL
 with ss as (
 select
          i_manufact_id,sum(ss_ext_sales_price) total_sales
 from
 	store_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     ss_item_sk              = i_item_sk
 and     ss_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     ss_addr_sk              = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
 limit 500
 ),
 cs as (
 select
          i_manufact_id,sum(cs_ext_sales_price) total_sales
 from
 	catalog_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id               in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     cs_item_sk              = i_item_sk
 and     cs_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     cs_bill_addr_sk         = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
limit 500
)
  select  i_manufact_id ,sum(total_sales) total_sales
 from  (select * from ss
        union all
        select * from cs
         order by i_manufact_id) tmp1
 group by i_manufact_id
 order by i_manufact_id;
```
Query 2
```
 with ss as (
 select
          i_manufact_id,sum(ss_ext_sales_price) total_sales
 from
 	store_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     ss_item_sk              = i_item_sk
 and     ss_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     ss_addr_sk              = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
 limit 500
 ),
 cs as (
 select
          i_manufact_id,sum(cs_ext_sales_price) total_sales
 from
 	catalog_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id               in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     cs_item_sk              = i_item_sk
 and     cs_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     cs_bill_addr_sk         = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
limit 500
)
  select  i_manufact_id ,count(*) total_sales
 from  (select * from ss
        union all
        select * from cs
         order by i_manufact_id) tmp1
 group by i_manufact_id
 order by i_manufact_id;
```
Query 3
```SQL
 with ss as (
 select
          i_manufact_id,sum(ss_ext_sales_price) total_sales
 from
 	store_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     ss_item_sk              = i_item_sk
 and     ss_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     ss_addr_sk              = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
 limit 10
 ),
 cs as (
 select
          i_manufact_id,sum(cs_ext_sales_price) total_sales
 from
 	catalog_sales,
 	date_dim,
         customer_address,
         item
 where
         i_manufact_id               in (select
  i_manufact_id
from
 item
where i_category in ('Books'))
 and     cs_item_sk              = i_item_sk
 and     cs_sold_date_sk         = d_date_sk
 and     d_year                  = 1999
 and     d_moy                   = 4
 and     cs_bill_addr_sk         = ca_address_sk
 and     ca_gmt_offset           = -5
 group by i_manufact_id
limit 10
)
  select  i_manufact_id ,sum(total_sales) total_sales
 from  (select * from ss
        union all
        select * from cs
         order by i_manufact_id) tmp1
 group by i_manufact_id
 order by i_manufact_id;
```
3. Observe the following scenarios
- Query 1 returns repeated group
- Query 2 returns wrong data for count(*) column, the values should be 2, while all count(*) results are 1
- Query 3 and Query 1 are identical in physical plan and logical plan, the only difference is the `LIMIT <n>` in CTE, however, query 3 gives non-duplicated, correct results

## Expected behavior

Queries with aggregation shouldn't return duplicated groups / miscalculated groups

### Spicepod

```
version: v1beta1
kind: Spicepod
name: gospice-sdk-sample

datasets:
  - from: s3://spiceai-public-datasets/tpcds/call_center/
    name: call_center
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/catalog_sales/
    name: catalog_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/catalog_returns/
    name: catalog_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/income_band/
    name: income_band
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/inventory/
    name: inventory
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/store_sales/
    name: store_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/store_returns/
    name: store_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/web_sales/
    name: web_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/web_returns/
    name: web_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/customer_address/
    name: customer_address
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/customer_demographics/
    name: customer_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/date_dim/
    name: date_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/household_demographics/
    name: household_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/promotion/
    name: promotion
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/reason/
    name: reason
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/ship_mode/
    name: ship_mode
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/store/
    name: store
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/time_dim/
    name: time_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/warehouse/
    name: warehouse
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/web_page/
    name: web_page
    params:
      file_format: parquet
    acceleration:
      enabled: true

  - from: s3://spiceai-public-datasets/tpcds/web_site/
    name: web_site
    params:
      file_format: parquet
    acceleration:
      enabled: true

```

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
