### ISSUE TITLE
Sharepoint connector: Invalid drive format

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3117]
## Describe the bug

I receive an invalid drive format error when I try to use the ID for a Sharepoint drive

## To Reproduce

1. Add Sharepoint dataset using the Drive ID

## Expected behavior

A functional dataset that I can query

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: sharepoint-qs
datasets:
  #- from: sharepoint:me/root
  - from: sharepoint:driveID:b!CbtYWrofwUGBJWnaJkNwoNrBLp_kC3RKklSXPwrdeP3yH8_qmH9xT5Y6RODPNfYI/root
  #- from: sharepoint:drive:Documents/root
    name: important_documents
    params:
      sharepoint_client_id: ${secrets:SPICE_SHAREPOINT_CLIENT_ID}
      sharepoint_tenant_id: ${secrets:SPICE_SHAREPOINT_TENANT_ID}
      sharepoint_auth_code: ${secrets:SPICE_SHAREPOINT_AUTH_CODE}
```

```shell
WARN runtime: Unable to get read provider for sharepoint: Invalid drive format: driveID:b!CbtYWrofwUGBJWnaJkNwoNrBLp_kC3RKklSXPwrdeP3yH8_qmH9xT5Y6RODPNfYI
```

### Output of the `describe table`

N/A

### Output of `explain query`

N/A

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
