### ISSUE TITLE
Enhancement: Multi-agent Models

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#3127]
## Goal-State/What/Result
Let users defined models that work as a multi-agent interaction.

## Why/Purpose

It's cool, and can be useful for customers.

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec
- Only considering the synchronous use case (i.e. no asynchonous multi-agent workloads).

New model type `multi_agent`:
```yaml

tools:
  - name: laptop_sql
    from: builtin:sql_tool
    description: |
      This tool allow's you to query against {{ company.name }} SQL data. 
      
models:
  - name: model_a
    from: openai:gpt-4o

  - name: model_b
    from: huggingface:huggingface.co/meta-llama/Llama-3.2-1B-Instruct
    params:
      system_prompt: |
        You are operating in {{ country or 'Australia' }}.
  - name: model_c
    from: anthropic

  - name: llm_party
    from: multi_agent:model_a,model_b,model_c
    params:
      - max_calls: 100
      - start_with: model_b
```

New tools for swarm
- `Handoff` tool to other model
- `Update context` tool.

Things `multi_agent` model type should do:
- Handle tool use recursion (like tool-using model wrapper)
- Handle handoff between models, update of `context_variables`.
- Inject `multi_agent` tool(s) into each model.
- Track the assistant's name, and inject into chat completion message history.
- Apply Jinja2 templating to model `params.system_prompt`, tools `description`, from request level `context_variables`.
  - Can initialise to [`.metadata`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-metadata) from request payload.
