### ISSUE TITLE
(Bug) DuckDB fail to accelerate arrow boolean list type

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#3138]
## Describe the bug

When DuckDB accelerate arrow boolean list type, the following error is shown
```
2024-10-18T01:28:21.007905Z  WARN runtime: Unable to attach data connector postgres: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create duckdb table: Invalid Input Error: Nested list is not supported yet.
```

## To Reproduce

Create dataset in Postgres using following command
```SQL
CREATE TABLE test_postgresql_table (
  bool_array_column BOOLEAN[]
);

INSERT INTO test_postgresql_table (
  bool_array_column
) VALUES (
  ARRAY[true, false]
), (
  NULL
);
```

Accelerate the data with DuckDB accelerator using the following configuration, and observe the error
```YAML
version: v1beta1
kind: Spicepod
name: gospice-sdk-sample

datasets:
  - from: postgres:test_postgresql_table
    name: test_postgresql_table
    params:
      pg_host: localhost
      pg_db: postgres
      pg_port: 5432
      pg_user: postgres
      pg_sslmode: disable
```

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
