### ISSUE TITLE
Enhancement: Enable DuckDB extensions to be loaded for DuckDB datasets.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#3164]
\*REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound\*

## Goal-State/What/Result
Configurable DuckDB extensions, per spicepod dataset.

## Why/Purpose
Explicit user interest in the ability for users to be able to use DuckDB functions that come from extensions. 

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

Example Spicepod
```yaml
datasets:
  - name: dck
    from: duckdb:st_read('/Users/jeadie/Downloads/xlxxlxlxlx.xlsx')
    params:
      duckdb_extensions: spatial
  
```

## How/Plan

_A clear and concise plan of how this should be implemented._

### Implementation (Sub Issues)

- Sub Issue 1
- Sub Issue 2

### QA

- Sub Issue 1
- Sub Issue 2
