### ISSUE TITLE
(Bug) Clickhouse schema inference failed when clickhouse tables are not in the `default` clickhouse database

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#3184]
When connecting to Clickhouse table not in clickhouse `default` database, the schema inference and all subsequent query fail.

To reproduce, create a Clickhouse table that's not in the default database, and connect to it with Spice.

For example, spicepod.yaml:
```yaml
  - from: clickhouse:my_first_table
    name: my_first_table
    params:
      clickhouse_host: localhost
      clickhouse_tcp_port: 9001
      clickhouse_db: testdb
      clickhouse_user: test_user
      clickhouse_pass: password
      clickhouse_secure: false
```

In Spice REPL, do `describe my_first_table`, observe `No results`
In Spice REPL, query `my_first_table`, observe the query failure.
