### ISSUE TITLE
Enhancement: Unified refresh

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3185]
## Goal-State/What/Result

Refreshes for two or more data connectors with the same acceleration parameters should be unified (only one refresh happens).

## Why/Purpose

To enable the in-memory primary, file backup acceleration fallback pattern.

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

E.g.

```yaml
datasets:
  - from: s3://blah/blah
     name: primary
     refresh_interval: 5m
  - from: s3://blah/blah
     name: secondary
     refresh_interval: 5m
```

Should only cause one refresh every 5 mins, but both datasets to have the refreshed data.

## How/Plan

_A clear and concise plan of how this should be implemented._

### Implementation (Sub Issues)

- Sub Issue 1
- Sub Issue 2

### QA

- Sub Issue 1
- Sub Issue 2
