### ISSUE TITLE
Editing spicepod.yaml and changing parent dataset for a localpod dataset breaks the link between them

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3288]
## Describe the bug

When a localpod dataset is synchronized with a parent dataset, changing the parameters of the parent dataset acceleration in such a way to cause it to unload/reload the acceleration (i.e. by changing the `refresh_sql`) will cause the localpod dataset to continue to refer to the old parent acceleration instead of pointing to the new one.

## To Reproduce

Create this spicepod:

```yaml
version: v1beta1
kind: Spicepod
name: quickstart
datasets:
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  description: taxi trips in s3
  params:
    file_format: parquet
  acceleration:
    enabled: true
    refresh_check_interval: 10s
    refresh_mode: full
- from: localpod:taxi_trips
  name: local_trips
  acceleration:
    enabled: true
```

Start Spice, wait for the dataset to load. Once loaded, add a refresh_sql to filter the original dataset:

```diff
  acceleration:
    enabled: true
    refresh_check_interval: 10s
    refresh_mode: full
+    refresh_sql: SELECT * FROM taxi_trips LIMIT 100
```

## Expected behavior

The localpod dataset reflects the change
