### ISSUE TITLE
Enhancement: Semantic model (Columnar granularity)

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3317]
\*REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound\*

## Goal-State/What/Result

Users should be able to express column level semantics about their datasets, and these details should be available to LLMs.

## Why/Purpose

Improve the ability for models to understand the semantic of the datasets they can access.

## By When

**Issue/Spec written and reviewed:** 1st November.
**Done-Done:** 5th November.

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Spicepod DX changes
Datasets in spicepod have optional column-level (each column also optional) configuration
```yaml
datasets:
- from: file:cleaned_sales_data.parquet
  name: sales
  columns:
    - name: order_number
    - name: msrp
      description: |
        Manufacturer's Suggested Retail Price (MSRP) is the price that a product's manufacturer recommends it be sold for at the point of sale.
    - name: address_line1
      embeddings: # `column` and `column_pk` are no longer allowed.
        - use: hf_minilm
          chunking:
            enabled: true
            target_chunk_size: 256
            overlap_size: 32
          row_id: order_number
```

Additional details:
 - `datasets[].indexes` are unaffected.
 - `datasets[].embeddings` are unaffected. When provided, will be aggregrated with `datasets[].columns[].embeddings`. With v1 launch of spicepod specification, `datasets[].embeddings` to be removed.
 - Add a pseudo-PK (name TBD, e.g. `row_id`) for `datasets[].columns[].embeddings` to denote what is unique. 

### Tool changes
- Tool `table_schema` will have additional, optional parameter `output: enum` (default `full`, others `minimal`). When set, the tool will return additional metadata from `datasets[].columns[]` in the output.
- Tool `table_schema` will mention that semantic information is available via `output` parameter.

### Embedding
 - `datasets[].columns[].embeddings.use` -> `datasets[].columns[].embeddings.from`
 

## How/Plan

_A clear and concise plan of how this should be implemented._

### Implementation (Sub Issues)

- Sub Issue 1
- Sub Issue 2

### QA

- Sub Issue 1
- Sub Issue 2

**Comment by Jeadie** [comment]
From discussion with @phillipleblanc  and @lukekim 
 - `datasets[].indexes` are unaffected.
 - `datasets[].embeddings` are unaffected. When provided, will be aggregrated with `datasets[].columns[].embeddings`. With v1 launch of spicepod specification, `datasets[].embeddings` to be removed.
 - Keep `datasets[].acceleration.primary_key`
 - Keep `datasets[].time_column`
 - Add a pseudo-PK (name TBD) for `datasets[].columns[].embeddings`

**Comment by Jeadie** [comment]
- Acceleration schema
- Data source schema
- Spicepod refresh_sql (we need to support reduced column set)
  - `SELECT projection FROM {dataset.name} WHERE ... `. Only column projection in `SELECT ... `.
- Embeddings columns (this needs to be merged with Spicepod dataset)
- LLM semantic layer (this needs to be merged with the two above)

```yaml
  columns:
    - name: order_number (String)
       type: Arrow_type/string
       verify: enum 
       description: string
       embedding: struct
```
This enhancement will only include: name, description, embedding. 
 
- **Principle**: Spiced verifies the federated source to the extent that its defined in spicepod, otherwise it tries to work.
