### ISSUE TITLE
Spice can't find MySQL tables with a non-lowercase name

### ISSUE THREAD

**Issue by a-ellison** [spiceai/spiceai#3364]
## Describe the bug

The Spice runtime is not able to find MySQL tables that contain uppercase characters in their name.

## To Reproduce

Download [bug.tar.gz](https://github.com/user-attachments/files/17624340/bug.tar.gz) for an example project that sets up database and the runtime as described below. (See README for how to run.)

Create example PostgreSQL database tables, one where the name has an uppercase character and one with a lowercase name:

```sql
CREATE TABLE Uppercase (
  a integer
);

INSERT INTO Uppercase (a) VALUES
(42);

CREATE TABLE lowercase (
  a integer
);

INSERT INTO lowercase (a) VALUES
(42);
```
 
Tell spice about the tables in `spicepod.yaml`:
```yaml
version: v1beta1
kind: Spicepod
name: demo

datasets:
  - from: mysql:Uppercase
    name: uppercase
    params:
      mysql_host: 127.0.0.1
      mysql_tcp_port: 3307
      mysql_db: demo
      mysql_user: demo
      mysql_pass: demo
      mysql_sslmode: disabled
  - from: mysql:lowercase
    name: lowercase
    params:
      mysql_host: 127.0.0.1
      mysql_tcp_port: 3307
      mysql_db: demo
      mysql_user: demo
      mysql_pass: demo
      mysql_sslmode: disabled
```

If you start the Spice runtime with this configuration, it won't be able to find the "Uppercase" table but it will find the "lowercase" table:
```
2024-11-04T21:48:53.516874Z  WARN runtime: Unable to load mysql dataset uppercase. Table uppercase not found. Verify the source table name in the Spicepod configuration.
2024-11-04T21:48:53.518053Z  INFO runtime: Dataset lowercase registered (mysql:lowercase), acceleration (arrow, 10s refresh), results cache enabled.
```

## Expected behavior

The Spice runtime should either be able to find the table, or the documentation should say that table names must be lowercase and/or the Spice runtime should complain when a non-lowercase table name is provided.

## Additional context

The above example does work with PostgreSQL. ([Here](https://github.com/user-attachments/files/17624323/postgres.tar.gz) is the above example in postgres.) As far as I understand the problem is that MySQL table names are case-sensitive (at least on Linux).
