### ISSUE TITLE
No trace or error in case of incorrect model type is specified (qwen2 model)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3407]
## Describe the bug

There is no trace error or other indication when incorrect model_type  is specified for `Qwen1.5-0.5B` model (`llama` instead of `qwen2`)

![Image](https://github.com/user-attachments/assets/43514b7c-fe59-49fc-a963-e02be8324edd)

![Image](https://github.com/user-attachments/assets/8a8f7ff9-f087-4c01-bf3b-9e315afc4fed)

## To Reproduce

```yaml
models:
  - name: local_model
    # from: huggingface:huggingface.co/meta-llama/Llama-3.2-1B-Instruct
    from: huggingface:huggingface.co/Qwen/Qwen1.5-0.5B
    params:
      model_type: llama # must be qwen2
      hf_token: ${ secrets:SPICE_HF_TOKEN }
```
