### ISSUE TITLE
NSQL error `Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: The")` (Llama-3.2-1B-Instruct)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3408]
## Describe the bug

NSQL api returns  error code 400 when 

>curl -i -XPOST "http://localhost:8090/v1/nsql" \
  -H "Content-Type: application/json" \
  -d '{
    "query": "How many records in taxi trips dataset?",
    "model": "local_model"
  }'
HTTP/1.1 400 Bad Request
content-type: text/plain; charset=utf-8
content-length: 89
date: Thu, 07 Nov 2024 04:49:52 GMT

Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: The")%

## To Reproduce

```yaml
version: v1beta1
kind: Spicepod
name: text-to-sql

datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM taxi_trips limit 100;
    
models:
  - name: local_model
    from: huggingface:huggingface.co/meta-llama/Llama-3.2-1B-Instruct
    params:
      model_type: llama
      hf_token: ${ secrets:SPICE_HF_TOKEN }
```

### Spicepod log

```console
2024-11-07T04:49:52.465175Z TRACE runtime::http::v1::nsql: Running query:
The sample output shows number of records in taxi trips dataset.
2024-11-07T04:49:52.465248Z DEBUG runtime::datafusion::query::tracker: Query finished with error: Failed to execute query: SQL error: ParserError("Expected: an SQL statement, found: The"); code: SyntaxError
```
