### ISSUE TITLE
NSQL error `Row format support not yet implemented for: [SortField`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3411]
## Describe the bug

>curl -i -XPOST "http://localhost:8090/v1/nsql" \
  -H "Content-Type: application/json" \
  -d '{
    "query": "How many records in taxi trips daatset?",
    "model": "local_model"
  }'
HTTP/1.1 500 Internal Server Error
content-type: text/plain; charset=utf-8
content-length: 323
date: Thu, 07 Nov 2024 06:57:10 GMT

Failed to execute query: Arrow error: Not yet implemented: Row format support not yet implemented for: [SortField { options: SortOptions { descending: false, nulls_first: true }, data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 1536) }]%

## To Reproduce

Stable repro

```yaml
version: v1beta1
kind: Spicepod
name: text-to-sql

datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM taxi_trips limit 100;
    
  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM item limit 100;
    embeddings:
      - column: i_item_desc
        column_pk:
          - i_item_sk
        use: openai_embeddings
    

models:
  - name: local_model
    from: huggingface:huggingface.co/meta-llama/Llama-3.2-1B-Instruct
    # from: huggingface:huggingface.co/Qwen/Qwen1.5-0.5B
    params:
      model_type: llama
      hf_token: ${ secrets:SPICE_HF_TOKEN }


embeddings:
  - from: openai
    name: openai_embeddings
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
    metadata: {}
```
