### ISSUE TITLE
TPCDS Queries fail for Arrow acceleration from DuckDB source

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3421]
## Describe the bug

TPC-DS queries fail when running with Arrow acceleration from a DuckDB source.

```rust
Status { code: Internal, message: "Schema mismatch: Query returned an unexpected data type for column total shipping cost: expected Decimal128(17, 2), received Decimal128(27, 2). Is the column data type supported by the data accelerator (https://docs.spiceai.org/reference/datatypes)?", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 08 Nov 2024 18:51:31 GMT", "content-length": "0"} }, source: None }
```

## To Reproduce

1. Run `test/scripts/setup-tpc-spicepod.bash tpcds 1`
2. Run any of the following queries
3. Receive error message

### Queries

16. 
```sql
select
   count(distinct cs_order_number) as "order count"
  ,sum(cs_ext_ship_cost) as "total shipping cost"
  ,sum(cs_net_profit) as "total net profit"
from
   catalog_sales cs1
  ,date_dim
  ,customer_address
  ,call_center
where
    d_date between '1999-5-01' and
           (cast('1999-5-01' as date) + INTERVAL '60 days')
and cs1.cs_ship_date_sk = d_date_sk
and cs1.cs_ship_addr_sk = ca_address_sk
and ca_state = 'ID'
and cs1.cs_call_center_sk = cc_call_center_sk
and cc_county in ('Williamson County','Williamson County','Williamson County','Williamson County',
                  'Williamson County'
)
and exists (select *
            from catalog_sales cs2
            where cs1.cs_order_number = cs2.cs_order_number
              and cs1.cs_warehouse_sk <> cs2.cs_warehouse_sk)
and not exists(select *
               from catalog_returns cr1
               where cs1.cs_order_number = cr1.cr_order_number)
order by count(distinct cs_order_number)
 LIMIT 100;
```

94. 
```sql
select
   count(distinct ws_order_number) as "order count"
  ,sum(ws_ext_ship_cost) as "total shipping cost"
  ,sum(ws_net_profit) as "total net profit"
from
   web_sales ws1
  ,date_dim
  ,customer_address
  ,web_site
where
    d_date between '1999-4-01' and
           (cast('1999-4-01' as date) + INTERVAL '60 days')
and ws1.ws_ship_date_sk = d_date_sk
and ws1.ws_ship_addr_sk = ca_address_sk
and ca_state = 'WI'
and ws1.ws_web_site_sk = web_site_sk
and web_company_name = 'pri'
and exists (select *
            from web_sales ws2
            where ws1.ws_order_number = ws2.ws_order_number
              and ws1.ws_warehouse_sk <> ws2.ws_warehouse_sk)
and not exists(select *
               from web_returns wr1
               where ws1.ws_order_number = wr1.wr_order_number)
order by count(distinct ws_order_number)
 LIMIT 100;
```

95. 
```sql
with ws_wh as
(select ws1.ws_order_number,ws1.ws_warehouse_sk wh1,ws2.ws_warehouse_sk wh2
 from web_sales ws1,web_sales ws2
 where ws1.ws_order_number = ws2.ws_order_number
   and ws1.ws_warehouse_sk <> ws2.ws_warehouse_sk)
 select
   count(distinct ws_order_number) as "order count"
  ,sum(ws_ext_ship_cost) as "total shipping cost"
  ,sum(ws_net_profit) as "total net profit"
from
   web_sales ws1
  ,date_dim
  ,customer_address
  ,web_site
where
    d_date between '2002-5-01' and
           (cast('2002-5-01' as date) + INTERVAL '60 days')
and ws1.ws_ship_date_sk = d_date_sk
and ws1.ws_ship_addr_sk = ca_address_sk
and ca_state = 'MA'
and ws1.ws_web_site_sk = web_site_sk
and web_company_name = 'pri'
and ws1.ws_order_number in (select ws_order_number
                            from ws_wh)
and ws1.ws_order_number in (select wr_order_number
                            from web_returns,ws_wh
                            where wr_order_number = ws_wh.ws_order_number)
order by count(distinct ws_order_number)
 LIMIT 100;
```

## Expected behavior

Expected queries to run successfully

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf1.db
datasets:
  - from: duckdb:call_center
    name: call_center
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:catalog_page
    name: catalog_page
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:catalog_returns
    name: catalog_returns
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:catalog_sales
    name: catalog_sales
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:customer
    name: customer
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:customer_address
    name: customer_address
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:customer_demographics
    name: customer_demographics
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:date_dim
    name: date_dim
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:household_demographics
    name: household_demographics
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:income_band
    name: income_band
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:inventory
    name: inventory
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:item
    name: item
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:promotion
    name: promotion
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:reason
    name: reason
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:ship_mode
    name: ship_mode
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:store
    name: store
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:store_returns
    name: store_returns
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:store_sales
    name: store_sales
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:time_dim
    name: time_dim
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:warehouse
    name: warehouse
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:web_page
    name: web_page
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:web_returns
    name: web_returns
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:web_sales
    name: web_sales
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
  - from: duckdb:web_site
    name: web_site
    params:
      duckdb_open: tpcds-sf1.db
    acceleration:
      enabled: true
```

### Output of `describe table`

```bash
sql> DESCRIBE web_sales;
+--------------------------+------------------+-------------+
| column_name              | data_type        | is_nullable |
+--------------------------+------------------+-------------+
| ws_sold_date_sk          | Int32            | YES         |
| ws_sold_time_sk          | Int32            | YES         |
| ws_ship_date_sk          | Int32            | YES         |
| ws_item_sk               | Int32            | YES         |
| ws_bill_customer_sk      | Int32            | YES         |
| ws_bill_cdemo_sk         | Int32            | YES         |
| ws_bill_hdemo_sk         | Int32            | YES         |
| ws_bill_addr_sk          | Int32            | YES         |
| ws_ship_customer_sk      | Int32            | YES         |
| ws_ship_cdemo_sk         | Int32            | YES         |
| ws_ship_hdemo_sk         | Int32            | YES         |
| ws_ship_addr_sk          | Int32            | YES         |
| ws_web_page_sk           | Int32            | YES         |
| ws_web_site_sk           | Int32            | YES         |
| ws_ship_mode_sk          | Int32            | YES         |
| ws_warehouse_sk          | Int32            | YES         |
| ws_promo_sk              | Int32            | YES         |
| ws_order_number          | Int32            | YES         |
| ws_quantity              | Int32            | YES         |
| ws_wholesale_cost        | Decimal128(7, 2) | YES         |
| ws_list_price            | Decimal128(7, 2) | YES         |
| ws_sales_price           | Decimal128(7, 2) | YES         |
| ws_ext_discount_amt      | Decimal128(7, 2) | YES         |
| ws_ext_sales_price       | Decimal128(7, 2) | YES         |
| ws_ext_wholesale_cost    | Decimal128(7, 2) | YES         |
| ws_ext_list_price        | Decimal128(7, 2) | YES         |
| ws_ext_tax               | Decimal128(7, 2) | YES         |
| ws_coupon_amt            | Decimal128(7, 2) | YES         |
| ws_ext_ship_cost         | Decimal128(7, 2) | YES         |
| ws_net_paid              | Decimal128(7, 2) | YES         |
| ws_net_paid_inc_tax      | Decimal128(7, 2) | YES         |
| ws_net_paid_inc_ship     | Decimal128(7, 2) | YES         |
| ws_net_paid_inc_ship_tax | Decimal128(7, 2) | YES         |
| ws_net_profit            | Decimal128(7, 2) | YES         |
+--------------------------+------------------+-------------+
````

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
|               |     ProjectionExec: expr=[count(alias1)@0 as order count, sum(alias2)@1 as total shipping cost, sum(alias3)@2 as total net profit, count(alias1)@0 as count(DISTINCT ws1.ws_order_number)]                                                   |
|               |       AggregateExec: mode=Final, gby=[], aggr=[count(alias1), sum(alias2), sum(alias3)]
```

### spice, spiced, OS info

- spice version: `CLI version:     v1.0.0-rc.1-build.c618ee3b
Runtime version: v1.0.0-rc.1-build.c618ee3b+models`
- spiced version: `v1.0.0-rc.1-build.c618ee3b+models`
- OS info: `Darwin jotunheim.local 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 arm64`

**Have you tried this on the latest `trunk` branch?**

- [X] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
