### ISSUE TITLE
Local HF model does not use tools

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3426]
## Describe the bug

When I use local huggingface models (`Llama-3.2-1B-Instruct`, `Phi-3-mini-4k-instruct`) and do chat completion request tools are not called and model does not have information about datasets.

>"tool_calls":[],

>{"id":"1","choices":[{"index":0,"message":{"content":"I'm sorry, but I can't provide the exact number of records in the taxi_trips dataset or any specific datasets without having direct access to your data. To obtain this information, you would typically run a SQL query such as `SELECT COUNT(*) FROM taxi_trips;` if you're working with an SQL database. However, you didn't specify if you have a dataset or database to query, or if you're seeking a general approach.","refusal":null,"tool_calls":[],"role":"assistant","function_call":null},"finish_reason":"stop","logprobs":null}],"created":1731185734,"model":"microsoft/Phi-3-mini-4k-instruct","service_tier":null,"system_fingerprint":"local","object":"chat.completion","usage":{"prompt_tokens":48,"completion_tokens":99,"total_tokens":147}}

## To Reproduce

```yaml
version: v1beta1
kind: Spicepod
name: text-to-sql

datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM taxi_trips limit 100;

models:
  - name: local_model
    from: huggingface:huggingface.co/microsoft/Phi-3-mini-4k-instruct
    # from: huggingface:huggingface.co/meta-llama/Llama-3.2-1B-Instruct
    params:
      #spice_tools: list_datasets, sql, table_schema
      spice_tools: auto
      model_type: phi3
      # model_type: llama
      hf_token: ${ secrets:SPICE_HF_TOKEN }

```

```console
curl -i http://localhost:8090/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "local_model",
    "messages": [
      {
        "role": "system",
        "content": "You are an assistant that responds to queries by providing only the requested data values without extra explanation"
      },
      {
        "role": "user",
        "content": "Provide the total number of records in the taxi_trips dataset. If known, return a single numeric value"
      }
    ]
  }'
HTTP/1.1 200 OK
content-type: application/json
content-length: 792
date: Sat, 09 Nov 2024 20:41:48 GMT

{"id":"1","choices":[{"index":0,"message":{"content":"I'm sorry, but I can't provide the exact number of records in the taxi_trips dataset or any specific datasets without having direct access to your data. To obtain this information, you would typically run a SQL query such as `SELECT COUNT(*) FROM taxi_trips;` if you're working with an SQL database. However, you didn't specify if you have a dataset or database to query, or if you're seeking a general approach.","refusal":null,"tool_calls":[],"role":"assistant","function_call":null},"finish_reason":"stop","logprobs":null}],"created":1731184894,"model":"microsoft/Phi-3-mini-4k-instruct","service_tier":null,"system_fingerprint":"local","object":"chat.completion","usage":{"prompt_tokens":48,"completion_tokens":99,"total_tokens":147}}
```

NSQL works

```console
curl -i -XPOST "http://localhost:8090/v1/nsql" \
  -H "Content-Type: application/json" \
  -d '{
    "query": "{\"sql\": \"how many records in taxi_trips dataset\"}",
    "model": "local_model",
    "sample_data_enabled": false
  }'
HTTP/1.1 200 OK
content-type: text/plain; charset=utf-8
x-cache: Miss from spiceai
content-length: 22
date: Sat, 09 Nov 2024 20:52:54 GMT

[{"record_count":100}]% 
```
