### ISSUE TITLE
spice chat `failed to send chat request ` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3427]
## Describe the bug

There is the following error when using `spice chat`

>⚡ spice chat
Using model: local_model
chat> how many records in taxi trips
⣾ 2024/11/09 14:45:57 ERROR failed to send chat request to spiced error="error sending request: Post \"http://localhost:8090/v1/chat/completions\": EOF"
⣟ at> 

## To Reproduce

```yaml
version: v1beta1
kind: Spicepod
name: text-to-sql

datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM taxi_trips limit 100;
   
models:
  - name: local_model
    from: huggingface:huggingface.co/microsoft/Phi-3-mini-4k-instruct
    params:
      #spice_tools: list_datasets, sql, table_schema
      spice_tools: auto
      model_type: phi3
      hf_token: ${ secrets:SPICE_HF_TOKEN }

```

Spice runtime error

```console
2024-11-09T22:45:43.455009Z  INFO runtime: Model [local_model] deployed, ready for inferencing
thread 'tokio-runtime-worker' panicked at crates/llms/src/chat/mod.rs:184:21:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
