### ISSUE TITLE
Bug: Github Data Connector does NOT error or warn when source repo does not exist

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3444]
## Describe the bug

If  repo source  is misspelled/incorrect (does not exist) the data connector reports NO errors and just loads 0 rows:

```console
2024-11-11T17:56:15.654886Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset datafusion_pulls
2024-11-11T17:56:16.057679Z  INFO runtime::accelerated_table::refresh_task: Loaded 0 rows for dataset datafusion_pulls in 402ms.
```

## To Reproduce

```
- from: github:github.com/apache/datafusion12123sdfsdf/pulls
    name: datafusion_pulls
    params:
      github_token: ${secrets:GITHUB_TOKEN}
      github_query_mode: search
    time_column: updated_at
    acceleration:
      enabled: true
      refresh_sql: |
        SELECT * FROM datafusion_pulls where updated_at > '2024-10-01'
```
