### ISSUE TITLE
Tags should be mapped in manifest and not use magic "_tags" syntax

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#346]
Tags should be mapped into the observation space from the source data via the dataspace manifest. There is only one "tags" set for the pod/row. I.e. each dataspace does not have its own set of tags.

```yaml
dataspaces:
  - from: coinbase
    name: btcusd
    measurements:
      - name: close
    tags:
      selectors:
      - color
      - size
      values:
      - purple
      - green
      - small
      - medium
```

E.g. from CSV

```csv
time,cost,color,size
12345678,5.00,purple,small
```

Would create the observation:

```json
{
   "time": 12345678,
   "measurements": {
      "cost": 5.00
   },
   "tags": [
      "purple", "small"
    ]
}
```
