### ISSUE TITLE
Move ready_state to be on the dataset level, not the acceleration level

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3523]
The `ready_state` parameter is really a dataset level parameter, not an acceleration level parameter.

```yaml
datasets:
  - from: mysql:foo
    name: foo
    ready_state: on_load # on_registration
    acceleration:
      enabled: true
      ready_state: on_load # deprecated, but still accepted
```
