### ISSUE TITLE
PostgreSQL Data Connector should allow specifying a single connection string

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3540]
It would be a better UX if the PostgreSQL data connector allowed specifying the connection string as a single parameter:

```yaml
  - from: postgres:foo
    name: foo
    params:
      pg_connection_string: postgresql://user:${secrets:PG_PASS}@pghost.com:5432/postgres
```
