### ISSUE TITLE
Keyring Secret Store doesn't work

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3542]
## Describe the bug

Attempting to use the Keyring secret store on macOS doesn't work. It fails with:

```bash
2024-11-18T23:25:27.071968Z ERROR runtime::secrets: Key spice_pg_pass not found in secret: keyring
2024-11-18T23:25:27.105846Z  WARN runtime::init::dataset: Error initializing dataset test. Cannot connect to postgres. Authentication failed. Ensure that the username and password are correctly configured in the spicepod.
```

## To Reproduce

Create a spicepod with the keyring secret store enabled:

```yaml
secrets:
  - from: keyring
    name: keyring
```

And use a secret from the keyring in a dataset:

```yaml
- from: postgres:cleaned_sales_data
  name: test
  params:
    pg_host: localhost
    pg_port: 5432
    pg_user: postgres
    pg_db: postgres
    pg_sslmode: disable
    pg_pass: ${keyring:spice_pg_pass}
```

## Expected behavior

The secret is loaded from the keyring store

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
