### ISSUE TITLE
`spice add` overwrites `views`

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3547]
## Describe the bug

When using `spice add` to add dataset to a `spicepod`, any `views` configured in the `spicepod` will disappear.

## To Reproduce

1. Start with the following `spicepod`:
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
    - from: spark:nyc_taxi_trip2
      name: nyc_taxi_trip2
      params:
        spark_remote: sc://localhost:15002
    - from: spark:nyc_taxi_trip
      name: nyc_taxi_trip
      params:
        spark_remote: sc://localhost:15002

views:
  - name: taxi
    sql: |
      SELECT * FROM nyc_taxi_trip UNION ALL SELECT * FROM nyc_taxi_trip2 
```

2. Run `spice add spiceai/quickstart` in a terminal
3. See that new `spicepod.yaml` is:
```yaml
version: v1beta1
kind: Spicepod
name: spark_demo
datasets:
    - from: spark:nyc_taxi_trip2
      name: nyc_taxi_trip2
      params:
        spark_remote: sc://localhost:15002
    - from: spark:nyc_taxi_trip
      name: nyc_taxi_trip
      params:
        spark_remote: sc://localhost:15002
dependencies:
    - spiceai/quickstart
```

## Expected behavior

`views` would be preserved after adding the new dependency.

### Spicepod

See above

### Output of `describe table`

N/A

### Output of `explain query`

N/A

### spice, spiced, OS info

- spice version: `CLI version:     v1.0.0-rc.1-build.1c30db0e`
- spiced version: `v1.0.0-rc.1-build.2893507a+models`
- OS info: `Darwin Mac.lan 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:00:32 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6030 arm64`

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

## Screenshots

https://github.com/user-attachments/assets/3481d8a6-340b-45fe-b64f-9a35c12957e3
