### ISSUE TITLE
S3 returns a generic timeout error when invalid region or auth mode is specified

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3553]
## Describe the bug

When specifying an invalid region, or using `s3_auth: iam_role` when no IAM role is loaded, returns a generic timeout error instead of a more specific error:

```
2024-11-18T23:39:25.337062Z  WARN runtime::init::dataset: Cannot connect to s3. Object Store error: Generic S3 error: Error performing list request: Error after 10 retries in 3.836037419s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://s3.not-a-real-region.amazonaws.com/spiceai-demo-datasets?list-type=2&prefix=taxi_trips%2F2024%2F)
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an S3 dataset like the supplied spicepod
2. See error

## Expected behavior

The Runtime should return a more specific and actionable error. For example, for the invalid region it should return an error about invalid region. For `s3_auth: iam_role` without a loaded IAM role it should return a permissions error.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
      s3_auth: iam_role
      s3_region: not-a-region
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No
