### ISSUE TITLE
S3 returns `No results.` when specifying an invalid `file_format`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3557]
## Describe the bug

When using the S3 connector, specifying a `file_format` that is invalid for the files being queried returns `No results.` instead of returning an error.

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure a dataset using a `file_format` parameter that is different to the actual stored files
2. Observe behavior

## Expected behavior

The Runtime should return an error when encountering a file in the specified path that differs from the specified `file_format`.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: csv
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No
