### ISSUE TITLE
S3 UX: Specifying only an `s3_key` without an `s3_secret` does not return an error

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3558]
## Describe the bug

When specifying only an `s3_key`, the S3 connector does not return an error.

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an S3 dataset with only an `s3_key`
2. Observe no error

## Expected behavior

 Because `s3_key` is only valid in the presence of `s3_secret`, the Runtime should error when only one of either exists instead of both.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
      s3_key: my-cool-key
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No
