### ISSUE TITLE
Specifying `s3_auth: key` is not supported in the S3 connector

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3559]
## Describe the bug

The S3 documentation states that `s3_auth: key` is a support parameter value, but the Runtime returns an error when specifying this parameter:

```
2024-11-18T23:45:12.001537Z  WARN runtime::init::dataset: Cannot connect to s3. Invalid or Unsupported Configuration: Unexpected S3 auth method: key
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Create an S3 dataset with `s3_auth: key`
2. See error

## Expected behavior

The Runtime should support specifying `s3_auth: key`

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
      s3_auth: key
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No
