### ISSUE TITLE
ODBC errors when setting `odbc_max_num_rows_per_batch` to 0

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3561]
## Describe the bug

ODBC errors or has returns no results when specifying some parameter values as `0`:

* `odbc_max_bytes_per_batch` - returns `No results.`
* `odbc_max_num_rows_per_batch` - Panics on the inner thread task
* `odbc_max_text_size` and `odbc_max_binary_size` when set to `0` makes no observable change in my testing

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure an odbc dataset with parameter values set to `0`
2. Observe behavior

## Expected behavior

The Runtime should return an invalid configuration error when setting parameter values to `0`, as they are not supported.

### Spicepod

```yaml
version: v1beta1
kind: Spicepod
name: spicepod
datasets:
  - from: odbc:table
    name: my_table
    params:
      odbc_connection_string: odbc_connection_string
      odbc_max_bytes_per_batch: 0
      odbc_max_num_rows_per_batch: 0
      odbc_max_text_size: 0
      odbc_max_binary_size: 0
```

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No
