### ISSUE TITLE
No refresh and no errors when `time_*` keys needed but not specified.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#3702]
## Describe the bug
For an append accelerated dataset, if `time_column` and `time_format` are not specified, there are no logs signs that the dataset won't refresh on `refresh_check_interval`.

## To Reproduce
`spiced -v`

Logs erroring:
```
2024-11-27T03:35:12.880575Z DEBUG runtime::accelerated_table::refresh_task::changes: Inserting data row for transac
2024-11-27T03:35:12.880618Z DEBUG runtime::accelerated_table::refresh_task::changes: Inserting data row for transac
```

### Spicepod
```yaml
version: v1beta1
kind: Spicepod
name: ai-test-spicepod

datasets:
  - from: spice.ai/eth.recent_transactions
    name: transac
#   time_column: block_timestamp
#    time_format: unix_seconds
    params:
      spiceai_api_key: ${secrets:SPICE_SPICEAI_API_KEY}
    acceleration:
      enabled: true
      refresh_mode: append
      refresh_sql: "SELECT * FROM transac"
      refresh_check_interval: 1s
```
