### ISSUE TITLE
Support multiple data connector/processor pairs per Dataspace

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#373]
This would enable the ability to bootstrap with one source of data, e.g. CSV, and then swap to using a streaming source of data. Initial support enables multiple pairs and naively merge all the data. An iteration would enable conditionals/selectors to know when to use either.

Manifest would look like:

```yaml
dataspaces:
  - from: from
     name: name
     data:
     - name: seed_data
       connector: ...
       processor: ...
     - name: streaming_data
        connector: ...
        processor: ...
```
