### ISSUE TITLE
Bug: inconsistent vector search result when chunking is enabled

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3749]
## Describe the bug

When I do search the result varies and there is missing item with previously highest score (cp_catalog_page_sk=1)

```console
spice search --limit 2
search> smart friend
Rank 1, Score: 65.8, Datasets [spice.public.catalog_page] cp_catalog_page_sk=1
In general basic characters welcome. Clearly lively friends con

Rank 2, Score: 60.6, Datasets [spice.public.catalog_page] cp_catalog_page_sk=9
So appropriate hopes cannot constitute with a shapes. Investors know therefo

Time: 350ms. 2 results.

search> smart friend
Rank 1, Score: 58.2, Datasets [spice.public.catalog_page] cp_catalog_page_sk=18
Absolute, early papers spare. Independent services need. About extreme women 

Rank 2, Score: 56.2, Datasets [spice.public.catalog_page] cp_catalog_page_sk=6
Legislative origins precede bold stations. Tiny sports should resume all pupils. Forces launch t

Time: 273ms. 2 results.

search> smart friend
Rank 1, Score: 65.8, Datasets [spice.public.catalog_page] cp_catalog_page_sk=1
In general basic characters welcome. Clearly lively friends con

Rank 2, Score: 60.6, Datasets [spice.public.catalog_page] cp_catalog_page_sk=9
So appropriate hopes cannot constitute with a shapes. Investors know therefo

Time: 413ms. 2 results.

search> smart friend
Rank 1, Score: 58.2, Datasets [spice.public.catalog_page] cp_catalog_page_sk=18
Absolute, early papers spare. Independent services need. About extreme women 

Rank 2, Score: 56.2, Datasets [spice.public.catalog_page] cp_catalog_page_sk=6
Legislative origins precede bold stations. Tiny sports should resume all pupils. Forces launch t

Time: 413ms. 2 results
```

## To Reproduce

```yaml
version: v1beta1
kind: Spicepod
name: ai-test-spicepod

datasets:    
  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    description: Represents an e-commerce platform's catalog page metadata
    params:
      file_format: parquet
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM catalog_page limit 20;
    embeddings:
      - column: cp_description
        column_pk:
          - cp_catalog_page_sk
        chunking:
          enabled: true
          target_chunk_size: 512
          overlap_size: 128
          trim_whitespace: false  
        use: openai_embeddings
    
embeddings:
  - from: openai:text-embedding-3-small
    name: openai_embeddings
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
    metadata: {}
```
