### ISSUE TITLE
Enhancement: Accelerate a subset of columns from source dataset

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3760]
## Goal-State/What/Result

Spice can accelerate only a subset of the full column set from a remote source into an acceleration.

## Why/Purpose

Reduce the amount of data transfer needed if only a subset of information is needed for an application to work.

## By When

**Issue/Spec written and reviewed:** Dec 3, 2024
**Done-Done:** Dec 3, 2024

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

The `refresh_sql` parameter in the acceleration section of the dataset can be used to specify a subset of columns from the source schema, and only those columns will be included in the acceleration and fetched from the remote source.

Only bare column references will be supported in the SELECT. Computed columns, aliases or any other expressions are not allowed.

Changing the columns selected from the Refresh SQL after startup is not allowed.

### Security Review

Reviewed, no impact.

## How/Plan

The validation of the refresh sql will produce a new schema that is used instead of the federated source schema.

## Release Notes

Accelerate a subset of columns: Spice now supports accelerating a subset of the columns from a federated source by specifying the columns in the [Refresh SQL](https://docs.spiceai.org/components/data-accelerators/data-refresh#refresh-sql).

Example Spicepod.yaml configuration:
```yaml
datasets:
  - from: s3://spiceai-demo-datasets/taxi_trips/2024/
    name: taxi_trips
    params:
      file_format: parquet
    acceleration:
      refresh_sql: SELECT tpep_pickup_datetime, tpep_dropoff_datetime, trip_distance, total_amount FROM taxi_trips
```
