### ISSUE TITLE
Support ingestion of transaction/correlation ids

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#377]
Enable the engine to ingest transaction or correlation ids, like `order_id` or `trace_id`.

To ingest unique ids today,  they would need to be set as categories, which is not scalable beyond a few ids. The initial version of this feature would simply enable them to be ingested, and round-tripped through the data APIs. In the second iteration, they would be available for reference in reward functions, and the third the potential to automatically correlate and flatten multiple rows of data on the id.

Proposed manifest

```yaml
dataspaces:
  - from: coinbase
    name: btcusd
    identifiers:
      - transaction_id
      - tick_id
    measurements:
      ...
```

alternative proposal:

```yaml
dataspaces:
  - from: coinbase
    name: btcusd
    transactions:
      identifiers:
        - transaction_id
        - tick_id
    measurements:
      ...
```

alternative proposal:

```yaml
dataspaces:
  - from: coinbase
    name: btcusd
    transactions:
      identifiers:
        - transaction_id
        - tick_id
      operator: and | or
    measurements:
      ...
```

alternative proposal:

```yaml
dataspaces:
  - from: coinbase
    name: btcusd
    correlation_ids:
      - transaction_id
      - tick_id
    measurements:
      ...
```
