### ISSUE TITLE
Dataspace Interpolation/Sparse data

### ISSUE THREAD

**Issue by Corentin-pro** [spiceai/spiceai#381]
Some data aren't mean to be interpolated, the interpolation can be an option. If such option is chosen categories shouldn't be interpolated. Having a warning stating the given names will be ignored as the data interpolation is enable can prevent future misunderstanding.

**Comment by Corentin-pro** [comment]
## Proposal

- Add a `interpolation` flag in the `params` section of the pod's manifest specification to allow the actual data interpolation using the `time` column. The new parameter could also hold string like `linear` to be able to use other types latter (`quadratic`, etc)
- In non interpolated mode the parameter `granularity` would be ignored : the client should print a warning if the manifest change the default value while not using interpolation.

## Example of manifests

Using interpolation:

```
name: my-project
params:
  epoch_time: 1634655600
  period: 240h
  interval: 24m
  granularity: 1m
  episodes: 10
  interpolation: linear
dataspaces:
[...]

```

Disable interpolation:

```
name: my-project
params:
  epoch_time: 1634655600
  period: 240h
  interval: 24m
  episodes: 10
dataspaces:
[...]
```

## Additional comments

- `categories` are 'one hot' encoded information, using interpolation on such column should not work nicely with ML algorithm. We might want to investigate with real use cases, for now skipping them in interpolation mode should be safer (with a printed warning)

**Comment by lukekim** [comment]
@Corentin-pro after a little thought, I think this should be at the field level, and perhaps be called `aggregation` so that it would also enable #260.

Thus the manifest would be.

```yaml
dataspaces:
  measurements:
  - name: travel_time
     selector: travel_time_ms
     aggregation: none
     fill: none
[...]
```
or with averaging:

```yaml
dataspaces:
  measurements:
  - name: travel_time
     selector: travel_time_ms
     aggregation: average
     fill: previous
[...]
```

or with counting.

```yaml
dataspaces:
  measurements:
  - name: travel_time
     selector: travel_time_ms
     aggregation: count
     fill: previous
[...]
```

"Interpolation" to me is synonymous with our existing concept of "fill" - basically how you handle missing or sparse data by estimating it.
