### ISSUE TITLE
Enhancement: Iceberg Catalog Connector Beta

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3872]
## Goal-State/What/Result

A new Iceberg Catalog Connector is implemented in Spice OSS that loads Iceberg/Spice.ai tables from the specified Iceberg REST Catalog API service

```yaml
catalogs:
  - from: iceberg:https://my_iceberg_host.com/v1/namespaces # Path to the `/v1/{prefix}/namespaces` API
    name: icey
    include:
      - "*.my_table"
    params:
      iceberg_bearer_token: ${ secrets:ICEBERG_BEARER_TOKEN }
```

The connector will recursively load all of the tables from all of the namespaces in the Iceberg catalog API.

To only load tables from a sub-namespace, specify the namespace identifier:

```yaml
catalogs:
  - from: iceberg:https://my_iceberg_host.com/v1/namespaces/top_namespace%1Fsecond_level_namespace # Only load tables under the `top_namespace.second_level_namespace` sub-namespace.
    name: icey
    include:
      - "*.my_table"
    params:
      iceberg_bearer_token: ${ secrets:ICEBERG_BEARER_TOKEN }
```

> [!NOTE]
> The `0x1F` as a separator is a bit ugly, but its what the official Iceberg spec requires - and I think its better to stick to that than trying to support a nicer syntax here. You can copy-paste this URL and it will work.

## Why/Purpose

Iceberg is an industry standard catalog API and table format.

## By When

**Issue/Spec written and reviewed:** Dec 16, 2024
**Done-Done:** To be scheduled

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes prepared

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

#### Merging namespaces

DataFusion doesn't support arbitrarily nested namespaces, limiting us to a 3-level hierarchy of `catalog.schema.table`.

The `catalog` will be the `name` that the user defines in their Spicepod configuration. The `schema` will be the `.` concatenated namespaces of the path to the table and `table` will be the name of the table.

> [!NOTE]
> Iceberg works similar to a filesystem where tables can exist in any namespace

Example: If we had this Iceberg catalog structure:

```
.
├── blockchain
│   └── eth
│       ├── blocks
│       └── transactions
├── spice
│   ├── tpch
│   │   ├── orders
│   │   └── customers
│   ├── info
│   └── extra
│       └── tpch_orders_metadata
└── unity
    └── very
        └── nested
            └── namespace
                └── foobar
```

Then this declaration in a consuming Spicepod would create the following datasets:
```yaml
catalogs:
  - from: iceberg:https://my_iceberg.com/v1/namespaces
    name: icey
```
- `icey.blockchain.eth.blocks`
  - `catalog`: `icey`, `schema`: `blockchain.eth`, `table`: `blocks`
- `icey.blockchain.eth.transactions`
  - `catalog`: `icey`, `schema`: `blockchain.eth`, `table`: `transactions`
- `icey.spice.tpch.orders`
  - `catalog`: `icey`, `schema`: `spice.tpch`, `table`: `orders`
- `icey.spice.tpch.customers`
  - `catalog`: `icey`, `schema`: `spice.tpch`, `table`: `customers`
- `icey.spice.info`
  - `catalog`: `icey`, `schema`: `spice`, `table`: `info`
- `icey.spice.extra.tpch_orders_metadata`
  - `catalog`: `icey`, `schema`: `spice.extra`, `table`: `tpch_orders_metadata`
- `icey.unity.very.nested.namespace.foobar`
  - `catalog`: `icey`, `schema`: `unity.very.nested.namespace`, `table`: `foobar`

Querying from these tables would normally require quoting the middle schema part, i.e. `SELECT * FROM icey."blockchain.eth".blocks` - however, we can relatively simply override how DataFusion parses table identifiers to put any extra identifiers into the `schema` section. Column selection can't be done like this, but that is a relatively edge case that we can still support with the quoting behavior.
