### ISSUE TITLE
Suppport to select columns on dataset

### ISSUE THREAD

**Issue by koolay** [spiceai/spiceai#3950]
**Is your feature request related to a problem? Please describe.**
Column like `password` should not retrieve on dataset.  It should be excluded.
**Describe the solution you'd like**

```yaml
datasets:
  - from: mysql:mytable
    name: my_dataset
    columns: [id, name,city]  # add 
    params:
      mysql_host: localhost
      mysql_tcp_port: 3306
      mysql_db: my_database
      mysql_user: my_user
      mysql_pass: ${secrets:mysql_pass}
```

**Describe alternatives you've considered**

**Additional context**
