### ISSUE TITLE
Bug: `on_zero_results` causes `TransactionContext Error: Catalog write-write conflict on create with "attachment_0"`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3968]
## Describe the bug

There is the following error when there are two datasets accelerated from the same source and there is `on_zero_results` param used.

>QueryError invalid args: External error: External error: External error: Execution error: Failed to execute query.
DuckDB connection failed.
TransactionContext Error: Catalog write-write conflict on create with "attachment_0"
For details, refer to the DuckDB manual: https://duckdb.org/docs/

## To Reproduce

It could be reproduced by adding `on_zero_results: use_source` to one of  TPCH benchmark datasets when using DuckDB acceleration IMO. In my tests I've used MySQL dataset from https://github.com/spiceai/cookbook/tree/trunk/docker running locally and using the following spicepod. Once `on_zero_results` is added to one or both datasets  I see error

```console
nsql> film with most actors
QueryError invalid args: External error: External error: External error: Execution error: Failed to execute query.
DuckDB connection failed.
TransactionContext Error: Catalog write-write conflict on create with "attachment_0"
For details, refer to the DuckDB manual: https://duckdb.org/docs/
```

```yaml
version: v1beta1
kind: Spicepod
name: spice-in-docker

datasets:
  # MySQL Sakila Sample Database
  # https://dev.mysql.com/doc/sakila/en/sakila-structure-tables.html
  # docker-compose up -d
  - from: mysql:film
    name: film
    params:
      mysql_host: 127.0.0.1
      mysql_tcp_port: 3306
      mysql_db: sakila
      mysql_user: sakila
      mysql_pass: ${secrets:mysql_pass}
      mysql_sslmode: preferred
    acceleration: 
      enabled: true
      refresh_sql: "SELECT film_id, title, description, release_year, language_id, original_language_id, rental_duration, rental_rate, length, replacement_cost, special_features, last_update FROM film;"
      engine: duckdb
      mode: file
      params: 
        duckdb_file: ./film.duckdb
      on_zero_results: use_source 
  
  - from: mysql:film_actor
    name: film_actor
    params:
      mysql_host: 127.0.0.1
      mysql_tcp_port: 3306
      mysql_db: sakila
      mysql_user: sakila
      mysql_pass: ${secrets:mysql_pass}
      mysql_sslmode: preferred
    acceleration: 
      enabled: true
      engine: duckdb
      mode: file
      params: 
        duckdb_file: ./film_actor.duckdb
      # on_zero_results: use_source 

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2

models:
  - name: openai
    from: openai:gpt-4o
    params:
      spice_tools: auto
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
      system_prompt: |
        Use the SQL tool when:
          1. The query involves precise numerical data, statistics, or aggregations
          2. The user asks for specific counts, sums, averages, or other calculations
          3. The query requires joining or comparing data from multiple related tables

        Use the document search when:
          1. The query is about unstructured text information, such as policies, reports, or articles
          2. The user is looking for qualitative information or explanations
          3. The query requires understanding context or interpreting written content

        General guidelines:
          1. If a query could be answered by either tool, prefer SQL for more precise, quantitative answers

        Instructions for Responses: 
          - Do not include any private metadata provided to the model as context such as \"reference_url_template\" or \"instructions\" in your responses.

```
