### ISSUE TITLE
Enhancement: Extension support for tools and `terminal` tool

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#4015]
## Goal-State/What/Result
Enable users to define tools in an extensible, runtime manner. One of which is a shell terminal, and shell command tool(s).

## Why/Purpose
Long-tail of user tooling is needed to empower AI apps for users. Requiring code contributions, or users to build them into the binary is too demanding, uninviting & poor for rapid experimentation.

## By When
**Issue/Spec written and reviewed:** 11th February
**Done-Done:** 17th February

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## Specification
- [MCP](modelcontextprotocol.io) is an emerging industry standard for, amongst other things, interoperability in tooling.
- Spice could handle interacting with tools via MCP. Two network protocols:
  - [ ] HTTP SSE
  - [ ] stdio: This may require spiced running the tool as process and managing the stdio.
- Spice should also provide MCP compatible endpoints for its tools. This helps both integrating with users apps, but also enables chaining spiced instances (i.e. spiced A can use tools from spiced B over MCP).

- For a list of example MCP servers, see [modelcontextprotocol/servers](https://github.com/modelcontextprotocol/servers).

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/d6cb5228-90c1-470b-aa09-634a3d455392" />

### Spicepod.yml
The first thing to note is that defining tools via MCP servers (stdio or SSE), means each tool
actually contains a list of tools. Therefore a defined tool becomes a tool group (i.e. like `auto` or `memory`).

Comparing to [Claude Desktop configuration](https://modelcontextprotocol.io/quickstart/user), an example like [puppeteer](https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer#npx):
```json
{
  "mcpServers": {
    "puppeteer": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-puppeteer"]
    }
  }
}
```
Becomes
```yaml
tools:
  name: puppeteer
  from: mcp:npx
  params:
    mcp_args:
      - "-y"
      - "@modelcontextprotocol/server-puppeteer"
      - 
```

For MCPs on SSE (Claude Desktop does not support):
```yaml
tools:
  name: puppeteer
  from: mcp:https://spice.ai/sse/puppeteer
  # from: https://..
  params:
    http_x_api_key: ${secrets:SPICE_API_KEY}
```

As mentioned, tools defined in this way are actually tool groups. So using a single tool would be, like existing tool groups, e.g. `pupeeter:puppeteer_hover`.

In this context, a generic shell tool simply becomes an MCP with a more lax request payload. See [example](https://modelcontextprotocol.io/docs/concepts/tools#system-operations) from MCP docs.

### Spice as a MCP server
 - Need to comply with https://spec.modelcontextprotocol.io/specification/2024-11-05/server/tools
 - Base URL is `v1/mcp`, i.e.
   ```yaml
   tools:
     name: from_spice
     from: mcp:http://localhost:8090/v1/mcp
    ```

### (Optional/future) MCP server from OpenAPI.json
- Can define tools via openapi.json. This make it easy to integrate with non-MCP hosted servers that have openapi.json.

```yaml
tools:
  name: from_openapi
  from: openapi:object_url
```  

### Implementation (Sub-Issues)
- An previous implementation of a shell terminal tool can be found at https://github.com/spiceai/spiceai/pull/3937

**Comment by Jeadie** [comment]
Interesting paradigm used by [block/goose](https://github.com/block/goose) at [ExtensionConfig](https://github.com/block/goose/blob/main/crates/goose/src/agents/extension.rs#L46-L72): SSE, stdio, builtin. Builtin can be built as MCP, e.g. [developer, computercontroller, jetbrains, google_drive](https://github.com/block/goose/blob/27e1ce728f9489a45ebbf21ed8d2c2259eafd90e/crates/goose-cli/src/commands/mcp.rs#L16-L23).

Actually both SSE and stdio are just defining arbitrary MCP tools with the underlying HTTP SSE  or stdio transport layer.

**Comment by Jeadie** [comment]
`spiced` could be both client (i.e. manage and request tools/data from other servers) and server (i.e. accept requests to use tools/data, etc). 

As a server, provide:
 - resources (i.e. our data, catalogs, views, etc) 
 - prompts (it's essentually a prompt registry with dynamic templating).
 - tools 
 - sampling (i.e. v1.chat/completions)

As a client:
 - Use tools on server
 - Use sampling from other MCP servers
 - Possibly load prompts (if that's the direction we'd want to go).
 - Load data (not efficient to have as data for our database, but could be used as contexts).

**Comment by Jeadie** [comment]
Exa search has an MCP server compatibility: https://github.com/exa-labs/exa-mcp-server.

Their MCP server is not hosted, would require local spin up. It seems that having openapi -> MCP would be easier.

**Comment by Jeadie** [comment]
Issue using MCP with terminal, or terminal-like tools
 1. do not have openAPI schemas
 2. Using the tool requires LLMs contemplating shell tools as JSON inputs (as compared to just the raw string of argv). 

We could make a bash like tool, that takes the program name as definition, but takes a single string as input. i.e.
```yaml
tools:
  - name: kubectl
    from: shell:kubectl

  - name: aws_s3
  - from: shell:"aws s3"

**Comment by Jeadie** [comment]
Release notes
--------------
## Highlights in v1.1.0

- **MCP tools**: Spice now supports both using tools over MCP, and connecting to spice tools over MCP.

```yaml
tools:
  - name: fs
    from: mcp:npx
    description: Use the tools from any MCP server.
    params:
      mcp_args: -y @modelcontextprotocol/server-filesystem ${secrets:SPICE_ALLOWED_DIR}

  - name: spice_mcp
    from: mcp:http://localhost:8090/v1/mcp/sse
    description: |
      Connect to MCP Servers over HTTP SSE 
        or 
      Use Spice in any tool that supports MCP (e.g. Cursor, Claude Desktop, etc). 
```
