### ISSUE TITLE
NSQL CLI error

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#4083]
## Describe the bug
An unexplained issue with NSQL CLI without many details.

## To Reproduce

```shell
>>> spice nsql 
Enter a query in natural language.
nsql> a random query

2024/12/23 14:11:12 ERROR sending nsql request error="error sending nsql request: Post \"http://localhost:8090/v1/nsql\": EOF"
```
In spicepod logs
```shell
Assertion failed: (col_ref.column_names.size() <= 3), function CreateStructPack, file bind_columnref_expression.cpp, line 235.
2024/12/23 14:11:12 ERROR error running Spice.ai error="os: process already finished"
```

### Spicepod
```yaml
name: pod
version: v1beta1
kind: Spicepod

datasets:
  - from: mysql:table_name
    name: table_name
    params:
      mysql_host: ${secrets:MYSQL_HOST}
      mysql_tcp_port: 3306
      mysql_db: db
      mysql_user: db_user
      mysql_pass: ${secrets:MYSQL_PASSWORD}
      mysql_sslmode: disabled
    time_column: created  
    acceleration:
      engine: duckdb
      mode: file
      params: 
        duckdb_file: ./local.db
      enabled: true
      refresh_check_interval: 30m
      refresh_mode: full
      refresh_sql: SELECT * FROM table_name WHERE created > '2024-08-01'
            

models:
  - from: openai:gpt-4o-mini
    name: nql
    params:
      tools: list_datasets,table_schema,sql
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
```

### Output of `describe table`
```
+------------------+------------------------------+-------------+
| column_name      | data_type                    | is_nullable |
+------------------+------------------------------+-------------+
| logid            | Int32                        | YES         |
| userid           | Int32                        | YES         |
| organizationid   | Int32                        | YES         |
| resourcetype     | Utf8                         | YES         |
| resourceid       | Int32                        | YES         |
| eventtype        | Utf8                         | YES         |
| eventdescription | Utf8                         | YES         |
| eventjsondata    | Utf8                         | YES         |
| oldvalue         | Utf8                         | YES         |
| newvalue         | Utf8                         | YES         |
| created          | Timestamp(Microsecond, None) | YES         |
+------------------+------------------------------+-------------+
```
