### ISSUE TITLE
"offset overflow" during HashJoin in DataFusion on large datasets

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#4216]
Note: Scoped out of 1.0 stable since it's a df physical plan issue

## Describe the bug

Datafusion panics with `offset overflow` error when executing TPCDS query 72 against a delta lake connector with TPCDS SF5 data, or an arrow accelerator with delta lake connector TPCDS SF5 data as data source. 

The panic happens at hashjoin physical execution, where the LHS and RHS data to be joined are each concatenated into a single record batch using `concat_batches`.

error
```
thread 'tokio-runtime-worker' panicked at /Users/qianqian/.cargo/git/checkouts/arrow-rs-ddec0d7286d46bb5/aecc340/arrow-array/src/builder/generic_bytes_builder.rs:86:57:
byte array offset overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Full backtrace:
```
thread 'tokio-runtime-worker' panicked at /Users/qianqian/.cargo/git/checkouts/arrow-rs-ddec0d7286d46bb5/aecc340/arrow-array/src/builder/generic_bytes_builder.rs:86:57:
byte array offset overflow
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: arrow_select::concat::concat_bytes
   4: arrow_select::concat::concat_batches
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: datafusion_physical_plan::joins::utils::OnceFut<T>::get_shared
   7: <datafusion_physical_plan::joins::hash_join::HashJoinStream as futures_core::stream::Stream>::poll_next
   8: <datafusion_physical_plan::coalesce_batches::CoalesceBatchesStream as futures_core::stream::Stream>::poll_next
   9: datafusion_common_runtime::trace_utils::trace_future::{{closure}}
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: tokio::runtime::task::harness::Harness<T,S>::poll
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  13: tokio::runtime::context::scoped::Scoped<T>::set
  14: tokio::runtime::context::runtime::enter_runtime
  15: tokio::runtime::scheduler::multi_thread::worker::run
  16: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::core::Core<T,S>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## To Reproduce
Connect to databricks TPCDS data source using the following config. (or change acceleration to true to enable arrow acceleration), observe the TPCDS query 72 fail whether acceleration is enabled or not.
```
  - from: databricks:<your-catalog>.tpcds_sf5.call_center
    name: call_center
    params: &db_params
      mode: delta_lake
      databricks_token: ${secrets:DATABRICKS_TOKEN}
      databricks_endpoint: ${secrets:DATABRICKS_ENDPOINT}
      databricks_aws_access_key_id: ${secrets:AWS_DATABRICKS_DELTA_ACCESS_KEY_ID}
      databricks_aws_secret_access_key: ${secrets:AWS_DATABRICKS_DELTA_SECRET_ACCESS_KEY}
      client_timeout: 600s
    acceleration:
      enabled: false
```
