### ISSUE TITLE
Bug: No field named body_embedding when do vector search with refresh sql containing subset of columns

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4258]
## Describe the bug

There is the following search error when refresh sql contains subset of columns, for example `body` column is included in refresh sql and  it contains embeddings

> search> test
2025/01/12 06:04:26 ERROR search failed error="Error occurred interacting with datafusion: Failed to execute query: Schema error: No field named body_embedding. Valid fields are spice.public.issues.id, spice.public.issues.number, spice.public.issues.title, spice.public.issues.body."

## To Reproduce

```yaml
version: v1beta1
kind: Spicepod
name: test

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2

datasets:
  - from: github:github.com/spiceai/spiceai/issues
    name: issues
    description: GitHub Issues for the Spice.ai project (github.com/spiceai/spiceai)
    params:
      github_token: ${secrets:GITHUB_TOKEN}
      github_query_mode: "search"
    acceleration:
      enabled: true
      refresh_sql: "SELECT id, number, title, body FROM issues WHERE created_at='2024-11-09T22:47:45'"
    embeddings:
      - column: body
        use: hf_minilm
```
