### ISSUE TITLE
Proposal: Continuous Actions

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#426]
# WHY

The types of applications you can build with just discrete actions are limited. Supporting continuous actions allows for building more powerful apps. This makes Spice.ai more useful for many real-world use-cases, which should attract more developers to the platform.

# WHAT

Discrete actions are useful for binary choices (yes/no) or choosing actions from a known fixed set. There are many classes of applications that require a continuous output to be useful, which Spice.ai cannot support yet. Instead of "turn left", it would be "turn left 23.2 degrees". Or instead of "buy bitcoin" it would be "buy 0.21 bitcoin".

As a developer authoring a Spicepod, I can indicate in the manifest file that an action is continuous by setting a `range` parameter on the action. The `range` specifies a minimum value and maximum value the action value can take. It is possible to mix discrete actions with continuous actions in a single Spicepod, but only one will be chosen at a given time. 

In the reward function, an extra parameter `action_value` is available to indicate which value the engine chose during training.

## Spicepod manifest format

Example 1: A trading application that wishes to either buy/sell in small amounts (in increments of 0.05) or buy/sell in large amounts (in increments of 1) or hold.

Potential recommendations:
`buy_small = 0.45`
`sell_small = 0.19`
`buy_large = 20`
`sell_large = 1`
`hold`

```yaml
actions:
  - name: buy_small
    range: [0, 1]
    resolution: 0.05
  - name: buy_large
    range: [1, 40]
    resolution: 1
  - name: sell_small
    range: [0, 1]
    resolution: 0.01
  - name: sell_large
    range: [1, 40]
    resolution: 1
  - name: hold
```

Example 2: A monitoring application that learns to recognize normal activity and provides a "score" for how unusual the environment becomes. You can imagine a built-in reward function that does this combined with user-submitted interpretations on which areas are "normal" vs "abnormal".

Potential recommendations:
`unusual = 1.43`
`unusual = 2.49`
`unusual = 10.23`
`unusual = 30.45`
`unusual = 90.12`

```yaml
actions:
  - name: unusual
    range: [0, 100]
    resolution: 0.01
```

Example 3: A fee minimization application (defly.ai) that learns to minimize the max fee needed to get into a next block. (For defly.ai we would have multiple Spicepods that have rewards tailored for the various times we want to train on)

Potential recommendations:

```yaml
actions:
  - name: set_max_fee_gwei
    range: [0, 300]
    resolution: 0.0001
```

Example 3.1: Slippage part of defly.ai. Also would have multiple pods for each time frame and per token.

Potential recommendations:
`slippage_percent = 0.5`
`slippage_percent = 0.9`
`slippage_percent = 4.2`
`slippage_percent = 10.3`

```yaml
actions:
  - name: set_slippage_percent
    range: [0, 100]
    resolution: 0.01
```

## Open Questions
1. Are fixed ranges sufficient? It makes sense in some cases, like ratings or percentages. But for things like the "max fee in gwei" - that is dependent on the state of the network, which can change over time. That would require going back and updating the Spicepod again. Should we make the range optionally dependent on measurement? Probably too complex for now - but wanted to bring it up for completeness.
2. Multi-actions would be useful here (especially for the defly scenario) - but I'm not including them as part of this proposal. We can work around multi-actions by defining multiple pods that are identical except for the action.
3. It would be really useful for training a defly Spicepod to be able to "recall" past predictions. If I'm training a Spicepod that gives me slippage estimates for 2 minutes out, it would be useful in the reward function to be able to see which prediction was made "2 minutes ago" and compare the price from that value to the price now. I'm not sure what that should look like. Perhaps the reward function itself just keeps a cache of predictions that happened (as a workaround)? We should also pass the timestamp into the reward function. 
4. What if we built in a "learning delay" where we know we can't learn/provide rewards until some time has passed to be able to see how the state changes. Then in the reward function we pass current_state, but instead of the action that was taken "now" we pass the action that was taken "*learning delay*" minutes ago along with the state from "*learning delay*" minutes ago. (And we wouldn't pass next_state). This seems like its own proposal, see #485 

## Alternate Spicepod formats

Other formats I considered for the Spicepod

#### Alt Option 1
```yaml
actions:
  - name: slippage_percent
    range:
      min: 1
      max: 100
      resolution: 0.01
```

#### Alt Option 2
```yaml
actions:
  - name: slippage_percent
    type: continuous
    range:
      min: 1
      max: 100
      resolution: 0.01
```

#### Alt Option 3
```yaml
actions:
  - name: slippage_percent
    type: continuous
    range:
      min: 1
      max: 100
      resolution: 0.01
```

## Reward function changes

If the reward function is not for a continuous action, it remains the same.

If the reward function is for a continuous action, it is passed an extra parameter: `action_value`

```python
def reward_for_action(
  current_state: dict, 
  current_state_interpretations: list, 
  next_state: dict, 
  next_state_interpretations: list, 
  action_value: float
) -> float:
```

# HOW

coming soon...
