### ISSUE TITLE
S3 Data Connector - fix error message when connecting to custom `http` endpoint without `allow_http` enabled

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4358]
## Describe the bug

```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf5
datasets:
  - from: s3://tpcds-sf5/call_center.parquet
    name: call_center
    params:
      client_timeout: 3h
      s3_endpoint: http://localhost:9000
      # allow_http: true
```

fails with bad error
```
2025-01-16T02:38:05.834529Z  WARN runtime::init::dataset: Cannot connect to the dataset call_center (s3).
Object Store error: Generic S3 error: Error after 10 retries in 1.786348042s, max_retries:10, retry_timeout:180s, source:error sending request for url (http://s3service.data.orb.local:9000/tpcds-sf5/call_center.parquet)
```

## Expected behavior

Error message should be clear. Inform user that s3 dataset with custom `http` endpoint can't be registered without explicit `allow_http` param
