### ISSUE TITLE
S3 Data Connector - TPCDS SF5 Query 72 causes huge CPU usage

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4360]
## Describe the bug

Query has 11 joins across 9 tables:

```sql
select  i_item_desc
      ,w_warehouse_name
      ,d1.d_week_seq
      ,sum(case when p_promo_sk is null then 1 else 0 end) no_promo
      ,sum(case when p_promo_sk is not null then 1 else 0 end) promo
      ,count(*) total_cnt
from catalog_sales
join inventory on (cs_item_sk = inv_item_sk)
join warehouse on (w_warehouse_sk=inv_warehouse_sk)
join item on (i_item_sk = cs_item_sk)
join customer_demographics on (cs_bill_cdemo_sk = cd_demo_sk)
join household_demographics on (cs_bill_hdemo_sk = hd_demo_sk)
join date_dim d1 on (cs_sold_date_sk = d1.d_date_sk)
join date_dim d2 on (inv_date_sk = d2.d_date_sk)
join date_dim d3 on (cs_ship_date_sk = d3.d_date_sk)
left outer join promotion on (cs_promo_sk=p_promo_sk)
left outer join catalog_returns on (cr_item_sk = cs_item_sk and cr_order_number = cs_order_number)
where d1.d_week_seq = d2.d_week_seq
  and inv_quantity_on_hand < cs_quantity
  and d3.d_date > d1.d_date + INTERVAL '5 days'
  and hd_buy_potential = '501-1000'
  and d1.d_year = 1999
  and cd_marital_status = 'S'
group by i_item_desc,w_warehouse_name,d1.d_week_seq
order by total_cnt desc, i_item_desc, w_warehouse_name, d_week_seq
 LIMIT 100;
```

Which causes very exhaustive physical plan.
Runtime utilizes all available CPU in local and benchmark environment (load tests), and affects concurrent queries.

Example: CPU usage on M1 Max, while querying q72. Runtime connected to local minio instance with tpcds sf5 datasets
<details><summary>spicepod.yaml</summary>

```yaml
version: v1beta1
kind: Spicepod
name: tpcds-sf5
datasets:
  - from: s3://tpcds-sf5/call_center.parquet
    name: call_center
    params: &s3_params
      client_timeout: 3h
      s3_endpoint: http://localhost:9000
      allow_http: true

  - from: s3://tpcds-sf5/catalog_page.parquet
    name: catalog_page
    params: *s3_params

  - from: s3://tpcds-sf5/catalog_returns.parquet
    name: catalog_returns
    params: *s3_params

  - from: s3://tpcds-sf5/catalog_sales.parquet
    name: catalog_sales
    params: *s3_params

  - from: s3://tpcds-sf5/customer.parquet
    name: customer
    params: *s3_params

  - from: s3://tpcds-sf5/customer_address.parquet
    name: customer_address
    params: *s3_params

  - from: s3://tpcds-sf5/customer_demographics.parquet
    name: customer_demographics
    params: *s3_params

  - from: s3://tpcds-sf5/date_dim.parquet
    name: date_dim
    params: *s3_params

  - from: s3://tpcds-sf5/household_demographics.parquet
    name: household_demographics
    params: *s3_params

  - from: s3://tpcds-sf5/income_band.parquet
    name: income_band
    params: *s3_params

  - from: s3://tpcds-sf5/inventory.parquet
    name: inventory
    params: *s3_params

  - from: s3://tpcds-sf5/item.parquet
    name: item
    params: *s3_params

  - from: s3://tpcds-sf5/promotion.parquet
    name: promotion
    params: *s3_params

  - from: s3://tpcds-sf5/reason.parquet
    name: reason
    params: *s3_params

  - from: s3://tpcds-sf5/ship_mode.parquet
    name: ship_mode
    params: *s3_params

  - from: s3://tpcds-sf5/store.parquet
    name: store
    params: *s3_params

  - from: s3://tpcds-sf5/store_returns.parquet
    name: store_returns
    params: *s3_params

  - from: s3://tpcds-sf5/store_sales.parquet
    name: store_sales
    params: *s3_params

  - from: s3://tpcds-sf5/time_dim.parquet
    name: time_dim
    params: *s3_params

  - from: s3://tpcds-sf5/warehouse.parquet
    name: warehouse
    params: *s3_params

  - from: s3://tpcds-sf5/web_page.parquet
    name: web_page
    params: *s3_params

  - from: s3://tpcds-sf5/web_returns.parquet
    name: web_returns
    params: *s3_params

  - from: s3://tpcds-sf5/web_sales.parquet
    name: web_sales
    params: *s3_params

  - from: s3://tpcds-sf5/web_site.parquet
    name: web_site
    params: *s3_params

```

</details> 

![Image](https://github.com/user-attachments/assets/94143be1-42bd-4fe6-97cc-c3ce657485e6)
