### ISSUE TITLE
xAI Grok 2 doesn't use memory tools automatically

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4493]
## Describe the bug

Memory tool used by Grok only after explicitly calling it:

![Image](https://github.com/user-attachments/assets/3018f629-a81e-4e7f-9af2-36d399c0ddd6)

![Image](https://github.com/user-attachments/assets/66a2cf4f-6aa3-441a-b2b1-fe9ba61f1f7c)

## To Reproduce

```yaml
version: v1
kind: Spicepod
name: llm-memory

datasets:
  - from: memory:store
    name: llm_memory
    mode: read_write


models:
  - from: xai:grok-2-latest
    name: groq
    params:
      xai_api_key: ${ secrets:XAI_API_KEY }
      tools: memory
```
