### ISSUE TITLE
Model default overrides only work when prefixed with `openai_` even for xAI and Anthropic providers

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4494]
## Describe the bug

Default parameter overrides recognized onyly with `openai_` prefix, which is not consistent (other params prefixed with provider name) and not intuitive

```yaml
models:
  - from: xai:grok-2-latest
    name: groq
    params:
      xai_api_key: ${ secrets:XAI_API_KEY }
      openai_tool_choice: "auto"

  - from: anthropic:claude-3-5-sonnet-latest
    name: claude
    params:
      anthropic_api_key: ${secrets:ANTHROPIC_API_KEY}
      openai_tool_choice: "auto"
```
