### ISSUE TITLE
DuckDB connector and accelerator, and Sqlite accelerator doesn't support specific DataFusion scalar functions

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4510]
## Describe the bug

Spicepod

```yaml
version: v1
kind: Spicepod
name: quickstart
datasets:

- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  description: taxi trips in s3
  params:
    file_format: parquet
  acceleration:
    enabled: true
    engine: duckdb
    refresh_sql: "SELECT * FROM taxi_trips LIMIT 20"
```

Query
```sql
SELECT LEFT(TO_CHAR(tpep_pickup_datetime, '%Y-%m-%d'), 10) AS pickup_at FROM taxi_trips LIMIT 2;
```

Works fine if acceleration engine is arrow:
```
sql> SELECT LEFT(TO_CHAR(tpep_pickup_datetime, '%Y-%m-%d'), 10) AS pickup_at FROM taxi_trips LIMIT 2;
+------------+
| pickup_at  |
+------------+
| 2024-01-10 |
| 2024-01-10 |
+------------+
```

Fails with duckdb acceleration (same error if loading this dataset from duckdb connector):
```
sql> SELECT LEFT(TO_CHAR(tpep_pickup_datetime, '%Y-%m-%d'), 10) AS pickup_at FROM taxi_trips LIMIT 2;
Query Error: Failed to execute query.
Catalog Error: Scalar Function with name to_char does not exist!
Did you mean "to_hours"?
LINE 1: WITH fetch_schema AS ( SELECT left(to_char("taxi_trips"."tpep_pickup_datet...
```

Fails with sqlite acceleration:
```
sql> SELECT LEFT(TO_CHAR(tpep_pickup_datetime, '%Y-%m-%d'), 10) AS pickup_at FROM taxi_trips LIMIT 2;
Query Error: Failed to execute query.
This error message has been truncated.
For the full error message, execute `.error`.
sql> .error
Client specified an invalid argument.
Failed to execute query.
ConnectionError Rusqlite("no such function: to_char in SELECT left(to_char(`taxi_trips`.`tpep_pickup_datetime`, '%Y-%m-%d'), 10) AS `pickup_at` FROM `taxi_trips` LIMIT 2 at offset 12")
```

[`TO_CHAR`](https://datafusion.apache.org/user-guide/sql/scalar_functions.html#to-char) is a valid DF scalar function
