### ISSUE TITLE
Enhancement: Perplexity.ai Connector

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#4521]
## Goal-State/What/Result
Perplexity can be used as both 
1. An LLM component (i.e. defined in a spicepod under `models`
2. A search engine tool that provides summary and citations for a given question. The paradigm for Perplexity as a search engine tool should be extensible to similar components (e.g. exa.ai, tavily.com, DuckDuckGo). 

## Why/Purpose
Perplexity is a useful model LLM interactions heavily relying on public context (citations), but may not be the only or best search engine for a given use case/task .

## By When

**Issue/Spec written and reviewed:** 4th February
**Done-Done:** 7th February

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [ ] Release Notes prepared

#### Perplexity model connector,
 - via Sonar [API](https://docs.perplexity.ai/api-reference/chat-completions).
   - The [response citations](https://docs.perplexity.ai/api-reference/chat-completions#response-citations) should be added as internal tool calls in the tracing (i.e. `runtime.task_history`).

```yaml
models
 - from: perplexity:sonar # default is sonar
   name: perp_llm
   params:
     perplexity_api_key: ${ secrets:SPICE_PERPLEXITY_API_KEY }
     perplexity_search_recency_filter: month
```
- `params.perplexity_*` provide model overrides, including non-openai compatible params (e.g. `search_recency_filter`).

#### A standard interface for search engine tools
Possible input Schema
```json
{
  "query": String,
  "limit": uint,
}
```

Response Schema
```json
{ 
  "summary": String | optional,
  "results": [
    {
      "url": String,
      "title": String | optional,
      "type": Webpage | Image,
      "content": String | optional
    }
 ] 
}
```
- This enhancement will only include perplexity as a search engine. 

--- 

Spicepod
```yaml
tools:

 - from: search:perp_llm # assumes `model` with `name: perp_llm` is defined. 
 - from: search:perplexity
    name: perp_tool
    params:
      model: sonar
      perplexity_api_key: ${ secrets:SPICE_PERPLEXITY_API_KEY }
      perplexity_search_recency_filter: month
```
 - `params` for `search:perplexity` include all from related LLM, as well as optional `model`.

### Security Review
 - Perplexity connector and search engine tools will have no side effects on the spice runtime.
 - Both connector and tools introduce unsanitised raw content from non-deterministic sources as per current setup (i.e. other models).

**Comment by Jeadie** [comment]
## Release Notes

Web search tooling: Spice provides new tools for LLMs to connect to the internet 

Example Spicepod.yml configuration:
```yaml
tools:
  - name: the_internet
    from: websearch
    description: "Search the web for information."
    params:
      engine: perplexity
      perplexity_auth_token: ${ secrets:SPICE_PERPLEXITY_AUTH_TOKEN }

models:
  - name: my_llm
    from: huggingface:huggingface.co/meta-llama/Llama-3.2-3B-Instruct
```
