### ISSUE TITLE
AI/LLM benchmark: run FinanceBench locally

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4565]

**Comment by sgrebnov** [comment]
Failed to run benchmark due to PDF loading issues:
[Bug: only first page of PDF document is loaded as content](https://github.com/spiceai/spiceai/issues/4570)
[Bug: refresh does not show warning or error when unable to accelerate PDF file](https://github.com/spiceai/spiceai/issues/4569)
[Bug: PDF document parsing fails with Error: ToUnicodeCMap(Parse(Error))](https://github.com/spiceai/spiceai/issues/4568)

**Comment by sgrebnov** [comment]
Converted pdf to txt

```bash
brew install poppler
for file in *.pdf; do pdftotext "$file"; done
```

Embeddings creation took 1h 2m 49s 341ms (local model, metal accelerated)

>2025-01-30T04:22:57.244596Z  INFO runtime::accelerated_table::refresh_task: Loaded 366 rows (471.73 MiB) for dataset data in 1h 2m 49s 341ms.

```yaml
embeddings:
  - from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
    name: all_MiniLM_L6_v2


- from: file://txt
    name: data
    params: 
      file_format: txt
    acceleration: 
      enabled: true
      engine: duckdb
      mode: file
    embeddings:
    - column: content
      chunking:
        enabled: true
        target_chunk_size: 256
        overlap_size: 64
        trim_whitespace: false
      use: all_MiniLM_L6_v2
```
