### ISSUE TITLE
Bug: PDF document parsing fails with `Error: ToUnicodeCMap(Parse(Error))`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4568]
## Describe the bug

50% of pdf documents from https://github.com/patronus-ai/financebench/tree/main/pdfs are failed to load/parse with the following error:

>External error: Error parsing document Users/sg/playground/financebench/pdfs/AMERICANWATERWORKS_2021_10K.pdf: Internal parsing PDF document. Error: ToUnicodeCMap(Parse(Error))

## To Reproduce

```yaml
version: v1
kind: Spicepod
name: financebench

datasets:
  - from: file://pdfs
    name: data
    params: 
      file_format: pdf
    acceleration: 
      enabled: false
```
