### ISSUE TITLE
Bug: local models should verify that specified path exists

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4589]
## Describe the bug

```yaml
models:
  - from: file://phi-3-mini-does-not-exist
    name: local_model
    params:
      model_type: phi3
```

>2025-01-31T07:37:57.655474Z  INFO runtime::init::model: Loading model [local_model] from file://phi-3-mini-does-not-exist...
2025-01-31T07:37:57.655639Z  WARN runtime::init::model: Failed to load model local_model from spicepod.
Unable to determine model type. Verify the model source and try again

There should be message that model folder does not exist for better DX / troubleshooting
