### ISSUE TITLE
Task: `o3-mini-low` is graded against the model grading criteria

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#4596]
config
```
models:
  - from: openai:o3-mini
    name: openai_model
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
      openai_reasoning_effort: low
```
