### ISSUE TITLE
Task: `o3-mini-high` is graded against the model grading criteria

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#4597]
Config:

```
models:
  - from: openai:o3-mini
    name: openai_model
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
      openai_reasoning_effort: high
```
