### ISSUE TITLE
Task: `deepseek-ai/DeepSeek-R1` is graded against the models grading criteria

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#4600]
config

```
models:
  - from: openai:deepseek-reasoner
    name: deepseek
    params:
      tools: auto
      endpoint: https://api.deepseek.com
      openai_api_key: ${secrets:DEEPSEEK_API_KEY}
```
