### ISSUE TITLE
Inference speed regression in running local models on v1.0.2

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#4659]
## Describe the bug

After we released the `v1.0.2` binaries - during post-release testing we found that the inference speed of local models dropped significantly. With `v1.0.1` I was able to get 10 tok/s on the `meta-llama/Llama-3.2-3B-Instruct` huggingface model running on an Nvidia RTX 3060 GPU. On `v1.0.2` it dropped to 2 tok/s for the same model and GPU - a 5x speed decrease.

## To Reproduce

Run the below Spicepod on a Windows machine with a GPU on `v1.0.1` and note the tokens/sec. Run the same spicepod with `v1.0.2` and notice the inference speed has decreased.

## Expected behavior

The inference speed is the same or better in subsequent versions.

### Spicepod

```yaml
version: v1
kind: Spicepod
name: llama

models:
  - from: huggingface:huggingface.co/meta-llama/Llama-3.2-3B-Instruct
    name: llama
    params:
      hf_token: ${secrets:HF_TOKEN}
```

## Screenshots

Here is a screenshot of the GPU usage when running the Llama model on `1.0.2`. Notice that the GPU memory has increased, indicating it has loaded the model into memory. Also notice the GPU 3D compute (which is where the CUDA operations happen) is not maxxed out. In previous versions, this was maxxed out during inferencing.

<img width="831" alt="Image" src="https://github.com/user-attachments/assets/50e350fa-d273-4504-8356-7c219a38245e" />

Running the non-CUDA models binary (i.e. `spice install ai --cpu`) performed even worse - which indicates the GPU was still being utilized, but not to its fullest extent.

## Additional context

I suspect a regression in the `mistral.rs` library or our usage of it.

Additional logs:
CUDA(fast):
https://gist.github.com/sgrebnov/2dc75a4b34ee16f016f6d8ec4c2199dc

CUDA(slow):
https://gist.github.com/sgrebnov/abc9e0e6ace8788717f0ee0b2c7625db
