### ISSUE TITLE
Task: `o1-low` is graded against the model grading criteria

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#4691]
config
```yaml
  - from: openai:o1
    name: openai_model
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
      openai_reasoning_effort: low
```
