### ISSUE TITLE
Task: `o1-high` is graded against model grading criteria

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#4692]
config
```yaml
models:
  - from: openai:o1
    name: openai_model
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
      openai_reasoning_effort: high
```
