### ISSUE TITLE
Task: `o1-medium` is graded against model grading criteria

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#4693]
config
```yaml
models:
  - from: openai:o1
    name: openai_model
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
```
