### ISSUE TITLE
Task: grok-2-1212 is graded against grading criteria

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#4696]
config

```
models:
- from: xai:grok2-latest
  name: xai
  params:
    xai_api_key: ${secrets:SPICE_GROK_API_KEY}
```
