### ISSUE TITLE
Bug: grok-2 `The arguments to a tool_call with ID 'initial_list_datasets' are not a valid JSON string` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4734]
## Describe the bug

https://github.com/spiceai/spiceai/actions/runs/13247963474/job/36979482706

>2025-02-10T18:46:35.720905Z ERROR async_openai::error: failed deserialization of: {"code":"Client specified an invalid argument","error":"The arguments to a tool_call with ID 'initial_list_datasets' are not a valid JSON string. Parsing error: Error(\"EOF while parsing a value\", line: 1, column: 0)"}

It seems grok-2 does support tools calling, for example:

https://github.com/moesmufti/xai_grok_sdk?tab=readme-ov-file#function-tool-calling

## To Reproduce

https://github.com/spiceai/spiceai/actions/runs/13247963474/job/36979482706

**Comment by Jeadie** [comment]
Replicated via

```yaml
version: v1
kind: Spicepod
name: bug

models:
  - name: grok2
    from: xai:grok-2-1212
    params:
      spice_tools: auto
      xai_api_key: ${secrets:SPICE_XAI_API_KEY}
```

```shell
curl -XPOST http://localhost:8090/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
        "model": "grok2",
        "messages": [
            {"role": "user", "content": "What is the capital of New York?"}
        ]
      }'
```
