### ISSUE TITLE
Bug: unable to specify column with uppercase letters as "primary_key" (acceleration)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4737]
## Describe the bug

> 2025-02-10T23:06:02.848785Z ERROR runtime::accelerated_table::refresh_task: Failed to refresh dataset taxi_trips (s3): Failed to get data from the connector.
External error: Constraint Violation: Schema error: No field named vendorid. Valid fields are "?table?"."VendorID", "?table?".tpep_pickup_datetime, "?table?".tpep_dropoff_datetime, "?table?".passenger_count, "?table?".trip_distance, "?table?"."RatecodeID", "?table?".store_and_fwd_flag, "?table?"."PULocationID", "?table?"."DOLocationID", "?table?".payment_type, "?table?".fare_amount, "?table?".extra, "?table?".mta_tax, "?table?".tip_amount, "?table?".tolls_amount, "?table?".improvement_surcharge, "?table?".total_amount, "?table?".congestion_surcharge, "?table?"."Airport_fee".
Ensure the dataset configuration is valid, and try again.

Indexes might have a similar issue and needs to be verified as well well.

## To Reproduce

```yaml
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  time_column: tpep_pickup_datetime
  params:
    file_format: parquet
  acceleration:
    enabled: true
    engine: duckdb
    mode: memory
    primary_key: '(VendorID, trip_distance)'

```
