### ISSUE TITLE
Bug: refresh_sql columns should not be automatically normalized to lowercase

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4786]
## Describe the bug

```yaml
- from: s3://spiceai-public-datasets/taxi_trips/taxi_sample.parquet
    name: taxi_trips
    acceleration:
      enabled: true
      refresh_sql: "SELECT * FROM taxi_trips where VendorID = 1"
```

>2025-02-13T18:44:19.364844Z ERROR runtime::accelerated_table::refresh_task: Failed to refresh dataset taxi_trips (s3): Failed to get data from the connector.
Schema error: No field named vendorid. Valid fields are taxi_trips."VendorID", taxi_trips.tpep_pickup_datetime, taxi_trips.tpep_dropoff_datetime, taxi_trips.passenger_count, taxi_trips.trip_distance, taxi_trips."RatecodeID", taxi_trips.store_and_fwd_flag, taxi_trips."PULocationID", taxi_trips."DOLocationID", taxi_trips.payment_type, taxi_trips.fare_amount, taxi_trips.extra, taxi_trips.mta_tax, taxi_trips.tip_amount, taxi_trips.tolls_amount, taxi_trips.improvement_surcharge, taxi_trips.total_amount, taxi_trips.congestion_surcharge, taxi_trips."Airport_fee".
Ensure the dataset configuration is valid, and try again.
