### ISSUE TITLE
Bug: DuckDB acceleration `Binder Error: Failure while replaying WAL file` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4814]
## Describe the bug

>Binder Error: Failure while replaying WAL file "/Users/sg/spice/spiceai/.spice/data/accelerated_duckdb.db.wal": Referenced table "taxi_trips_spice_99a9ab1a" not found!

## To Reproduce

```yaml
- from: s3://spiceai-demo-datasets/taxi_trips/2024/
  name: taxi_trips
  time_column: tpep_pickup_datetime
  params:
    file_format: parquet
  acceleration:
    enabled: true
    engine: duckdb
    mode: file
    refresh_sql: "SELECT * FROM taxi_trips limit 1"
    primary_key: tpep_pickup_datetime
    indexes:
      tpep_pickup_datetime: enabled
```
