### ISSUE TITLE
Catalog api `/v1/namespaces/<namespace>/tables/<table>` returns 404 on table with `List` column type (from embeddings)

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#4815]
## Describe the bug

If table has `List` column type it is listed in catalog tables api, but returns 404 on getting table details, most likely on schema

spicepod:

```yaml
version: v1
kind: Spicepod
name: iceberg-catalog-bug

datasets:
  - from: github:github.com/ewgenius/docs/files/trunk
    name: docs_with_embeddings
    description: Documentation for Spice.ai
    params:
      include: "**/*.md"
    acceleration:
      enabled: true
    columns:
      - name: content
        embeddings:
          - chunking:
              enabled: true
              overlap_size: 128
              target_chunk_size: 512
              trim_whitespace: true
            from: openai_embeddings
            row_id:
              - path

  - from: github:github.com/ewgenius/docs/files/trunk
    name: docs
    description: Documentation for Spice.ai
    params:
      include: "**/*.md"

embeddings:   
  - from: openai
    name: openai_embeddings
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
```

List tables:

```console
curl -sX GET 'http://localhost:8090/v1/namespaces/spice%1Fpublic/tables' | jq
{
  "identifiers": [
    {
      "namespace": [
        "spice",
        "public"
      ],
      "name": "docs"
    },
    {
      "namespace": [
        "spice",
        "public"
      ],
      "name": "docs_with_embeddings"
    }
  ]
}
```

Get table without embeddings:

```console
curl -sX GET 'http://localhost:8090/v1/namespaces/spice%1Fpublic/tables/docs' | jq
{
  "metadata": {
    "format_version": 2,
    "table_uuid": "ce874eec-c754-4d3d-874f-8d5890afaec9",
    "location": "spice.ai/spice.public.docs",
    "schemas": [
      {
        "schema-id": 0,
        "type": "struct",
        "fields": [
          {
            "id": 0,
            "name": "name",
            "required": false,
            "type": "string"
          },
          {
            "id": 1,
            "name": "path",
            "required": false,
            "type": "string"
          },
          {
            "id": 2,
            "name": "size",
            "required": false,
            "type": "long"
          },
          {
            "id": 3,
            "name": "sha",
            "required": false,
            "type": "string"
          },
          {
            "id": 4,
            "name": "mode",
            "required": false,
            "type": "string"
          },
          {
            "id": 5,
            "name": "url",
            "required": false,
            "type": "string"
          },
          {
            "id": 6,
            "name": "download_url",
            "required": false,
            "type": "string"
          }
        ]
      }
    ]
  }
}
```

Table with embeddings

```console
curl -sX GET 'http://localhost:8090/v1/namespaces/spice%1Fpublic/tables/docs_with_embeddings' | jq
{
  "error": {
    "message": "Internal Server Error: DF_INVALID_SCHEMA",
    "type": "InternalServerError",
    "code": 500
  }
}
```

Table schema

```console
sql> show columns from docs_with_embeddings;
+---------------+--------------+----------------------+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| table_catalog | table_schema | table_name           | column_name       | data_type                                                                                                                                                                                                                                      | is_nullable |
+---------------+--------------+----------------------+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| spice         | public       | docs_with_embeddings | name              | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | path              | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | size              | Int64                                                                                                                                                                                                                                          | YES         |
| spice         | public       | docs_with_embeddings | sha               | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | mode              | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | url               | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | download_url      | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | content           | Utf8                                                                                                                                                                                                                                           | YES         |
| spice         | public       | docs_with_embeddings | content_embedding | List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 1536), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }) | NO          |
| spice         | public       | docs_with_embeddings | content_offset    | List(Field { name: "item", data_type: FixedSizeList(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 2), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })      | NO          |
+---------------+--------------+----------------------+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+

Time: 0.043793209 seconds. 10 rows.
```
