### ISSUE TITLE
Enhancement: `last_modified` metadata column added for append-mode object-store based connectors

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#4850]
## Goal-State/What/Result

When an object-store based Data Connector uses `mode: append` for the acceleration if either `time_column` or `time_partition_column` is set to `last_modified`, it will automatically detect and append only newly created/updated files based on the file/object's metadata.

If `last_modified` already exists as a column in the parquet data, then that column will take precedence over the metadata value from the file itself.

Example using `time_column`:

```yaml
- from: s3://my_bucket/my_dataset
  name: my_dataset
  params:
    file_format: parquet
  time_column: last_modified
  acceleration:
    enabled: true
    mode: append
```

Example using `time_partition_column`:

```yaml
- from: s3://my_bucket/my_dataset
  name: my_dataset
  params:
    file_format: parquet
  time_column: created_at
  time_partition_column: last_modified
  acceleration:
    enabled: true
    mode: append
```

## Why/Purpose

This will optimize some scenarios where a large parquet append-only dataset adds new files.

## By When

**Issue/Spec written and reviewed:** Mon Feb 24
**Done-Done:** Mon Mar 19

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

Create a new `spice_sys` table called 

### Security Review

This is an optimization that does not affect security.

## Release Notes

**Optiimized Append for Object-store Connectors**: The `time_column` for object store based Data Connectors (i.e. S3, Delta Lake) can now be set to `last_modified` which will add the last modified timestamp of the file as a column to the table. When combined with `refresh_mode: append`, Spice will now only load files that have been modified since the last time an acceleration was updated.
