### ISSUE TITLE
Bug: attempted to dereference shared_ptr that is NULL! (DuckDB acceleration)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4876]
## Describe the bug

>2025-02-25T21:53:22.449294Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset lineitem
libc++abi: terminating due to uncaught exception of type duckdb::InternalException: {"exception_type":"INTERNAL","exception_message":"Attempted to dereference shared_ptr that is NULL!","stack_trace_pointers":"4356465280;4356407652;4367556416;4367669164;4367695848;4362022196;4362251696;4362242744;4362239844;4362256472;4362262716;4358801020;4358730856;4358715668;4358714968;4358687372;4358708520;4358894948;4358903940;4358913576;4358951524;4371048760;4354883160;4354901944;4351342836;4349882840;4351309068;4452916860;4452877004;4452879320;4455788176;6450922212;6450901244"}
2025/02/25 13:53:40 ERROR error running Spice.ai error="os: process already finished"

## To Reproduce

```yaml
datasets:

- from: s3://spiceai-demo-datasets/tpch/lineitem/
    name: lineitem
    params:
      file_format: parquet
    acceleration:
      primary_key: "(l_linenumber, l_orderkey)"
      indexes:
        l_shipdate: enabled
        '(l_linenumber, l_orderkey)': enabled
      enabled: true
      mode: file
      engine: duckdb
      on_conflict:
        '(l_linenumber, l_orderkey)': upsert
```
