### ISSUE TITLE
Bug: `Current transaction is aborted (please ROLLBACK)` error during DuckDB acceleration

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4883]
## Describe the bug

>2025-02-26T18:39:36.998385Z  WARN runtime::accelerated_table::refresh_task: Failed to load data for dataset my_table (s3): Failed to get data from the connector.
External error: Unable to get appender to duckdb table: Current transaction is aborted (please ROLLBACK)

The error occurs when there is primary key an duckdb file acceleration.

```
 acceleration:
      enabled: true
      engine: duckdb
      primary_key: ColumnId
      on_conflict: 
        ColumnId: upsert
```

v1.0.4
