### ISSUE TITLE
Issue with embedding column with `from: memory:store`.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#4901]
## Describe the bug
Issue with writing to dataset `memory:store` when embedding column added. 

## To Reproduce
```shell
curl -XPOST http://127.0.0.1:8090/v1/tools/load_memory \
  -d '{"thoughts": ["foo", "bar"]}'
```
```shell
{
    "message": "Error calling tool store_memory: Schema mismatch: Expected and actual number of fields in the query result dont match: expected 5, received 4"
}
```

## Expected behavior
```shell
null
```

### Spicepod
```yaml

datasets:
  - from: memory:store
    name: llm_memory
    mode: read_write
    columns:
      - name: value
        embeddings:
          - from: xl_embed

embeddings:
  - from: openai:text-embedding-3-small
    name: xl_embed
    params:
      openai_api_key: ${ secrets:OPENAI_API_KEY }
```

## Additional context
 - `v1/sql` on dataset `memory:store` with embedding column is unaffected. i.e. appears to be a write specific problem.
