### ISSUE TITLE
Bug: pdf-extract `missing object reference: ObjectNotFound` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#4919]
## Describe the bug

>2025-03-06T01:18:32.290672Z  INFO runtime::accelerated_table::refresh_task: Loading data for dataset financial_data
thread 'tokio-runtime-worker' panicked at /Users/sg/.cargo/git/checkouts/pdf-extract-5dde1f8973a15145/3ca5e2c/src/lib.rs:176:52:
missing object reference: ObjectNotFound
2025-03-06T01:19:28.574981Z  WARN runtime::accelerated_table::refresh_task: Failed to load data for dataset financial_data (file): Failed to get data from the connector.
External error: Join Error
caused by
External error: task 581 panicked with message "missing object reference: ObjectNotFound"
Ensure the dataset configuration is valid, and try again.

## To Reproduce

Clone https://github.com/patronus-ai/financebench

Create Spicepod with the following dataset configuration 

```yaml
- from: file://pdfs
  description: Financial information
  name: financial_data
  params: 
    file_format: pdf
  acceleration: 
    enabled: true
    refresh_sql: |
      SELECT * FROM financial_data where financial_data.location LIKE '%3M%.pdf'
```
