### ISSUE TITLE
Enhancement: Iceberg Data Connector

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#4925]
## Goal-State/What/Result

An Iceberg dataset can be specified in the Spicepod YAML by putting a link to the table in the `from`, i.e.:

```yaml
datasets:
  - from: iceberg:https://iceberg-catalog-host.com/v1/namespaces/my_catalog/tables/my_table
    name: my_table
    params:
      <same as iceberg catalog>
```

## Why/Purpose

Allows customers the ability to accelerate Iceberg tables locally.

## By When

**Issue/Spec written and reviewed:** Fri Mar 7 2025
**Done-Done:** Monday Mar 10, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

Add an Iceberg Data Connector that takes the same parameters as the catalog connector and connects only to a single table.

### Security Review

No additional security scope.
