### ISSUE TITLE
Cannot define new table schema via views (only datasets).

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#4955]
## Describe the bug
 - User can define new schemas via dataset (i.e. `foo.sales`), but not views (i.e. `bar.sales`).
 - Get error:
    ```shell
    ERROR runtime::datafusion: Failed to create view: Error during planning: failed to resolve schema: bar
    ```

### Spicepod
```yaml
version: v1
kind: Spicepod
name: spicepoo

views:
  - name: bar.sales
    sql: SELECT * FROM foo.sales

datasets:
  - from: file:cleaned_sales_data.parquet
    name: foo.sales
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM foo.sales where msrp> 1000000 LIMIT 5
      engine: duckdb
      params:
        duckdb_file: ./duck.db
```
