### ISSUE TITLE
Bug: Invalid dataset configuration prevents future pods watcher updates

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5049]
## Describe the bug

Pods watcher has no currently logic to stop dataset loading retry and will keep try loading the dataset / new app w/o processing a new changes detected.

Options:
 - Add retry limit or timeout for Pods Watcher
 - Cancel in-progress update if new changes are detected (this can potentially result in an invalid state when the dataset has been partially loaded)

## To Reproduce

Add dataset that could not be loaded, for example:

```yaml
 - from: s3://spiceai-demo-datasets/taxi_trips/2026/
    name: taxi_trips
    description: taxi trips in s3
    params:
      file_format: parquet
```
