### ISSUE TITLE
DuckDB connector time out waiting on connection when accelerating multiple datasets

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#5074]
## Describe the bug

DuckDB time out waiting on connection when accelerating multiple datasets (30+), either causing failure of creating accelerator or failure in writing data.

Example errors:
```
2025-03-17T10:20:22.821943Z  WARN runtime::init::dataset: Failed to setup the dataset testdb_001_iceberg_table_012 (iceberg).
Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: DbConnectionError: DuckDB connection failed.
timed out waiting for connection
Adjust the DuckDB connection pool parameters for sufficient capacity.
```

```
Failed to load data for dataset customer_demographics (s3): Failed to get data from the connector.
External error: DbConnectionError: DuckDB connection failed.
timed out waiting for connection
Adjust the DuckDB connection pool parameters for sufficient capacity.
Ensure the dataset configuration is valid, and try again.
```

## To Reproduce

Use the following spicepod, run spice run and observe the `timeout waiting for connection` error from duckdb.

```yaml
version: v1beta1
kind: Spicepod
name: structured-output-sample

datasets:
  - from: s3://spiceai-public-datasets/tpch/customer/
    name: customer_tpch
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/lineitem/
    name: lineitem
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/nation/
    name: nation
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/orders/
    name: orders
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/part/
    name: part
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/partsupp/
    name: partsupp
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/region/
    name: region
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpch/supplier/
    name: supplier
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/call_center/
    name: call_center
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_page/
    name: catalog_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_returns/
    name: catalog_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/catalog_sales/
    name: catalog_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer_address/
    name: customer_address
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/customer_demographics/
    name: customer_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/date_dim/
    name: date_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/household_demographics/
    name: household_demographics
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/income_band/
    name: income_band
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/inventory/
    name: inventory
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/item/
    name: item
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/promotion/
    name: promotion
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/reason/
    name: reason
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/ship_mode/
    name: ship_mode
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store/
    name: store
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store_returns/
    name: store_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/store_sales/
    name: store_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/time_dim/
    name: time_dim
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/warehouse/
    name: warehouse
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_page/
    name: web_page
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_returns/
    name: web_returns
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_sales/
    name: web_sales
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-public-datasets/tpcds/web_site/
    name: web_site
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
