### ISSUE TITLE
iceberg-rust: Upstream fix for connecting to AWS Glue Iceberg REST Catalog API

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5104]
Upstream PR: https://github.com/apache/iceberg-rust/pull/917

**Comment by amitgilad3** [comment]
Hey @phillipleblanc  - i am trying to use your branch to connect to s3tables using the rest catalog api but i keep getting 

```
Context:
   code: 404 Not Found
   operation: auth
   url: https://glue.us-east-1.amazonaws.com/iceberg/v1/oauth/tokens
   json: <UnknownOperationException/>

```
im not sure why this is happening since in the python impl it works :/ 
any assistance would be appreciated.
