### ISSUE TITLE
Enhancement: Model graded Eval scorers.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#5113]
## Goal-State/What/Result
Spice supports running LLMs, evaluating LLMs, and provides several functions to the score the results of an eval run. Currently, users can not use an LLM to judge/score another LLMs eval ouput.

This enhancement is to add LLM-as-a-judge scoring natively, through spicepod model components.

## Why/Purpose
LLM scoring, or LLM-as-a-judge scorers (also called judge models in this enhancement) are a powerful way to measure certain characteristics of a LLM response that may be hard to codify in strict logic. They are also an effective way to capture the long tail of characteristics users want to measure.

## By When

**Issue/Spec written and reviewed:** 20th March
**Done-Done:** _Target Date_

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

### Requirements
 - Judge models will be defined as a model spicepod component.
 - There must be a mechanism to provide data from the eval dataset (minimally input, output, actual; but further to arbitrary columns in the dataset) into the model. Tangibly, this could be:
   - Templating of the system prompt. There is the open question for how this data would be provided via `chat/completions`. Current prototypes use the `metadata` field of the request payload.
      ```yaml
      models:
        - name: openai-with-spice
          from: openai:gpt-4o-2024-08-06
          params:
            parameterized_prompt: enabled # disabled
            system_prompt: |
              # Task
              Given an input prompt, you must evaluate the provided haiku and how well it describes {{ student.theme }}
              <poet>{{ input }}</poet>
              <research_artifacts>{{ actual }}</research_artifacts>
      ```
 - Need mechanism in `chat/completion` to provide data to model.
 - Need UX to know when to template `system_prompt` with data, vs current implementation.

### Implementation
 - Use `metadata` key in request payload for templating data. Any metadata provided can be used by templating.
 - Use `params.parameterized_prompt: enabled # disabled` to determine if templating should be attempted.
   - Security posture: No templating by default. 
 - Can check at startup if LLM has template variables in `system_prompt`. If so, when request metadata has these fields, template.
   - Question: Since we are not forcing the user to explicitly state a model should be templated, if we want to template initial user message, how do we know to do so, if metadata keys aren't used in system prompt.

### Security Review
 - Obvious concern is various forms of LLM prompt injection. At a minimum, system_prompt templating should not be default, but rather intentional choice by user. This risk of prompt injection also suggests we shouldn't allow for SQL or other tools in templating.

## Release Notes

<!--

Release notes for this enhancement, to be filled once completed. These release notes will be included as highlights on the next release.

Example:

## Release Notes

API Key Authentication: Spice now supports optional authentication for API endpoints via configurable API keys, for additional security and control over runtime access.

Example Spicepod.yml configuration:
```yaml
runtime:
  auth:
    api-key:
      enabled: true
      keys:
        - ${ secrets:api_key } # Load from a secret store
        - my-api-key # Or specify directly
```

Would be included on the next release like:

# Highlights in v1.0-rc.1

{other release note}

API Key Authentication: Spice now supports optional authentication for API endpoints via configurable API keys, for additional security and control over runtime access.

Example Spicepod.yml configuration:
```yaml
runtime:
  auth:
    api-key:
      enabled: true
      keys:
        - ${ secrets:api_key } # Load from a secret store
        - my-api-key # Or specify directly
```
