### ISSUE TITLE
spiceai connector `grpc: received message larger than max` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5143]
## Describe the bug

Unable to retrieve large spiceai dataset

>External error: Execution error: Query execution failed.
Tonic error: status: ResourceExhausted, message: "DoGet recv error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (150018393 vs. 104857600)", details: [], metadata: MetadataMap { headers: {} }
Verify the configuration and try again.
Ensure the dataset configuration is valid, and try again.

## To Reproduce

```yaml
  - from: spice.ai/spiceai/financebench/datasets/spice.financebench.data
    name: financebench.data
    description: Financial information
    params:
      spiceai_api_key: ${ secrets:SPICEAI_API_KEY }
      spiceai_endpoint: https://flight.spiceai.io
    acceleration:
      enabled: true
```
