### ISSUE TITLE
Enhancement: Add support for custom url to infer dataset schema (object store providers)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5172]
Add support for `schema_source_path` param that could be used to specify exact URL that should be used to infer dataset schema:
1. Faster dataset registration for large datasets  
1. Support scenarios when the last modified file (default schema inference approach) does not fully represent the target schema

Notes:  
 - When the schema infer parameter is specified, verification of the dataset location containing the provided file format via listing all objects is skipped. This is to support scenario 1 (avoid listing all objects).  
 - When the schema infer parameter is specified, all matched objects are used for schema inference, not only the last modified one from the path provided. This is to support scenario 2 above

Example Spicepod.yml configuration:

```yaml

- from: s3://spiceai-public-datasets/bucket/
  name: dataset2
  params:
    file_format: parquet
    schema_source_path: s3://spiceai-public-datasets/bucket/day=2024-01-10/ #or s3://spiceai-public-datasets/bucket/day=2024-01-10/data.parquet

- from: file:my_local_dataset/
  name: dataset1
  params:
    file_format: parquet
    schema_source_path: my_local_dataset/path/ # or my_local_dataset/path/data.parquet
```
