### ISSUE TITLE
SQL Query Fails with Multiple Subqueries and Query Aliases

### ISSUE THREAD

**Issue by boer0924** [spiceai/spiceai#5191]
When I execute this SQL on Spiced, I encounter the following error: `INVALID_ARGUMENT: No field named t.fac_name. Valid fields are t1.fac_name, t1.workshop_name, t1.workroom_name, t1.potno, t1.ddate, t1.temp.`
```sql
SELECT
    date_trunc ('YEAR', t1_ddate) AS date_trunc,
    ROUND(MAX(t1_temp), 2) AS value,
    t1_fac_name AS fac_name,
    t1_workshop_name AS workshop_name,
    t1_workroom_name AS workroom_name,
    t1_potno AS potno
FROM
    (
        SELECT
            t1.fac_name AS t1_fac_name,
            t1.workshop_name AS t1_workshop_name,
            t1.workroom_name AS t1_workroom_name,
            t1.potno AS t1_potno,
            t1.ddate AS t1_ddate,
            t1.workv AS t1_workv,
            t1.fe_rto AS t1_fe_rto,
            t1.temp AS t1_temp,
            t1.power_consum AS t1_power_consum,
            t1.tap AS t1_tap,
            t1.plan_tap_m AS t1_plan_tap_m,
            t1.plan_tap_d AS t1_plan_tap_d
        FROM
            (
                SELECT
                    fac_name,
                    workshop_name,
                    workroom_name,
                    potno,
                    ddate,
                    workv,
                    fe_rto,
                    temp,
                    power_consum,
                    tap,
                    plan_tap_m,
                    plan_tap_d
                FROM
                    source1900768068132974594_dwd_daytable_pg
            ) AS t1
    ) t
GROUP BY
    t1_fac_name,
    t1_workshop_name,
    t1_workroom_name,
    t1_potno,
    date_trunc ('YEAR', t1_ddate);
```
This SQL executes successfully on PostgreSQL.

But I found that DataFusion has already fixed the related issue.
https://github.com/apache/datafusion/pull/15068

**Comment by phillipleblanc** [comment]
Thanks for reporting @boer0924, this will likely be fixed when we upgrade DataFusion to a version that includes this fix.

**Comment by phillipleblanc** [comment]
Looks like this will be released in DF 47

**Comment by sgrebnov** [comment]
Confirmed that previously failing queries (below) now works (the fix will be available in Spice v1.4.0)

```yaml
version: v1
kind: Spicepod
name: test_unparser

datasets:
  - from: s3://spiceai-demo-datasets/tpch/customer/
    name: customer
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file

  - from: s3://spiceai-demo-datasets/tpch/orders/
    name: orders
    params:
      file_format: parquet
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
```

```sql
SELECT
    DATE_TRUNC('YEAR', t1_o_orderdate) AS order_year,
    ROUND(MAX(t1_o_totalprice), 2) AS max_totalprice,
    t1_o_orderpriority AS order_priority,
    t1_o_orderstatus AS order_status
FROM (
    SELECT
        t1.o_orderdate AS t1_o_orderdate,
        t1.o_totalprice AS t1_o_totalprice,
        t1.o_orderpriority AS t1_o_orderpriority,
        t1.o_orderstatus AS t1_o_orderstatus
    FROM (
        SELECT
            o_orderdate,
            o_totalprice,
            o_orderpriority,
            o_orderstatus
        FROM orders
    ) AS t1
) t
GROUP BY
    t1_o_orderpriority,
    t1_o_orderstatus,
    DATE_TRUNC('YEAR', t1_o_orderdate);
```

```sql
SELECT
  customer_view.c_custkey,
  customer_view.c_name,
  customer_view.custkey_plus
FROM (
  SELECT
    customer.c_custkey,
    customer.c_name,
    customer.custkey_plus
  FROM (
    SELECT
      customer.c_custkey,
      CAST(customer.c_custkey AS BIGINT) + 1 AS custkey_plus,
      customer.c_name
    FROM (
      SELECT
        c_custkey,
        c_name
      FROM customer
    ) AS customer
  ) AS customer
) AS customer_view;

```
