### ISSUE TITLE
Spicepod changes to allow metrics to be exposed from components.

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5288]
```yaml
datasets:
  - from: mysql:table
    name: my_table
    metrics:
      - name: some_metric
         enabled: true
```
