### ISSUE TITLE
Bug: Iceberg Catalog should respect `include` parameter

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5314]
## Describe the bug

```yaml
catalogs:
  - from: iceberg:https://glue.ap-northeast-2.amazonaws.com/iceberg/v1/catalogs/.../namespaces
    name: ice_glue
    include: 
        - "testdb_001.*"
    params: 
      iceberg_s3_region: ap-northeast-2
      iceberg_s3_access_key_id: ${ env:AWS_ICEBERG_ACCESS_KEY_ID }
      iceberg_s3_secret_access_key: ${ env:AWS_ICEBERG_SECRET_ACCESS_KEY 
```

![Image](https://github.com/user-attachments/assets/7f3460ea-71b4-4bde-8572-f8dd3f9c8e2d)
