### ISSUE TITLE
Bug: LLM eval score `Expected a string with maximum length 512` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5357]
>Expected a string with maximum length 512, but got a string with length 695 instead. (param: metadata.actual) (code: string_above_max_length)","scorers":["judge"],"metrics":{}}]%   

```yaml
datasets:
  - from: file:spicepods/evals/evals.jsonl
    description: Dataset for evaluating model performance. Must be ignored by the model.
    name: evals
    acceleration:
      enabled: true

evals:
  - name: evals
    dataset: evals
    scorers:
      - judge

models:
  - name: judge
    from: openai:gpt-4o
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
      parameterized_prompt: enabled
      system_prompt: |
        Score between 0.0 and 1.0 correctness of answer to the following question:
        Question: {{ .input }}
        Correct Answer: {{ .ideal }}
        Answer to score: {{ .actual }}
      openai_response_format:
        type: json_schema
        json_schema:
          name: judge
          schema:
            type: object
            properties:
              score:
                type: number
                format: float
            additionalProperties: true
            required:
              - score
        strict: false
```
