### ISSUE TITLE
Bug: `Underlying language model produced no score in response` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5394]
## Describe the bug

There is the following error when I use model scorer

```bash
curl -XPOST "http://localhost:8090/v1/evals/financebench" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-4o"
  }'
[{"id":"ef86182525936e6dbd4d5a46bcd222f5","created_at":"2025-04-15T20:10:18","dataset":"financebench.evals","model":"gpt-4o","status":"Failed","error_message":"An error occured whilst scoring the results of the eval run. Scorer failed: judge - Could not score case [input=UserInput(\"What is the FY2019 fixed asset turnover ratio for Activision Blizzard? Fixed asset turnover ratio is defined as: FY2019 revenue / (average PP&E between FY2018 and FY2019). Round your answer to two decimal places. Base your judgments on the information provided primarily in the statement of income and the statement of financial position.\"), actual=AssistantResponse(\"I could not retrieve specific financial data for Activision Blizzard for FY2019, including revenue and PP&E values. Therefore, I am unable to calculate the fixed asset turnover ratio for FY2019.\"), expected=AssistantResponse(\"24.26\")]. Error: Underlying language model produced no score in response","scorers":["judge"],"metrics":{}}]%  
```

## To Reproduce

```
- name: judge
    from: openai:gpt-4o
    params:
      openai_api_key: ${ secrets:SPICE_OPENAI_API_KEY }
      parameterized_prompt: enabled
      system_prompt: |
        You are a financial domain expert acting as a **scorer** to evaluate the **correctness and quality** of a generated response from a Retrieval-Augmented Generation (RAG) system.

        You are provided with:
          - A **User Question**.
          - A **Reference Answer**, which is the correct and complete response.
          - A **Generated Answer**, produced by the RAG model.

        Your evaluation should focus on:
          1. **Correctness**: Does the generated answer contain accurate factual information based on the question and context?
          2. **Completeness**: Does it address all relevant aspects of the question?
          3. **Relevance**: Is the information included pertinent and within scope?
          4. **Faithfulness**: Is the content grounded in the retrieved documents and avoids hallucination or fabrication?
          5. **Clarity**: Is the reasoning clear and coherent (when applicable)?

        Specific evaluation guidance:
          - For **numerical answers**, check precision, rounding, and if values match the correct source.
          - For **qualitative assessments**, check whether the rationale is logically sound and factually grounded.
          - For **financial metrics**, ensure the definitions used are consistent with industry standards.
          - If **citations or justifications** are included, confirm that they are relevant and accurate.
          - Penalize **hallucinated or extraneous** details, even if minor.

        Scoring:
          - Assign a score between **0 and 1**, where:
            - **1.0**: Perfect — fully correct, relevant, faithful
            - **0.0**: Couldn't find information or rejected to answer,
            - **0.0**: Entirely incorrect, misleading, or fabricated.
            - Use intermediate values (e.g., 0.6, 0.8) to reflect partial correctness.

        You must **only output** the result as a JSON object, no commentary or explanation.

        # User Question:
        {{ input }}

        # Reference Answer:
        {{ ideal }}

        # Generated Answer:
        {{ actual }}

      openai_response_format:
        type: json_schema
        json_schema:
          name: judge
          schema:
            type: object
            properties:
              score:
                description: >
                  The score assigned to the actual answer based on the evaluation criteria.
                type: number
                format: float
            additionalProperties: true
            required:
              - score
        strict: true
```
