### ISSUE TITLE
Reported user issue with Parasail

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#5418]
```yaml
models:
  - from: openai:cloud-sambanova-llama-3-70b-instruct
    name: oai
    params:
      openai_api_key: ${ secrets:SPICE_PARASAIL_API_KEY }
      endpoint: https://api.parasail.io/v1
```

On startup, loading model fails because of `"created":1744857525.254391`. This is OpenAI [spec](https://platform.openai.com/docs/api-reference/chat/object) incompatible which expects an integer.
```
2025-04-17T02:38:45.341397Z ERROR async_openai::error: failed deserialization of: 
{
  "choices": [
    {
      "finish_reason":"stop",
      "index":0,
      "logprobs":null,
      "message": { 
        "content":"A",
        "role":"assistant"
      }
    }
  ],
  "created":1744857525.254391,
  "id":"7ab7172c-9166-451d-be98-49e84d824a8d",
  "model":"cloud-sambanova-llama-3-70b-instruct",
  "object":"chat.completion",
  "system_fingerprint":"fastcoe",
  "usage": {
    "completion_tokens":1,
    "completion_tokens_after_first_per_sec":0,
    "completion_tokens_after_first_per_sec_first_ten":0,
    "completion_tokens_per_sec":14.361300572492947,
    "end_time":1744857525.2543614,
    "is_last_response":true,
    "prompt_tokens":49,
    "start_time":1744857525.1847298,
    "stop_reason":"stop",
    "time_to_first_token":0.052271366119384766,
    "total_latency":0.06963157653808594,
    "total_tokens":50,
    "total_tokens_per_sec":718.0650286246473
}}
```
