### ISSUE TITLE
Enhancement: Databricks Model Provider

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#5428]
## By When

**Issue/Spec written and reviewed:** _Target Date_
**Done-Done:** _Target Date_

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

**Comment by Jeadie** [comment]
No cookbook will be made. Benchmarks and tests won't be added as Databricks cannot even satisfy Alpha. 

PM/Design in https://github.com/spiceai/spiceai/pull/5434. PR approved by Luke. 

Docs Done [#955](https://github.com/spiceai/docs/pull/955)

Release notes


----
## Highlights v1.2.0

- **Databricks AI Models**:  Connect to LLMs running on Databricks AI serving endpoints. 

```yaml
models:
  - from: databricks:llama_70B
    name: my_model
    params:
      databricks_endpoint: dbc-46420123-42e5.cloud.databricks.com
      databricks_token: ${ secrets::SPICE_DATABRICKS_TOKEN }
```
