### ISSUE TITLE
Bug: OpenAI o3 `stream failed: Invalid status code: 400 Bad Request` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5432]
## Describe the bug

```yaml
models:

  - name: o3
    from: openai:o3-2025-04-16
    params:
      tools: list_datasets, table_schema, document_similarity
      openai_api_key: ${ secrets:OPENAI_API_KEY}
      system_prompt: *model_system_prompt
```

>Using model: o3
chat> Test
⣻ 2025/04/17 22:06:36 ERROR chat request failed error="stream failed: Invalid status code: 400 Bad Request"

https://platform.openai.com/docs/models/o3

## To Reproduce

2025-04-18T05:06:31.112920Z  INFO runtime::init::model: Model [o3] deployed, ready for inferencing
2025-04-18T05:06:31.761491Z  INFO runtime: All components are loaded. Spice runtime is ready!
2025-04-18T05:06:36.329065Z ERROR runtime::http::v1::chat: Error encountered in chat completion stream: stream failed: Invalid status code: 400 Bad Request
