### ISSUE TITLE
Enhancement: Ensure all Databricks connectors support M2M auth with User-Agent

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#5467]
## Goal-State/What/Result

Support: https://docs.databricks.com/aws/en/dev-tools/auth/oauth-m2m. Databricks datasets and catalogs connectors and models provider can be configured with service principal credentials: client id and client secret, and runtime will automatically handle token refresh.

```yaml
datasets:
  - from: databricks:spiceai_sandbox.default.messages
    name: messages
    params:
        databricks_endpoint: ${secrets:DATABRICKS_ENDPOINT}      # required for M2M auth
        databricks_cluster_id: ${secrets:DATABRICKS_CLUSTER_ID}  # required for M2M auth
        databricks_client_id: ${secrets:DATABRICKS_CLIENT_ID}    # required for M2M auth
        databricks_client_secret: ${secrets:DATABRICKS_CLIENT_SECRET}
```

Databricks connectors support passign down User-Agent string form the runtime:
- [spark connect](https://github.com/apache/spark/blob/master/sql/connect/docs/client-connection-string.md)
- Databrics catalog API, Auth API - in headers

User agent can be specified by separate optional param `databricks_user_agent: <value>`

## Why/Purpose

Databricks PAT will soon be deprecated. Tokens will have a short lifespan, rendering our current Databricks connector unusable. The M2M OAuth flow is the most suitable and straightforward solution and will be the default method for setting up connections.

## By When

**Issue/Spec written and reviewed:** Apr 21
**Done-Done:** Apr 25

## Principles

- Secure by default
- Developer experience first
- Align to industry standards

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

New parameters:

- `databricks_client_id` - Databricks service principal client id
- `databricks_client_secret` - Databricks service principal client secret

To use M2M auth, user will need to specify service principal credentials and `databricks_endpoint` parameter, which will be used to generate workspace-level acces token. ([docs](https://docs.databricks.com/aws/en/dev-tools/auth/oauth-m2m?language=Environment#manually-generate-a-workspace-level-access-token))

Databricks M2M token response includes following fields:
```json
{
  "access_token": "eyJraWQ...72Q",
  "scope": "all-apis",
  "token_type": "Bearer",
  "expires_in": 3600
}
```

When configured with SP credentials, the Databricks connector will obtain a token and schedule a refresh 5 minutes before it expires. The new token is passed to the Spark connector instance to recreate and rotate the session.

A `DatabricksTokenProvider` will be added, which will implement the [`TokenProvider` trait](https://github.com/spiceai/spiceai/blob/e07d181c6dbebe3f152253de592da58b0f8f1c0b/crates/data_components/src/token_provider.rs#L33-L36) to handle token generation.

M2M Auth will be implemented for both Databricks data and catalog connectors, in Delta and Spark connect modes.

### Security Review

**Secure by default** - Additional credentials will be stored in secrets. The `DatabricksTokenProvider` should use `secrecy::SecretString` for token value.

### QA

- [x] Add integration tests for Databricks dataset and catalog connectors

## Release Notes

Databricks M2M OAuth support: SpiceAI now supports M2M authentication for Databricks using Service Principal credentials, enhancing security and access control. This includes Databricks dataset and catalog connectors using Spark Connect and Delta Lake modes, as well as the Databricks models provider.

Example Spicepod.yml configuration:
```yaml
datasets:
  - from: databricks:spiceai_sandbox.default.messages
    name: messages
    params:
        databricks_endpoint: ${secrets:DATABRICKS_ENDPOINT}
        databricks_cluster_id: ${secrets:DATABRICKS_CLUSTER_ID}
        databricks_client_id: ${secrets:DATABRICKS_CLIENT_ID}
        databricks_client_secret: ${secrets:DATABRICKS_CLIENT_SECRET}
```
