### ISSUE TITLE
DuckDB accelerator panics during Ctrl+C shutdown

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#5519]
## Describe the bug

When shutting down during acceleration to DuckDB, from an S3 source, the Runtime throws several panics:

```console
2025-04-24T03:48:02.084768Z  INFO runtime: Goodbye!
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.10.0/src/bytes.rs:390:9:
range start must not be greater than end: 6288000 <= 6223151
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.10.0/src/bytes.rs:390:9:
range start must not be greater than end: 6276810 <= 5457045
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.10.0/src/bytes.rs:390:9:
range start must not be greater than end: 2457502 <= 2041023
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.10.0/src/bytes.rs:390:9:
range start must not be greater than end: 2456532 <= 1965821
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.10.0/src/bytes.rs:390:9:
range start must not be greater than end: 1577039 <= 1514869
spiced: /home/runner/_work/spiceai/spiceai/bin/spiced/../../target/release/build/libduckdb-sys-811795cc396e7805/out/duckdb/src/storage/buffer/block_manager.cpp:45: duckdb::shared_ptr<duckdb::BlockHandle> duckdb::BlockManager::ConvertToPersistent(duckdb::block_id_t, duckdb::shared_ptr<duckdb::BlockHandle>): Assertion `new_block->state == BlockState::BLOCK_UNLOADED' failed.
2025/04/24 03:48:05 ERROR error running Spice.ai error="signal: aborted (core dumped)"
```

## To Reproduce

_Steps to reproduce the behavior:_

1. Configure a SF100 TPCH dataset accelerated to DuckDB from S3
2. Ctrl+C shutdown during acceleration
3. Observe panics

## Expected behavior

The runtime should not panic and should shutdown successfully

### Spicepod

```yaml
version: v1
kind: Spicepod
name: s3[parquet]-federated
datasets:
  - from: s3://benchmarks/tpch_sf100/customer.parquet
    name: customer
    params: &s3_params
      file_format: parquet
      allow_http: true
      s3_auth: key
      s3_endpoint: ${secrets:S3_ENDPOINT}
      s3_key: ${secrets:S3_KEY}
      s3_secret: ${secrets:S3_SECRET}
    acceleration: &acceleration
      enabled: true
      engine: duckdb
      mode: file
  - from: s3://benchmarks/tpch_sf100/lineitem.parquet
    name: lineitem
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/nation.parquet
    name: nation
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/orders.parquet
    name: orders
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/part.parquet
    name: part
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/partsupp.parquet
    name: partsupp
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/region.parquet
    name: region
    params: *s3_params
    acceleration: *acceleration
  - from: s3://benchmarks/tpch_sf100/supplier.parquet
    name: supplier
    params: *s3_params
    acceleration: *acceleration
```
