### ISSUE TITLE
`table` protected SQL word

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#5532]
## Describe the bug
The dataset name `table` appears to be a protected word, but this is not clear from error message. 

## To Reproduce
```yaml
datasets:
  - from: snowflake:SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER
    name: table
    params:
      ...
```

```bash
>>> spice sql
sql> select count(1) from table;
Query Error: Expected: (, found: ;
```
