### ISSUE TITLE
Subsequent `refresh_sql` changes doesn't affect existing file-based DuckDB accelerated table

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#5534]
## Describe the bug
 On existing file-based DuckDB accelerated table, changing the `refresh_sql` after it was used to create the initial DuckDB table, doesn't reinitialise the table in the accelerated DuckDB. 

## To Reproduce
```yaml
datasets:
  - from: <Any table> 
    name: customer
    acceleration:
      enabled: true
      engine: duckdb
      mode: file
        # 1. refresh_sql: SELECT col1, col2 FROM customer LIMIT 1000; -- This is the refresh SQL that instantiated the DB. 
        # 2. refresh_sql: SELECT col1, col2 FROM customer LIMIT 5000; -- This still has only 1000 rows. 
      refresh_sql: SELECT col1 FROM customer WHERE C_NATIONKEY = 10 LIMIT 5000; # Projection change is available, but WHERE clause is not. 
      params:
        duckdb_file: /Users/jeadie/Github/spiceai/quack.db
        duckdb_memory_limit: "10GB"
```
