### ISSUE TITLE
Rearchitect worker paradigm to be broader than routing models.

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#5556]
Workers in the Spice runtime represent configurable units of compute. There are several types of workers, of which, the type will fufill one or more possible traits (e.g. being callable like an LLM, is a trait).

**Definitions**
 - Worker: A spice component that encapsulates and organises configurable unit(s) of compute.
 - Worker Compute: A standalone spice component, self sufficient (i.e. can be used in its own right; has its own traits)
   - e.g: An LLM, a tool, code-running compute.
 - Worker Type: Determines how the worker can be configured, and what subset of compute traits are applicable.
   - e.g:
 - Compute Traits: Define how a worker component can be interacted with. All workers implement a worker trait that allows for basic introspection (e.g. CRUD of workers).
   - e.g. being callable like an LLM,

TODO: use retryable as trait for > worker types (separate for routing).

### YAML UX
```yaml
workers:
 - name: <string>
   type: <string>
   description: <String>
   params: <map[string]string; needed to instantiate the worker, independent of trait-level configuration>
   trait_x: <map[string]string; (optional) additional configuration of `worker_type` to implement `trait_x`. Specification should depend on `trait_x`, not `worker_type`.
   trait_y: <see `trait_x`>
```

#### YAML example: LLM Load-balancing
```yaml
workers:
  - name: a_b_llms
    type: load_balance
    description: |
      Ensure 80% of requests go to 'foo' and 20% go to 'bar'.
    load_balance:
      routing:
        - model: foo
          weight: 4
        - model: bar
          weight: 1
    retry: # retry is a trait implementable by any worker.
      max_attempts: 3
      back_off: fibonacci
      initial_backoff: 3s
```

#### YAML example: LLM postprocess (in code)
```yaml
# Assume some code running spice component definition.
code:
  - name: pythonner
    from: wasm:internal # Run code internally in Spice WASM runner.

workers:
  - name: email_sender
    type: postprocess # This type runs: `LLM -> code`.
    description: |
      This worker implements:
        - Chat completion API (output of code function returned in response payload).
    retry:
      # This will retry the whole flow.
      # To retry either the python code, or the LLM model separately, add retry to their workers.
      max_attempts: 1
      back_off: fibonacci
      initial_backoff: 3s
    model:
      # This section could configure anything pertaining to how `email_sender` acts as an LLM.
    postprocess:
      model: a_b_llms
      runner: pythonner
      code: | # or `code_ref: ./main.py`
        from openai.types.chat import ChatCompletion

        def process(resp: ChatCompletion) -> String:
            sms_content: Option[str] = resp.choices[0].message.content
            if sms_content is None:
                return "Model produced no content. No SMS sent"

            if resp.labels['recipient_phone_number'] is None:
                return "Recipient's phone number was not provided. Non SMS sent."

            try:
                client =  Client(environ['TWILIO_ACCOUNT_SID'], environ['TWILIO_AUTH_TOKEN'] )
                message = client.messages.create(
                    body=sms_content,
                    from_=environ['TWILIO_PHONE_NUMBER'],
                    to=resp.labels['recipient_phone_number']
                )

                print(f"Message sent successfully! SID: {message.sid}")
            except Exception as e:
                print(f"Error sending SMS: {e}")
```

#### YAML example: Multi-LLM coordination.
```yaml
workers:
  - name: email_sender
    type: orchestrator
    description: |
      Handles piping between models.
    orchestrator:
    #            +--- model_b ---+
    #  req --> model_a         model_d --> resp
    #            +--- model_c ---+
      - name: model_a
      - name: model_b
        from: model_a
      - name: model_c
        from: model_a
      - name: model_d
        from:
          # Can combine JSONs. :
          # {
          #   "company_research": <output of model_b>,
          #   "government_research": <output of model_c>
          #  }
          - source: model_b
            alias: company_research
          - source: model_c
            alias: government_research
```

### HTTP API v1/workers
Update HTTP response 

`.data[].is_llm` denotes if the worker can be used interchangeably with defined LLMs (e.g. `v1/chat/completions`). 

```diff
{
    "object": "list",
    "data": [
        {
            "name": "round-robin",
            "description": "Distributes requests between foo and bar models in a round-robin fashion.\n",
            "type": "load_balance",
+            "is_llm": true
-            "models": ["foo", "bar"]
        }
    ]
}
```
