### ISSUE TITLE
Bug: `Lru cache: Failed to convert query result size to u32: out of range integral type conversion attempted`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5652]
## Describe the bug

There is the following error with cache size set to 6144MiB. Cache itself works and I can see cached values returned.

```yaml
runtime:
    results_cache: # Optional. Cache results for faster subsequent queries
      enabled: true
      cache_max_size: 6144MiB
      item_ttl: 300s
```

>2025-05-01T02:16:14.358255Z  WARN cache::lru_cache: Lru cache: Failed to convert query result size to u32: out of range integral type conversion attempted
