### ISSUE TITLE
Enhancement: Metadata columns for object-store based data connectors

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5657]
## Goal-State/What/Result

Configure object-store based data connectors (i.e. s3, file) to expose metadata columns as queryable columns in the dataset.

The metadata columns are enabled by setting their name to `enabled` in the `metadata` section. The following metadata columns are available:
- `location`
- `last_modified`
- `size`

```yaml
datasets:
  - from: s3://spiceai-public-datasets/table1
    name: table1
    params:
      file_format: parquet
    metadata:
      location: enabled
      last_modified: enabled
      size: enabled
```

## Why/Purpose

Allows efficient SQL queries on specific files based on their metadata.

## By When

**Issue/Spec written and reviewed:** May 1, 2025
**Done-Done:** May 1, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

Use the above Spicepod mapping to enable the underlying metadata columns on the listing table provider configuration.

### Security Review

No security impact.

## QA Plan

Integration tests
