### ISSUE TITLE
Enhancement: cron based refresh schedule support

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5683]
## Goal-State/What/Result

Accelerated datasets can be refreshed via a cron schedule, which sequentially refreshes datasets.

Workers also support refreshes via cron schedule, and execute based on the defined prompt parameter.

## Why/Purpose

To minimize the load impact of refreshing datasets by scheduling at off-peak hours, and to schedule automatic model updates on refreshed data.

## By When

**Issue/Spec written and reviewed:** 20th May, 2025
**Done-Done:** 26th May, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

* The spicepod specification for `datasets.acceleration` is updated to include `refresh_cron` which specifies a cron schedule to execute a scheduled refresh:

```yaml
datasets:
  - name: my_dataset
    from: s3://my-bucket/my_file.parquet
    acceleration:
      refresh_cron: 0 0 * * * # Daily refresh at midnight
```

* The spicepod specification for `datasets.acceleration` is updated to include `refresh_cron` which specifies a cron schedule to execute a scheduled refresh:

```yaml
datasets:
  - name: my_dataset
    from: s3://my-bucket/my_file.parquet
    acceleration:
      refresh_cron: 0 0 * * * # Daily refresh at midnight
```

Refreshes initiated by cron schedules respect the `dataset_refresh_parallelism`. For datasets containing the same refresh schedule, they are queued to refresh ordered by dataset name.

`refresh_cron` is mutually exclusive with `refresh_check_interval` - only one of each parameter can exist on the same acceleration, but not both. Dataset validation should error when both parameters exist.

* The spicepod specification for `workers` is updated to include a `cron` parameter, and a `params.prompt` parameter. When triggered via a schedule, the worker will execute with the specified prompt:

```yaml
workers:
  - name: email_reporter
    models:
      - from: gpt-4o
    params:
      prompt: "Inspect the latest emails, and generate a summary report for them. Post the summary report to the connected Teams channel"
    start_cron: 0 2 * * * # Daily at 2am
```

### Security Review

* There is a potential security impact if a user supplies a malicious or improper cron expression, causing excessive expression evaluations resulting in high dataset refresh load or model calls.
  * This risk can be mitigated my implementing a minimum expression evaluation period. For example, evaluating cron expressions only every minute. This would prevent cron expressions set to excessive intervals like `* * * * *` from running any faster than 1 minute.
* Specifying a model prompt to be executed on a schedule inside the `spicepod.yml` could expose the system to privilege escalation by a malicious prompt
  * Users should ensure strict access controls to the `spicepod.yml` file, preventing access from unauthorised users.
  * The Spice Runtime should run with minimum access, as a user account with low privileges and minimal access to files.

## How/Implementation Plan

A scheduler architecture for scheduling tasks across the Runtime shall be implemented, initially focusing on replacing the existing control architecture for accelerated dataset refresh tasks. The final control flow would look like the following mermaid chart:

![Image](https://github.com/user-attachments/assets/44b2bb87-d02e-4c5c-bd27-a44c05215a0a)

As an M1 milestone, this task will implement the scheduler up to but excluding retry strategies and parallelism controls. At the completion of this task:

1. The `scheduler` will support cron-based schedules, as well as interval expressions and manual interrupts (e.g. on-demand refreshes)
2. The `scheduler` will support cancellation of running tasks, and archiving items from the queue
3. The `scheduler` will support tracing with accurate parent spans, to track events that the scheduler invokes
4. A `scheduler` can be created from the Runtime, to run dataset acceleration refresh tasks as well as worker invocations

## QA Plan

* An integration test utilising a cron refresh schedule is created, to test refresh behavior with a changing dataset source on a 2 minute schedule (`*/2 * * * *`). The dataset row count should be checked before and after one refresh to confirm a dataset refresh occurred.
* An integration test utilising a cron worker schedule is created, to test worker execution behavior on a 2 minute schedule (`*/2 * * * *`). The schedule runs twice in the test, confirming the task history of the chat completion for both executions.

## Release Notes

* **Cron Scheduled Refresh for Datasets and Workers:** Spice now supports cron-based scheduling for both dataset refreshes and worker executions, enabling hands-free automation of periodic tasks.

**Dataset Refresh Schedules:**

Accelerated datasets now support a `refresh_cron` parameter, automatically refreshing the dataset on a defined cron schedule. Cron-based scheduled refreshes respect the global `dataset_refresh_parallelism` parameter, and datasets with identical refresh schedules are queued and refreshed in alphabetical order by name.

Example `spicepod.yml` configuration:

```yaml
datasets:
  - name: my_dataset
    from: s3://my-bucket/my_file.parquet
    acceleration:
      refresh_cron: 0 0 * * * # Daily refresh at midnight
```

**Worker Execution Schedules:**

Workers now support a `cron` parameter, and in conjunction with the provided `params.prompt` will execute automatically on the defined cron schedule.

Example `spicepod.yml` configuration:

```yaml
workers:
  - name: email_reporter
    models:
      - from: gpt-4o
    params:
      prompt: "Inspect the latest emails, and generate a summary report for them. Post the summary report to the connected Teams channel"
    cron: 0 2 * * * # Daily at 2am
```

For more details, refer to the [Scheduling documentation](#)
