### ISSUE TITLE
Enhancement: Glue Catalog Connector for Iceberg + Hive-style Parquet (Beta)

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5690]
## Goal-State/What/Result

A Glue-native Catalog Connector that can load Iceberg + Hive-style Parquet tables

## Why/Purpose

Part of our stated Roadmap: https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md

## By When

**Issue/Spec written and reviewed:**May 29, 2025
**Done-Done:** June 8, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

```yaml
catalogs:
  - from: glue # endpoint not needed; each AWS account has one AWS Glue Data Catalog per AWS region
    name: glue_catalog # catalog name within Spice
    params:
      glue_key: <your-access-key-id>
      glue_secret: <your-secret-access-key>
      glue_region: <your-region>
    include:
      - 'database1.table_*' # Include tables matching the pattern from database1
      - 'database2.*'       # Include all tables from database2
```

### Security Review

The same authentication mechanisms used with other AWS data connectors are used in this catalog provider.

## How/Implementation Plan

- Implement the following traits in a new `crates/runtime/src/catalogconnector/glue.rs` module:
  - `CatalogConnector`
  - `CatalogProvider`
  - `SchemaProvider`
  - `RefreshableCatalogProvider`
- Use `aws_sdk_glue` crate to interface with the Glue API.
- Use `iceberg` and `iceberg-datafusion` crates to interface with Iceberg tables
- Use the existing S3 data connector to interface with Hive-style parquet files

## QA Plan

- Add integration tests
  - Read from Iceberg table
  - Read from Hive-style parquet table
  - Query using both Iceberg and Hive-style parquet tables

## Release Notes

**AWS Glue Catalog Connector**: Connect to the AWS Glue Data Catalog to access and query Iceberg tables or tables using parquet or CSV data formats in S3.

Example `spicepod.yaml`:

```yaml
catalogs:
  - from: glue
    name: my_glue_catalog
    params:
      glue_key: <your-access-key-id>
      glue_secret: <your-secret-access-key>
      glue_region: <your-region>
    include:
      - 'testdb.hive_*'
      - 'testdb.iceberg_*' 
```

```sql
sql> show tables;
+-----------------+--------------+-------------------+------------+
| table_catalog   | table_schema | table_name        | table_type |
+-----------------+--------------+-------------------+------------+
| my_glue_catalog | testdb       | hive_table_001    | BASE TABLE |
| my_glue_catalog | testdb       | iceberg_table_001 | BASE TABLE |
| spice           | runtime      | task_history      | BASE TABLE |
+-----------------+--------------+-------------------+------------+
```
