### ISSUE TITLE
Bug: Iceberg Table Provider does not reflect new data after append on Iceberg table

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5697]
## Describe the bug

Start Spice with a dataset that loads an Iceberg table:

```yaml
datasets:
  - from: iceberg:https://glue.ap-northeast-2.amazonaws.com/iceberg/v1/catalogs/211125479522/namespaces/security_logs/tables/audit_log
    name: audit_log
    params:
      iceberg_s3_region: ap-northeast-2
      iceberg_s3_access_key_id: ${ secrets:AWS_ACCESS_KEY_ID }
      iceberg_s3_secret_access_key: ${ secrets:AWS_SECRET_ACCESS_KEY }
      iceberg_s3_role_arn: ${ secrets:AWS_ROLE_ARN }
```

Load additional data into the Iceberg table. Try querying for that new data in Spice and see it doesn't exist. Restart Spice and observe the data is now present.
