### ISSUE TITLE
Unable to load databricks chat models from serving endpoints

### ISSUE THREAD

**Issue by avivshafir** [spiceai/spiceai#5751]
Failed to load model meta-llama-3_3_70b_instruct from spicepod.
Unable to determine model type. Verify the model source and try again.

spicepod.yaml:

```
models:
  - from: databricks:meta-llama-3_3_70b_instruct
    name: llama-70b
    params:
      databricks_endpoint: <my_endpoint>
      databricks_token: <my_token>
```

I tried several models such as claude-3_7-sonnet as well.

I'm running spice.ai version 1.2.1
