### ISSUE TITLE
Enhancement: Databricks Connector SQL API support

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#5754]
## Goal-State/What/Result

The [Databricks Data Connector](https://docs.spiceai.org/data-connectors/databricks) can use the [Databricks SQL Statement Execution API](https://docs.databricks.com/aws/en/dev-tools/sql-execution-tutorial?language=curl#step-1-execute-a-sql-statement-and-save-the-data-result-as-json)

## Why/Purpose

Spice can run SQL statements to access Databricks data and retrieve results without the need to install database drivers or manage persistent connections.

## By When

**Issue/Spec written and reviewed:** May 12, 2025
**Done-Done:** May 14, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials
- [x] Release Notes prepared

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Databricks SQL Execution API example

```yaml
datasets:
  - from: databricks:spiceai.datasets.my_awesome_table 
    name: my_awesome_table
    params:
      mode: sql_warehouse # | spark_connect | delta ; new parameter variant
      databricks_endpoint: dbc-a1b2345c-d6e7.cloud.databricks.com
      databricks_sql_warehouse_id: 1234-567890-abcde123 # new parameter
      databricks_token: ${secrets:DATABRICKS_TOKEN} # PAT
```

> DATABRICKS_SQL_WAREHOUSE_ID, representing the ID of your Databricks SQL warehouse. This ID is the string of letters and numbers following /sql/1.0/warehouses/ in the HTTP path field for your warehouse. To learn how to get your warehouse's HTTP path value, see [Get connection details for a Databricks compute resource](https://docs.databricks.com/aws/en/integrations/compute-details).

### Security Review

- Follow the [security best practices](https://docs.databricks.com/aws/en/dev-tools/sql-execution-tutorial#security-best-practices)
- Uses the same currently established authentication mechanisms (PAT or M2M OAuth) https://spiceai.org/docs/components/data-connectors/databricks#authentication

## How/Implementation Plan

- Add support for new mode name and parameters in the Spicepod configuration
- Add an additional Rust module to `crates/data_components/src/databricks/mod.rs` called `sql_statement_execution`
- Create a `struct SqlStatementExecution` and `impl data_components::Read` for it.
- `impl TableProvider`
- `impl ExecutionPlan`
- use `reqwest` crate to make network requests.
- Handle timeouts by refetching the in progress query
- Handle request cancelling if spicepod gets interrupted.

## QA Plan

Ensure that the same [cookbook](https://github.com/spiceai/cookbook/tree/trunk/databricks) used to test the other modes (delta_lake and spark) can be used via the new SQL Statement Execution API mode.

## Release Notes

**Databricks SQL Statement Execution API Support**: Added support for the [Databricks SQL Statement Execution API](https://docs.databricks.com/aws/en/dev-tools/sql-execution-tutorial), enabling direct SQL queries against Databricks SQL Warehouses for enhanced performance in analytics and reporting workflows.

Example `spicepod.yml` configuration:
```yaml
datasets:
  - from: databricks:spiceai.datasets.my_awesome_table 
    name: my_awesome_table
    params:
      mode: sql_warehouse
      databricks_endpoint: ${env:DATABRICKS_ENDPOINT}
      databricks_sql_warehouse_id: ${env:DATABRICKS_SQL_WAREHOUSE_ID}
      databricks_token: ${env:DATABRICKS_TOKEN}
```
