### ISSUE TITLE
What time will be removed accelerated data to free up memory with --pods-watcher-enabled setting

### ISSUE THREAD

**Issue by boer0924** [spiceai/spiceai#5762]
When disabling the acceleration configuration for a dataset with `--pods-watcher-enabled` setting, at what point will the already accelerated data be removed to free up memory

**Comment by phillipleblanc** [comment]
This largely depends on the memory allocator being used. The default allocator that Spice uses (`snmalloc`) likes to hold onto memory for while, but it does eventually release it. You can specify the system allocator when building spice with `alloc-system` which does a better job at returning memory immediately.

**Comment by boer0924** [comment]
It's a example config:
```yaml
datasets:
  - from: postgres:users
    name: users
    time_column: updated_at
    params:
      pg_host: postgres
      pg_db: postgres
      pg_user: postgres
      pg_pass: postgres
      pg_sslmode: disable
    acceleration:
      enabled: true
      engine: duckdb
```
If we're using DuckDB in memory mode, would it be possible to explicitly drop the accelerated tables once we detect that the dataset's acceleration has been disabled? This might help with immediate memory release rather than relying on the allocator's delayed behavior, Can it be done?
