### ISSUE TITLE
`location` metadata column should be the full path, not just the suffix

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#5777]
## Describe the bug

When setting the `location` metadata column using `metadata.location = enabled` on a dataset, it returns the path as a suffix of the full path, i.e.

`s3://my_bucket/some_table/part1=col1/part2=col2/data.parquet`

If the above is the full path, and the dataset is defined as:

```yaml
datasets:
  - from: s3://my_bucket/some_table/
    name: some_table
    metadata:
      location: enabled
```
Then the `location` column is currently returning as:
`part1=col1/part2=col2/data.parquet`. It should be `s3://my_bucket/some_table/part1=col1/part2=col2/data.parquet`
