### ISSUE TITLE
Bug: Error decoding ipc RecordBatch: Parser error: Cannot find a dictionary batch with dict id: 1

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#5863]
## Describe the bug

>sql> select * from my_table;
Unexpected Flight Error Decode error: Error decoding ipc RecordBatch: Parser error: Cannot find a dictionary batch with dict id: 1

```shell
sql> describe my_table;
+-------------+-------------------------+-------------+
| column_name | data_type               | is_nullable |
+-------------+-------------------------+-------------+
| id          | Int32                   | YES         |
| col1        | Dictionary(Int32, Utf8) | YES         |
| col2        | Dictionary(Int32, Utf8) | YES         |
+-------------+-------------------------+-------------+
```

```yaml
version: v1
kind: Spicepod
name: test

datasets:
  - name: my_table
    from: s3://spiceai-public-datasets/test_different_formats/dictionaries.parquet
```
