### ISSUE TITLE
Databricks `sql_warehouse` mode, datasets health monitor error

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#5912]
## Describe the bug

After dataset loaded and available in the runtime, health monitor check failed once with the error

```
2025-05-20T01:14:52.371427Z  INFO runtime::http: Spice Runtime HTTP listening on 127.0.0.1:8090
2025-05-20T01:14:53.823733Z  INFO runtime::init::dataset: Dataset messages registered (databricks:spiceai_sandbox.default.evgenii_messages), results cache enabled.
2025-05-20T01:14:55.217472Z  INFO runtime: All components are loaded. Spice runtime is ready!
2025-05-20T01:26:02.668533Z  WARN runtime::datasets_health_monitor: Failed to verify the dataset messages was available.
Failed to execute query.
Missing JSON field: result
```

spicepod

```yaml
version: v1
kind: Spicepod
name: databricks_demo
datasets:
  - from: databricks:spiceai_sandbox.default.evgenii_messages
    name: messages
    params:
      mode: sql_warehouse
      databricks_endpoint: ${ secrets:DATABRICKS_HOST }
      databricks_sql_warehouse_id: ${ secrets:DATABRICKS_SQL_WAREHOUSE_ID }
```

## To Reproduce

_Steps to reproduce the behavior:_

2. Click on '...'
3. Scroll down to '...'

## Expected behavior

_A clear and concise description of what you expected to happen._

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
