### ISSUE TITLE
`.acceleration.refresh_sql` ignores  `LIMIT n` for Github connector

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#6017]
## Describe the bug
The underlying GraphQL pagination is not working for the github connector. When the LIMIT > pagination size (github defaults to 100), the connector incorrectly early exits. 

## To Reproduce
```yaml
datasets:
  - from: github:github.com/spiceai/spiceai/pulls
    name: spiceai.issues
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
      refresh_sql: SELECT * FROM spiceai.issues limit 202
```
Notice
```shell
2025-05-28T01:51:11.396805Z  INFO runtime::accelerated_table::refresh_task: Loaded 100 rows (491.41 kiB) for dataset spiceai.issues in 2s 841ms.
```
