### ISSUE TITLE
Enhancement: Glue Data Connector

### ISSUE THREAD

**Issue by kczimm** [spiceai/spiceai#6080]
## Goal-State/What/Result

Connect directly to specific tables in your AWS Glue Data Catalog.

## Why/Purpose

Comprehensive Glue support is highly requested by customers.

## By When

**Issue/Spec written and reviewed:** June 4, 2025
**Done-Done:** June 6, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

A table in Glue can be specified using the following `spicepod.yaml`

```yaml
datasets:
    - from: glue:my_database.my_table
       name: my_table
       params:
           glue_auth: key
           glue_region: us-east-1
           glue_key: ${secrets:AWS_ACCESS_KEY_ID}
           glue_secret: ${secrets:AWS_SECRET_ACCESS_KEY}
```

where `my_database` is the name of the database and `my_table` is the name of the table in the Glue Data Catalog.

### Security Review

Currently used AWS authentication mechanisms are reused for the Glue Data Connector.

## How/Implementation Plan

The Glue Catalog Connector is already connecting to parquet and Iceberg tables.

- Refactor that work out of the catalog and into a data connector that is used by the catalog.
- Add support for the CSV data format.

## QA Plan

- Integration tests that read tables in Iceberg, parquet, and CSV tables.

## Release Notes

**Glue Data Connector Beta**: The Glue Data Connector enables you to connect directly to specific tables in your AWS Glue Data Catalog and query them using Spice.

```yaml
datasets:
    - from: glue:my_database.my_table
       name: my_table
       params:
           glue_auth: key
           glue_region: us-east-1
           glue_key: ${secrets:AWS_ACCESS_KEY_ID}
           glue_secret: ${secrets:AWS_SECRET_ACCESS_KEY}
```

Support is currently limited to the S3 data source and Iceberg tables or parquet and CSV data formats.
