### ISSUE TITLE
Bug `max_tokens_per_request` error when creating FinanceBench embeddings

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#6142]
## Describe the bug

>External error: External error: Failed to create embedding.
An error occurred: max_tokens_per_request: Requested 346134 tokens, max 300000 tokens per request (code: max_tokens_per_request)

## To Reproduce

```yaml
  - from: 
    description: Financial information
    name: financebench.data
    params: 
      file_format: txt
    acceleration:
      primary_key: location
      enabled: true
      engine: duckdb
      mode: file
    columns:
      - name: content
        description: Financial documents content
        embeddings:
          - from: openai_embed
            chunking:
              enabled: true
              target_chunk_size: 1000
              overlap_size: 200

embeddings:
  - from: openai:text-embedding-3-small
    name: openai_embed
    params:
      openai_api_key: ${secrets:OPENAI_API_KEY}
```
