### ISSUE TITLE
Bug. Failed to load LLM: o1 due to ` max_tokens or model output limit was reached`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#6146]
## Describe the bug

When FinanceBench is loaded there is the following error occurs **time to time** (restarting Spicepod helps to resolve this):

> 2025-06-07T19:31:07.185576Z  WARN runtime::init::model: Failed to load LLM: o1.
Failed to check the status of the model.
An error occurred: invalid_request_error: Could not finish the message because max_tokens or model output limit was reached. Please try again with higher max_tokens.
Verify the model configuration.

## To Reproduce

https://github.com/spiceai/spiceai/blob/trunk/test/financebench/spicepod_openai.yaml

```yaml
 - name: o1
    from: openai:o1-2024-12-17
    params:
      openai_reasoning_effort: high
      tools: list_datasets, table_schema, document_similarity
      openai_api_key: ${ secrets:OPENAI_API_KEY}
      system_prompt: *model_system_prompt
```
