### ISSUE TITLE
Enhancement: Results caching for embeddings

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#6180]
## Goal-State/What/Result

Embeddings requests against the same embedding model with the same content are cached.

## Why/Purpose

To improve the performance of embeddings, reducing costs by limiting embedding requests for the same content.

## By When

**Issue/Spec written and reviewed:** 16th Sep, 2025
**Done-Done:** 18th Sep, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

A `embeddings` section under `caching` is created:

```yaml
runtime:
  caching:
    embeddings:
      enabled: true
      max_size: 128mb
      item_ttl: 5s
      eviction_policy: lru
      hashing_algorithm: siphash
```

### Security Review

* Users should consider whether their embedded content is sensitive, and whether this data should be cached in memory. For these use-cases, users should disable the results cache.
* Malicious users could perform cache denial-of-service attacks, where they request excessive search terms or content which causes cache evictions of legitimate-use cache entries.
  * Users should ensure they use API keys to limit access to authorized users, preventing such requests from malicious users.

## How/Implementation Plan

* Embeddings cache is added to the `Caching` struct
* Embedding models take a reference to the `Caching` struct and return results from the cache if they exist
* Embedding models store results in the cache on completion. Records are stored per-item, so batched requests will create multiple cache entries (one for each item in the batch).

## QA Plan

* [x] Integration tests are added to test the efficiency of embeddings caching

## Release Notes

* **Caching Support for Embedding Requests:** The Runtime now supports caching embedding requests, improving the performance and reducing cost of embedding content and search requests.

Example `spicepod.yml`:

```yaml
runtime:
  caching:
    embeddings:
      enabled: true
      max_size: 128mb
      item_ttl: 5s
```

For more details, refer to the [Caching documentation](https://spiceai.org/docs/features/caching)
