### ISSUE TITLE
Bug: Full text search index does not use accelerated table for filter conditions

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#6214]
## Describe the bug
Given this spicepod

```yaml
datasets:
  - from: github:github.com/spiceai/docs/pulls
    name: doc.pulls
    params:
      github_token: ${secrets:GITHUB_TOKEN}
    acceleration:
      enabled: true
    columns:
      - name: title
        full_text_search:
          enabled: true
          row_id:
            - id
      - name: body
        full_text_search:
          enabled: true

embeddings:
  - name: hf_minilm
    from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
```

Running the following is slow because the full text search CandidateGeneration is not using the accelerated table, and has to fall back to Github API.
```shell
>>> curl -XPOST http://localhost:8090/v1/search \
    -H "Content-Type: application/json" \
    -d '{
        "datasets": ["doc.pulls"],
        "text": "Glue data",
        "limit": 3,
        "where": "comments_count>1"
```
