### ISSUE TITLE
Enhancement: CDC Snapshot from external dataset

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#6230]
## Goal-State/What/Result

Debezium CDC accelerations can be bootstrapped using an external dataset and offset.

## Why/Purpose

Required for bootstrapping a Debezium dataset without replaying all changes.

## By When

**Issue/Spec written and reviewed:** _Target Date_
**Done-Done:** _Target Date_

## Done-Done

- [ ] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Release Notes / PRFAQ
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Telemetry / Metrics / Task History
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Cookbook Recipes/Tutorials

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Specification

_Work in progress_
```yaml
datasets:
  - from: iceberg:my_table
     name: my_table
     params....

  - from: debezium:my_kafka_topic_with_debezium_changes
    name: deb_table
    params:
       debezium_initial_snapshot_from: my_table
       max_lag: 30m
```

`/v1/ready` only turns ready when initial snapshot read is complete and all changes have been applied.
