### ISSUE TITLE
Glue catalog connector returns empty table when `include` is not specified

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#6250]
## Describe the bug

Glue catalog data connector 0 schema 0 table when `include` is not specified.

## To Reproduce

Use the spice ai glue catalog data connector test endpoint.

First use the following spicepod.yaml configuration:
```yaml
version: v1
kind: Spicepod
name: glue-connector-demo
catalogs:
  - from: glue
    name: my_glue_catalog
    # include:
    #   - security_logs.*
    params:
      glue_auth: key
      glue_region: ${env:GLUE_AWS_REGION}
      glue_key: ${env:GLUE_AWS_ACCESS_KEY_ID}
      glue_secret: ${env:GLUE_AWS_SECRET_ACCESS_KEY}
```
Observe in runtime log that 0 schema and 0 tables are loaded:
```
2025-06-16T19:17:20.006244Z  INFO runtime::init::catalog: Registering catalog 'my_glue_catalog' for glue
2025-06-16T19:17:22.234584Z  INFO runtime::init::catalog: Registered catalog 'my_glue_catalog' with 0 schemas and 0 tables
```

Uncomment the include clauses and restart runtime
```yaml
version: v1
kind: Spicepod
name: glue-connector-demo
catalogs:
  - from: glue
    name: my_glue_catalog
    include:
      - security_logs.*
    params:
      glue_auth: key
      glue_region: ${env:GLUE_AWS_REGION}
      glue_key: ${env:GLUE_AWS_ACCESS_KEY_ID}
      glue_secret: ${env:GLUE_AWS_SECRET_ACCESS_KEY}
```
Observe in runtime log that tables in security_logs schema are loaded:
```
2025-06-16T19:18:33.514918Z  INFO runtime::init::catalog: Registering catalog 'my_glue_catalog' for glue
2025-06-16T19:18:33.515174Z  INFO runtime::http: Spice Runtime HTTP listening on 127.0.0.1:8090
2025-06-16T19:18:35.729942Z  INFO runtime::init::catalog: Registered catalog 'my_glue_catalog' with 1 schema and 1 table
```

## Expected behavior

Glue catalog connector should load all tables in all schemas when the include is not specified.

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
