### ISSUE TITLE
Glue data connector returns uninformative `service error` when connecting to an non-exist table

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#6251]
## Describe the bug

Glue data connector returns uninformative `service error` when connecting to an non-exist table

## To Reproduce

Connect to a non-exist table using the glue data connector
```yaml
version: v1
kind: Spicepod
name: glue-connector-demo
datasets:
  - from: glue:blah.blah
    name: lineitem
    params:
      glue_region: ${env:AWS_REGION}
      glue_key: ${env:AWS_ACCESS_KEY_ID}
      glue_secret: ${env:AWS_SECRET_ACCESS_KEY}
```

Observe the error log, which doesn't indicate the table / schema name doesn't exist
```
2025-06-16T19:19:53.640994Z  WARN runtime::init::dataset: Cannot connect to the dataset lineitem (glue).
service error
```

## Expected behavior

Glue data connector emit a more informative error when schema / table doesn't exist, something like:
```
Table `blah.blah` doesn't exist, ensure the table path exist and try again 
```

### Spicepod

_Add the relevant `spicepod.yml` section._

### Output of `describe table`

_Add any relevant `describe table` output here._

### Output of `explain query`

_Add any relevant `explain query` output here._

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`
