### ISSUE TITLE
Duplicate key in schema for databricks `mode: sql_warehouse`

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#6253]
Issue with databricks `mode: sql_warehouse`.
```yaml
datasets:
  - from: databricks:spiceai_sandbox.tpch.customer
    name: db_uc_sql
    params:
      mode: sql_warehouse
      databricks_sql_warehouse_id: "2f4e22bff398fb84"
      # databricks_token: ${secrets:DATABRICKS_PAT}
      databricks_client_id: ${secrets:DATABRICKS_SP_CLIENT_ID}
      databricks_client_secret: ${secrets:DATABRICKS_SP_CLIENT_SECRET}
      databricks_endpoint: ${secrets:DATABRICKS_HOST}
```

Errors: 
```sql
select * from db_uc_sql limit 4;
```
```shell
Query Error: Schema contains duplicate qualified field name db_uc_sql.c_customer_sk
```

Which is true
```sql
describe db_uc_sql;
```
```shell
+------------------------+-------------------+-------------+
| column_name            | data_type         | is_nullable |
+------------------------+-------------------+-------------+
| c_customer_sk          | Int32             | YES         |
| c_customer_id          | Utf8              | YES         |
| c_current_cdemo_sk     | Int32             | YES         |
| c_current_hdemo_sk     | Int32             | YES         |
| c_current_addr_sk      | Int32             | YES         |
| c_first_shipto_date_sk | Int32             | YES         |
| c_first_sales_date_sk  | Int32             | YES         |
| c_salutation           | Utf8              | YES         |
| c_first_name           | Utf8              | YES         |
| c_last_name            | Utf8              | YES         |
| c_preferred_cust_flag  | Utf8              | YES         |
| c_birth_day            | Int32             | YES         |
| c_birth_month          | Int32             | YES         |
| c_birth_year           | Int32             | YES         |
| c_birth_country        | Utf8              | YES         |
| c_login                | Utf8              | YES         |
| c_email_address        | Utf8              | YES         |
| c_last_review_date_sk  | Int32             | YES         |
| c_customer_sk          | Int32             | YES         |
| c_customer_id          | Utf8              | YES         |
| c_current_cdemo_sk     | Int32             | YES         |
...
```
