### ISSUE TITLE
Enhancement: Views support cron-based refreshes

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#6266]
## Goal-State/What/Result

Similar to datasets, views support cron-based refreshes to refresh views on a schedule.

## Why/Purpose

To align with the behavior of dataset refreshes, and provide the ability to refresh views on a defined schedule.

## By When

**Issue/Spec written and reviewed:** 29th Jun, 2025
**Done-Done:** 30th Jun, 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

A `refresh_cron` parameter is supported on the View acceleration parameters, replicating the existing parameter for datasets:

```yaml
views:
  - name: my_view
    sql: SELECT 1
    acceleration:
      refresh_cron: "* * * * *" # Every minute
      enabled: true
```

For all cron-based schedules, a minimum refresh period of 1 second is applied.

### Security Review

* If the `cron_refresh` parameter is set with too short of a refresh, there is a risk that excessive refresh frequencies cause a Denial-of-Service
  * Ensure that only authorized users have access to the spicepod to modify acceleration settings
  * Enforce a minimum refresh period of 1 second
* Resource contention could occur from many components scheduled to refresh at the same time
  * The scheduler should include a configuration for jitter, and apply a jitter delay before executing a refresh for a component

## How/Implementation Plan

* Views cron refresh replicates the behavior of dataset refresh, where it creates a scheduler for all views and adds eligible views with cron configurations to the scheduler

## QA Plan

- [x] An integration test is created to validate that views cron refreshes correctly refresh their data

## Release Notes

**Scheduled View Refreshes:** Views now support scheduled refreshes via a `refresh_cron` parameter, enabling acceleration updates on a defined interval.

Example Spicepod.yml configuration:
```yaml
views:
  - name: my_view
    sql: SELECT 1
    acceleration:
      enabled: true
      refresh_cron: "0 * * * *" # Every hour
```

For more details, refer to [Scheduled Refreshes](#).
