### ISSUE TITLE
Bug: env Secrets in lowercase are not detected

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#6283]
## Describe the bug

>2025-06-19T18:15:25.083364Z ERROR runtime::secrets: Key 'openaiapikey' not found in any connected secrets.

.env
```
openaiapikey="sk-..."
```

Spicepod

```yaml
name: test-app
kind: Spicepod
version: v1

models:   
  - from: openai:gpt-4.1
    name: test_model
    params:
      openai_api_key: ${secrets:openaiapikey}
      tools: auto
```

if I replace `openaiapikey` -> `OPENAIAPIKEY` in both Spicepod and env file then it works.
