### ISSUE TITLE
Bug: Make DynamoDB connector connection error more specific and actionable

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#6290]
## Describe the bug

There is the same error in multiple different cases when unable to connect to DynamoDB table. The connection error must be more specific and actionable

>2025-06-20T19:04:09.617794Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
service error

1. invalid table name (does not exist)
1. invalid credentials, for example expired dynamodb_aws_session_token param
1. dynamodb_aws_session_token was not provided/missing

## To Reproduce

Try using invalid table name, expired session token, invalid access key.

```yaml
datasets:
- from: dynamodb:sales_transactions
  name: sales_transactions
  params:
      dynamodb_aws_region: ${secrets:SPICE_AWS_REGION}
      dynamodb_aws_access_key_id: ${secrets:SPICE_AWS_ACCESS_KEY_ID}
      dynamodb_aws_secret_access_key: ${secrets:SPICE_AWS_SECRET_ACCESS_KEY}
      dynamodb_aws_session_token: ${secrets:SPICE_AWS_SESSION_TOKEN}
```

>2025-06-20T19:04:09.617794Z  WARN runtime::init::dataset: Failed to load the dataset sales_transactions (dynamodb).
service error
