### ISSUE TITLE
Enhancement: Oracle Data Connector

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#6314]
## Goal-State/What/Result

Spice can be used to query and accelerate datasets stored in Oracle Database:
 - Oracle On-Prem hosted Databases
 - Oracle Cloud User-Managed Databases
 - Oracle Cloud Autonomous Databases (Serverless)

## Why/Purpose

There is a large community of Oracle users attempting to integrate with Spice, but the lack of a dedicated connector creates a significant barrier.

## By When

**Issue/Spec written and reviewed:** 06/24
**Done-Done:** 07/14

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Specification

`oracle:` prefix is used to define Oracle Database data connector

```yaml
# On-premise Oracle instance
datasets:
  - from: oracle:"SH"."PRODUCTS"
    name: sh.products
    params: 
      oracle_host: 127.0.0.1
      oracle_username: scott
      oracle_password: tiger
```

### Auth / Configuration

Support login based authentication only. `OS Authentication` is out of scope for alpha release.

**oracle_host** - the hostname or IP address of the Oracle Database instance. Requried
**oracle_port** - the host port of the Microsoft SQL Server instance. Optional. Default is `1521`
**oracle_username** - the username. Required
**oracle_password** - the password associated with the specified SQL user
**oracle_service_name** - the Oracle Database service name to connect to. Optional. Default to `XEPDB1`
Not supported by Spice, as **oracle_service_name** is modern and recommended configuration, supported since Oracle v9 (2001)
**oracle_connection_string** - the raw connection string (TNS alias from tnsnames.ora for mTLS/Wallet or Easy Connect strings for TLS connection). Note: oracle python library name it as `dsn`
**oracle_wallet_sso_cert**: The base64-encoded `cwallet.sso` (wallet auto-login certificate) to use for mTLS authentication.
**oracle_wallet**: Specifies the Oracle wallet location used to save the provided mTLS certificate or retrieve an existing/pre-downloaded certificate. See [TNS_ADMIN documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/ntqrf/about-tns-admin-parameter.html) for details.

Example connection UI from Oracle SQL Developer

https://docs.oracle.com/en/database/oracle/oracle-database/tutorial-create-conn/index.html
<img width="239" alt="Image" src="https://github.com/user-attachments/assets/24850e93-9fa4-4453-b953-d0d62b95a93f" />
![Image](https://github.com/user-attachments/assets/f91bbb5a-bee8-4d9f-a794-5aa48b6d9de6)

### Oracle Cloud (Autonomous DB)
 
See connection options: #6357
 
**mTLS (Wallet-based)**

```yaml
  - from: oracle:"SALES"
    name: my.sales
    params:
      oracle_username: admin
      oracle_password: ${SPICE_ORACLE_PASSWORD}
      # TNS alias;
      oracle_connection_string: 'fgp1tqxys1e_low'
      # this can also be specified via env::TNS_ADMIN
      oracle_wallet: 'path/to/existing/wallet'


  - from: oracle:"SALES"
    name: my.sales
    params:
      oracle_username: admin
      oracle_password: ${SPICE_ORACLE_PASSWORD}
      # base64 encoded cwallet.sso
      oracle_wallet_sso_cert:  ${SPICE_ORACLE_WALLET_SSO_CERT}
      oracle_connection_string: '(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.us-sanjose-1.oraclecloud.com))(connect_data=(service_name=g81f1d801d5c853_fgp1t_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))'
```

TNS_ADMIN Parameter - controls where Oracle wallet/configuration is located.
You can add the parameter TNS_ADMIN to change the directory path of Oracle Net Services configuration files from the default location of ORACLE_HOME\network\admin.

**Easy Connect string (no wallet required for TLS-only)**

```yaml
- from: oracle:"SALES"
    name: my.sales
    params:
      oracle_username: admin
      oracle_password: ${SPICE_ORACLE_PASSWORD}
      # Easy Connect string (no wallet required for TLS-only)
      oracle_connection_string: 'tcps://adb.us-sanjose-1.oraclecloud.com:1522/g81f1d801d5c853_fgp1tqxyc1e_low.adb.oraclecloud.com?ssl_server_dn_match=yes'
```

### Other

1. No federation,
2. No full push-downs support are in scope for alpha support (note: this will be fully supported out of the box with data acceleration enabled).

### Security Review

1. Use parametrized queries (for example for native schema inference) to avoid potential sql injection using table name

## How/Implementation Plan

1. The `oracle` feature is added (`CARGO_FEATURES`) to control whether the Oracle data connector and its dependencies are included in the build. **Enabled by default.**
2. [Oracle](https://crates.io/crates/oracle) — the Rust crate — is used for the implementation. It is based on the [ODPI-C](https://oracle.github.io/odpi/) library, which must be installed/configured manually by following the official [Oracle installation instructions](https://odpi-c.readthedocs.io/en/latest/user_guide/installation.html). Otherwise, a user-friendly message with the Spice documentation with installation link is shown.
3. Implementation steps are tracked as enhancement sub-issues.

## QA Plan

- [x] Integration tests that includes main supported data types and filters pushdown using  [Oracle Database XE Release 21c (21.3.0.0) Docker Image](https://container-registry.oracle.com/ords/f?p=113:4:3016724055031:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:803,803,Oracle%20Database%20Express%20Edition,Oracle%20Database%20Express%20Edition,1,0&cs=3ifiVs6zybTrDduVyHHChcryiWtBYdk-YF9MvaG3_uRwFyvfX207Kjtdjn5nhBny_ZSAQqGSUCoxNPtXd-FFqmA) 

- https://github.com/spiceai/spiceai/issues/6337
- https://github.com/spiceai/spiceai/issues/6356
- https://github.com/spiceai/spiceai/issues/6357

## Release Notes

Highlights for 1.5.0 release.

**Oracle Data Connector**: Use `from: oracle:` to access and accelerate data stored in Oracle database, deployed on-premises or in the cloud.

Example `Spicepod.yml`:

```yaml
datasets:
  - from: oracle:"SH"."PRODUCTS"
    name: products
    params: 
      oracle_host: 127.0.0.1
      oracle_username: scott
      oracle_password: tiger
```

See the [Oracle Data Connector documentation](https://spiceai.org/docs/components/data-connectors/oracle).
