### ISSUE TITLE
Enhancement: AWS Bedrock Models Provider

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#6340]
## Goal-State/What/Result
Configure and run Amazon Bedrock Nova models in the Spice runtime.

## Why/Purpose
Users of the Spice runtime can currently use Amazon bedrock as an embedding provider. Enabling support for language models increases this scope of integration.

## By When

**Issue/Spec written and reviewed:** 29th July 2025
**Done-Done:** 31st July 2025

## Done-Done

- [x] [Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Release Notes / PRFAQ
- [x] Threat Model / Security Review
- [x] Tests
- [x] Telemetry / Metrics / Task History
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Cookbook Recipes/Tutorials

## Specification

Use same Amazon specific parameters as [embedding models](https://spiceai.org/docs/components/embeddings/bedrock#aws-parameters).

For [guardrails](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_GuardrailConfiguration.html)

- `bedrock_guardrail_identifier` (String): The identifier for the guardrail.
  - Length in [0, 2048] inclusive.
  - Pattern: `(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+))`.
- `bedrock_guardrail_version` (String): The version of the guardrail. 
  - Pattern: `(([1-9][0-9]{0,7})|(DRAFT))`
- `bedrock_trace`: The trace behavior for the guardrail.
  - Valid Values: `enabled` | `disabled` | `enabled_full` default `disabled`.

For [OpenAI overrides](https://spiceai.org/docs/features/large-language-models/parameter_overrides), the following subet: `maxTokens`, `temperature`, `topP`, `topK`, `stopSequences` will be supported. Support will be come by supporting these values in the request payload.

Model Ids:
 - `us.amazon.nova-lite-v1:0`
 - `us.amazon.nova-micro-v1:0`
 - `us.amazon.nova-premier-v1:0`
 - `us.amazon.nova-pro-v1:0`

```yaml
models:
  - from: bedrock:us.amazon.nova-lite-v1:0
    name: novash
    params:
      aws_region: us-east-1
      aws_access_key_id: ${ secrets:AWS_ACCESS_KEY_ID }
      aws_secret_access_key: ${ secrets:AWS_SECRET_ACCESS_KEY }

      bedrock_guardrail_identifier: arn:aws:bedrock:abcdefg012927:0123456789876:guardrail/hello
      bedrock_guardrail_version: DRAFT
      bedrock_trace: enabled

      bedrock_temperature: 42
```

### Security Review
 - No change in scope to capabilities of `models`.
 - No change in authz/authn scope if Bedrock integration.

## How/Implementation Plan
 - Prerequisite: https://github.com/spiceai/spiceai/pull/6626
 - Implement generic bedrock language model integration using Invoke API (this is to support future language models that do not support `converse` API).
 - Add guardrail capabilities
 - Add Bedrock to extended tests.

## QA Plan
 - Alpha level testing of bedrock models in extended tests.
 - Manual testing of guardrail functionality
