### ISSUE TITLE
Local Server Connection in AI Model Providers

### ISSUE THREAD

**Issue by javialvarezcostas** [spiceai/spiceai#6342]
# Problem
We have a gpt4 model and a Llama model hosted on a custom company platform and is not possible to connect to them with Spice.ai

# Feature Request
Implement connection to on-premise hosted AI models via custom endpoints outside openai

**Comment by phillipleblanc** [comment]
@javialvarezcostas It is possible to connect to any OpenAI compatible provider (including on-premise hosted AI models) using the `openai` model provider and providing the `endpoint` parameter. See https://spiceai.org/docs/components/models/openai

i.e.

```yaml
models:
  - from: openai:your-onprem-model
    name: onprem-model
    params:
      endpoint: https://api.openai.com/v1 # Override to use a compatible provider (i.e. NVidia NIM)
```
