### ISSUE TITLE
Data in dataset with append `refresh_mode` is never deleted

### ISSUE THREAD

**Issue by mitchdevenport** [spiceai/spiceai#854]
**Describe the bug**
According to https://docs.spiceai.org/reference/spicepod/datasets/, data in an `append` dataset should be deleted based on the `retention` field, but this field is not honored and data is never deleted.

**To Reproduce**

1. Run spiced with the following dataset

```
- from: spice.ai/eth.recent_blocks
  name: eth_recent_blocks
  acceleration:
    enabled: true
    refresh_mode: append
    retention: 1m
```
2. Observe that data is never deleted

**Expected behavior**
Data should be deleted once it is older than the set retention
