### ISSUE TITLE
Bug: No way via CLI to login to a PostgreSQL server

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#863]
**Describe the bug**
When attempting to use the PostgreSQL data connector with a secret stored in the file secret store - there is no CLI command to generate the correct secret structure, leaving a user unable to actually use the PostgreSQL connector.

**To Reproduce**
Navigate to the docs for PostgreSQL https://docs.spiceai.org/connectors/postgres/

Create a PostgreSQL dataset based on the example given:

```yaml
datasets:
  - from: postgres:path.to.my_dataset
    name: my_dataset
    params:
        pg_host: localhost
        pg_port: 5432
        pg_db: my_database
        pg_user: my_user
        pg_pass_key: my_secret
```

Start the runtime, get an error that `my_secret` doesn't exist.
