### ISSUE TITLE
Bug: Better experience when PostgreSQL DataConnector cannot connect

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#864]
**Describe the bug**
If a user inputs the incorrect parameters for connecting to a PostgreSQL database, it takes 30 seconds before any feedback is given to the user that something went wrong, and the error message shown is too verbose.

**To Reproduce**
Create a PostgreSQL dataset with the following configuration:

```yaml
from: postgres:hello
name: pg_source
params:
    pg_host: localhost
    pg_port: 5432
    pg_db: postgres
    pg_user: postgres
    pg_pass_key: my_secret
```

Start the runtime, observe that nothing happens for 30 seconds and then this gets printed out:
`2024-03-19T15:29:23.611094Z  INFO runtime::opentelemetry: Spice Runtime OpenTelemetry listening on 127.0.0.1:50052
2024-03-19T15:29:53.612321Z  WARN runtime: Failed to initialize data connector for dataset pg_source, retrying: Unable to attach data connector postgres: Unable to register table: Unable to get table provider: Unable to get a DB connection from the pool: ConnectionPoolRunError: Timed out in bb8`

**Expected behavior**
An error is logged immediately when the connection cannot be made - this should be essentially the same as a connection refused error - we should know immediately if the port is open or not. If the port is open and the server isn't responding, then we should have a smaller timeout window - maybe closer to 5 seconds.

The error message logged should follow the guidelines for showing user errors: https://github.com/spiceai/spiceai/blob/trunk/docs/dev/user_facing_errors.md
