### ISSUE TITLE
Errors when a data backend does not support a type are unclear and inconsistent

### ISSUE THREAD

**Issue by mitchdevenport** [spiceai/spiceai#878]
**Describe the bug**
We should have consistent and clear error messages when a data backend does not support a data type. We should also clearly distinguish between a lack of support in our code and a true limitation of the backend store. The error should also link to documentation on backends and supported types.

**To Reproduce**

Run `spice run` with the following datasets:

```
- from: spice.ai/eth.recent_transactions
  name: eth_recent_transactions
  acceleration:
    enabled: true
    refresh_mode: full
    refresh_interval: 10s
    engine: duckdb

- from: spice.ai/eth.recent_transactions
  name: eth_recent_transactions
  acceleration:
    enabled: true
    refresh_mode: full
    refresh_interval: 10s
    engine: sqlite
```

Observe the inconsistent and nasty error messages:

```
thread '<unnamed>' panicked at /Users/mitch/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-query-0.30.7/src/backend/sqlite/table.rs:181:41:
not implemented: Array is not available in Sqlite.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
Nested list is not supported yet.
thread 'tokio-runtime-worker' panicked at /Users/mitch/.cargo/git/checkouts/duckdb-rs-7cfb8083041eafcf/4e1cf06/src/vtab/arrow.rs:381:13:
not yet implemented
fatal runtime error: Rust panics must be rethrown
os: process already finished
```
