### ISSUE TITLE
Running `spice dataset configure` replaces most of the contents of existing spicepod.yaml

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#879]
**Describe the bug**

I have existing spicepod:

```yaml
version: v1beta1
kind: Spicepod
name: test_spice_app
secrets:
  store: env
```

After running `spice dataset configure`, it replaced all lines after name

```yaml
version: v1beta1
kind: Spicepod
name: test_spice_app
datasets:
- ref: datasets/eth_recent_blocks
```

**To Reproduce**

1. init new spicepod
2. add some additional configuration
3. run `spice dataset configure`, follow the prompts

**Expected behavior**

Spice dataset configure should update only datasets section of spicepod.yaml
