### ISSUE TITLE
Setting the `endpoint` parameter for the S3 DataConnector for AWS S3 breaks

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#895]
**Describe the bug**
When setting the `endpoint` parameter to the same value in the [docs for S3](https://docs.spiceai.org/connectors/s3/), it stops the runtime from being able to load the parquet file with the following error:

```bash
WARN runtime: Failed to initialize data connector for dataset s3_source, retrying: Unable to attach data connector s3: Unable to register table: Unable to get table provider: Object Store error: Generic S3 error: Client error with status 403 Forbidden: No Body
```

**To Reproduce**
Set up an S3 dataset, here is a minimal example: 
```yaml
from: s3://phillip-parquet/beacon_attestations_06142200_06142209.parquet
name: s3_source
params:
  region: "ap-northeast-2"
```

**Expected behavior**
The quickstart continues to work.

**Screenshots**

**Additional context**
