### ISSUE TITLE
Unsupported column type Varchar (Postgres dataconnector)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#904]
**Describe the bug**

I see the following error when using Postgres as data source and table from [TCP-H benchmark](https://www.tpc.org/tpch/)  

thread 'tokio-runtime-worker' panicked at crates/arrow_sql_gen/src/postgres.rs:355:14:
not implemented: Unsupported column type Varchar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Spice should NOT crash. There should be user friendly warning instead**

**To Reproduce**

1. Create Postgres table using schema below

```
CREATE TABLE public.customer (
	c_custkey int4 NOT NULL,
	c_name varchar(25) NOT NULL,
	c_address varchar(40) NOT NULL,
	c_nationkey int4 NOT NULL,
	c_phone bpchar(15) NOT NULL,
	c_acctbal numeric(15, 2) NOT NULL,
	c_mktsegment bpchar(10) NOT NULL,
	c_comment varchar(117) NOT NULL
);
```
2.  Add created Postgres table above as data source to your spicepod ([instructions](https://docs.spiceai.org/connectors/postgres/))  
3. Run Spice
5. See error

thread 'tokio-runtime-worker' panicked at crates/arrow_sql_gen/src/postgres.rs:355:14:
not implemented: Unsupported column type Varchar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Screenshots**
![image](https://github.com/spiceai/spiceai/assets/981580/c95f3370-fb00-487e-b13e-46d3dfe7b8bb)

**Additional context**
customer table above is part of [TCP-H benchmark](https://www.tpc.org/tpch/)

Spice dataset definition:
```
from: postgres:customer
name: customer
acceleration:
  enabled: true
  refresh_interval: 10s
  refresh_mode: full
params:
  pg_host: localhost
  pg_port: 5433
  pg_db: tpch
  pg_user: postgres
  # pg_pass_key: password

```
