### ISSUE TITLE
Bug: spice can't read number parameters from inline datasets definitions

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#912]
**Describe the bug**
If dataset configured inline in spicepod.yaml and has some numeric param value (like pg port) spice fails to load it

**To Reproduce**

Using following spicepod
```yaml
version: v1beta1
kind: Spicepod
name: models-demo

datasets:
  - from: postgres:eth_recent_blocks
    name: eth_recent_blocks
    description: eth recent blocks
    params:
      pg_host: localhost
      pg_port: 5432
      pg_db: testdb
      pg_user: postgres
      pg_pass_key: password
```

Spice runtime fails to parse it:

![CleanShot 2024-03-25 at 16 27 12@2x](https://github.com/spiceai/spiceai/assets/827338/66f2f064-8f32-4f03-a36e-3c7fa169455d)

**Expected behavior**
Spice runtime properly loads inline datasets with numeric param values
