### ISSUE TITLE
FTP/SFTP Data Connector

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#996]
## Goal-State/What/Result

Spice OSS user can access csv and parquet files from FTP / SFTP file server through Spice Runtime

Milestones:

- M1 Prototyping with access parquet files from SFTP file server.
- M2 CSV files support
- M3 Quickstarts and documentation.

## Why/Purpose

FTP / SFTP protocol is widely used for file transfer in organizations. Supporting a data connector to FTP / SFTP server will benefit 
 users who need to fetch data from FTP / SFTP server.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** April 15th

**M1:** FTP Support with Parquet
**M2:** SFTP Enhancement
**M3:** CSV with Schema inference
...
**Done-Done:** 5/20

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

Based on Datafusion CSV functionality. 

Example definition for sftp parquet
```
from: sftp://host/path-to-dataset/
name: taxi_trips
description: taxi trips
params:
  data_format: parquet
  sftp_user: <user>
  sftp_password: <pwd>
  sftp_tcp_port: 22  
acceleration:
  enabled: true
  refresh_check_interval: 10s
  refresh_mode: full
```

Example definition for ftp parquet
```
from: ftp://host/path-to-dataset/
name: taxi_trips
description: taxi trips
params:
  data_format: parquet
  ftp_user: <user>
  ftp_password: <password>
  ftp_tcp_port: 21
acceleration:
  enabled: true
  refresh_check_interval: 10s
  refresh_mode: full
```

Example definition for sftp csv
```
from: sftp://host/path-to-dataset/
name: taxi_trips
description: taxi trips
params:
  csv_delimeter: ';'
  csv_quote: '"'
  csv_schema:
    id: Int64
    name: Utf8
  data_format: csv
  sftp_user: <user>
  sftp_password: <password>
  sftp_tcp_port: 22  
acceleration:
  enabled: true
  refresh_check_interval: 10s
  refresh_mode: full
```

Example definition for ftp csv
```
from: ftp://hosy/path-to-dataset/
name: taxi_trips
description: taxi trips
params:
  csv_delimeter: ';'
  csv_quote: '"'
  csv_schema:
    id: Int64
    name: Utf8
  data_format: csv
  ftp_user: <user>
  ftp_password: <password>
  ftp_tcp_port: 21
acceleration:
  enabled: true
  refresh_check_interval: 10s
  refresh_mode: full
```

## How/MAP

* Find a suitable Rust ftp / sftp client
   * [openssh-sftp-client](https://crates.io/crates/openssh-sftp-client) Most downloads, async support
* Figure out Datafusion support on .csv files
   * Similar to parquet, [read_csv](https://docs.rs/datafusion/latest/datafusion/execution/context/struct.SessionContext.html#method.read_csv)  
* Spicepod parameters for FTP / SFTP connection
    * Server
    * Port
    * Username
    * Password
    * SSH Private Key

### Implementation (issues)

- https://github.com/spiceai/spiceai/pull/1414 
- https://github.com/spiceai/spiceai/pull/1355
- https://github.com/spiceai/spiceai/pull/1404
- https://github.com/spiceai/spiceai/pull/1399
- https://github.com/spiceai/spiceai/pull/1378
- https://github.com/spiceai/docs/pull/246
- https://github.com/spiceai/quickstarts/pull/113
